### ISSUE TITLE
Path's dopesheet keys are not moved when changing parent of path

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#101]
Repro:
1. Create path on Root bone.
2. Constraint bone(s) to path.
3. Create a couple of position keys on the timeline (doesn't matter which type of key).
4. Create a new bone parented to the root bone.
5. Drag the path on to the newly created bone.
Dopesheet root bone will still hold "Path position: pathName".
6. Set keys again on the path. 
Now we have the same path showing up twice in the dopesheet.,,

**Comment by NathanSweet** [comment]
3.5.00-beta
