### ISSUE TITLE
Unresponsive window/hard crash using alt+tab+click to switch repeatedly

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-editor#106]
See http://esotericsoftware.com/forum/Win-10-Two-monitors-Hard-crasj-6834?p=31602&hilit=unresponsive#p31602 and e-mail by David.

**Comment by pharan** [comment]
Renamed the title. I was able to repro it with only one monitor.
bcats outlined the simple repro steps here:
http://esotericsoftware.com/forum/Spine-freezes-7137

**Comment by NathanSweet** [comment]
Fixed in 3.5.03-beta, users verified.
