### ISSUE TITLE
Export improvements

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#11]
- [x] Images: always use a prefix http://www.esotericsoftware.com/forum/viewtopic.php?f=3&t=753
- [x] Video: allow exporting all animations http://www.esotericsoftware.com/forum/viewtopic.php?f=3&t=1892
- [x] Video: Loop quantity http://www.esotericsoftware.com/forum/viewtopic.php?f=3&t=1882
- [x] Scale for exporting images and video, for when disable inherit scale is used in the skeleton http://www.esotericsoftware.com/forum/viewtopic.php?f=3&t=2114
- [x] Specify an animation to export rather than "current".
- [x] Export multiple animations at once. People use this for sharing animation previews. For images, checkbox to create each in a subfolder?
- [x] Allow a size to be specified so image sequences use the same world origin http://esotericsoftware.com/forum/Pivot-Problem-On-Export-Sequence-Anim-5585 Alternatively, provide the ability to set (and animate) a viewport rectangle which is used for image/video export. http://esotericsoftware.com/forum/viewtopic.php?f=3&t=262
- [x] Zero padding for numbers in image file names.
- [x] Export multiple skeletons as a single PNG frame or sequence, rather than one per skeleton. http://esotericsoftware.com/forum/Export-single-PNG-file-instead-of-multiple-3411#p31308
- [x] Should be possible to choose "All animations" for GIF export, as it is for PNG and JPEG. http://esotericsoftware.com/forum/Animated-GIF-export-size-6363
- [x] Remember export settings per project.
- [x] Option to only export specific skeletons and animations.
- [x] When exporting an image sequence, allow specifying if it is looping to avoid writing duplicate start and end frames.
- [x] Allow exporting only a portion of images. http://esotericsoftware.com/forum/Export-parts-of-timeline-9505
- [x] Two modes for packing when doing data export: 1) as it is now, pack only images used in the project, and 2) just run the packer on the images dir (enables using pack.json) http://esotericsoftware.com/forum/viewtopic.php?f=9&t=1265
- [x] High quality and faster GIF export.
- [x] Additional settings to control GIF dithering and alpha.

**Comment by erikari** [comment]
- [ ] frames instead of FPS for gif export
- [ ] "Skip last frame" option for looping animations
http://esotericsoftware.com/forum/Add-export-in-frame-count-not-in-FPS-9796

**Comment by pharan** [comment]
Use case for zero-padding numbers:
http://esotericsoftware.com/forum/Index-number-when-exporting-frames-9967

**Comment by erikari** [comment]
+ 1 for export animations with mixing and batch export videos http://esotericsoftware.com/forum/Feature-Requests-10019

**Comment by erikari** [comment]
Video/image export size is now defined as a separate issue here: https://github.com/EsotericSoftware/spine-editor/issues/334

**Comment by NathanSweet** [comment]
@erikari [This thread](http://esotericsoftware.com/forum/Export-single-PNG-file-instead-of-multiple-3411#p31308) doesn't make sense. You say if you select a folder, you get sets of PNGs for each skeleton and if you **don't** select a folder you get a single set of PNGs containing all the skeletons. The problem: you *always* have to specify a folder when exporting a PNG sequence.

Note if you select all animations or all skins then you will get sets of PNGs for each skeleton. This is because it wouldn't make sense to export a combination of every animation/skin with every other animation/skin for every skeleton. `skeletons * animations * skins` could be a huge number of combinations and probably not what you want.

The relevant part of the new GIF export UI (which will also be used for PNGs) looks like:
![](http://n4te.com/x/4492-Ci27.png)
If you want all skeletons in a single set of PNGs, you must choose all/current/current. *Any* other combination of settings results in sets of PNGs for each skeleton. If I understand correctly, this solves your problem and I can check the box in the issue above.

**Comment by NathanSweet** [comment]
We could make this more clear by showing whether it will be all skeletons in one set of images, or separate sets of images:
![](http://n4te.com/x/4493-zVTF.png)
If together is chosen, animation/skin must be current/current. If animation/skin are set to anything else, together changes to all.

**Comment by erikari** [comment]
@NathanSweet  well, I made that post an year and a half ago, which was before I made bug reports with gifs. Anyway, that was a bug, so it actually makes sense that it doesn't make sense since I shouldn't have been allowed to do what I did. I also did it various times so I know for sure that it works.  Is the problem that you didn't manage to repro?

Your second paragraph makes sense, I suppose for png exports people wouldn't want to export any possible combination but just the currently shown one. 

Yes I think your proposed solution is acceptable.

Having the Together-All solution is the best and makes it very clear!

**Comment by NathanSweet** [comment]
The problem is it is not possible to "not specify a folder" when doing a PNG export. The reproduction steps are impossible.

**Comment by NathanSweet** [comment]
Many of these are in 3.7.20-beta!

**Comment by NathanSweet** [comment]
Move one bullet to a [new issue](https://github.com/EsotericSoftware/spine-editor/issues/369), EVERYTHING else is done in 3.7.24-beta!
