### ISSUE TITLE
Exporting GIF doesn't export the selected animation

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-editor#112]
Repro case in e-mail `Export Error` by aiat soltani. See forum thread http://esotericsoftware.com/forum/Wrong-animation-is-exported-6850?p=31635&hilit=export+animation+gif#p31635

Repro: select `Run` animation, export as GIF, `Idle` animation is exported.

**Comment by NathanSweet** [comment]
Sorry it's taken so long to get to this. Unfortunately the project link that was emailed no longer works.
