### ISSUE TITLE
Editor freezes for a long time when keying 300+ slots

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-editor#113]
See http://esotericsoftware.com/forum/No-response-when-editing-over-300-slots-7109. Was able to reproduce using the provide project file.

**Comment by aoxu** [comment]
Thanks for your engagement. Feel free to ask anything if you need.

**Comment by NathanSweet** [comment]
Fixed in 3.5.08-beta

**Comment by aoxu** [comment]
Thanks.
