### ISSUE TITLE
Some frames in GIF export have white background

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-editor#117]
See "GIF export issue" e-mail for repro case. I reproduced it locally by exporting at 25FPS, background white, transparency checked. All frames except frame 46 are transparent.

**Comment by NathanSweet** [comment]
It exported for me correctly, used Photoshop to verify each frame. Not much I can do without repro.

At 25 FPS "Biped Run" is 34 frames. You mentioned 46 frames, what animation did you repro with?

**Comment by NathanSweet** [comment]
Need repro (7 months!).

**Comment by NathanSweet** [comment]
3.7.20-beta (new GIF export)
