### ISSUE TITLE
Curve editor

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#118]

**Comment by KarlTwoMenAndADog** [comment]
DoublePlus Good

**Comment by djmisterjon** [comment]
hope see this soon, i never try in maya, but i pretty love this graph editor. If it can give some good idea.
https://greensock.com/docs/Easing

**Comment by djmisterjon** [comment]
add a visual basic concept
![image](https://user-images.githubusercontent.com/24865815/56874480-1d938300-6a08-11e9-8dec-2a11e9c238db.png)
![image](https://user-images.githubusercontent.com/24865815/56874567-b62a0300-6a08-11e9-9e0a-f6c883fbfce4.png)

**Comment by samanabo** [comment]
This looks great, however for an animator there are a few critical features here that would make this feature incredible.

It looks like from this mock up that you are able to customize the easing for a given key, however it would be far more valuable to be able to edit the easing, and the value.

It would also be great to change more than one key at a time. Being able to see the values of multiple keys over time, and adjust the easing and value will let animators achieve much better arcs, timing and spacing.

Maya has one of the best curve editors out there... if you are looking for any inspiration:
https://help.autodesk.com/cloudhelp/2018/ENU/Maya-Animation/images/GUID-2295C176-EE5A-4B2B-8EFB-23D51FAE786B.gif

**Comment by djmisterjon** [comment]
yes true, let see how they will made this, am curious because it very a lack support in spine2D.

**Comment by ivamorlor** [comment]
As a complete Spine lover this is the only feature I really miss in the software. We NEED that. I know some people that don't get Spine because of that. Even the temporary improvement of modifying X and Y curves independently would be a huge advance.

**Comment by NathanSweet** [comment]
We are making good progress and will have something to show soon.

**Comment by TextusGames** [comment]
> We are making good progress and will have something to show soon.

Finally, something is publicly happening. Hura.)

**Comment by NathanSweet** [comment]
Yeeees! We're working hard on it and have made a lot of progress. Even in its current basic state it's very useful for animating. It's going to be great when done! A number of important thing needs to change in the runtimes and we're working through those as fast as possible. There are related improvements such as separate X/Y timelines and rotation < -180 and > 180 that we're also laying the groundwork for at the same time. Lastly, we have changes that will enable us to have many more types of timeline. Until now things were not keyable at a granular level and there were some limitations about how many different kinds of timelines we can have.

**Comment by ivanpopelyshev** [comment]
>  There are related improvements such as separate X/Y timelines and rotation < -180 and > 180 that we're also laying the groundwork for at the same time.
Finally! And I'll have to port those breaking changes in pixi-spine and support for both v4 and v5 pixi. More branching, yay!

**Comment by NathanSweet** [comment]
@ivanpopelyshev We just pushed a commit:
https://github.com/EsotericSoftware/spine-runtimes/commit/93ca505864c1b96688b370a079474b4d205b980b
Please keep in mind that this is still early days, there may be more changes coming. I wouldn't suggest starting to port too early!

**Comment by arthas-ln2014** [comment]
Hey guys, the curve editor is so urgent for making animation
and also separating x/y/z keys,
when exactly you're going to release this feature ??
I really need curve editor for animating,
please tell me when you're going to release.
thanks

**Comment by NathanSweet** [comment]
@arthas-ln2014 It will be in the next version of Spine, which is 3.9. We don't have a fixed date to tell. We are working on it as hard as possible. It will be released in the 3.9-beta as soon as it is in a reasonably stable state, then improved for the duration of the beta.

**Comment by ivanpopelyshev** [comment]
@NathanSweet of course people will update **just before their production deadline** as soon as 3.9-beta hits ;)

**Comment by arthas-ln2014** [comment]
> 
> 
> @arthas-ln2014 It will be in the next version of Spine, which is 3.9. We don't have a fixed date to tell. We are working on it as hard as possible. It will be released in the 3.9-beta as soon as it is in a reasonably stable state, then improved for the duration of the beta.

Thanks so much! then we will wait for the beta version and I will try to send my feedback for you  for helping
Also we developed some tools for spine inside unity engine for having a better animation event system and previewing it inside editor without needing to see it in play mode, if you like we can share it with you.

**Comment by samanabo** [comment]
@NathanSweet well this is excellent news!

@arthas-ln2014 I would certainly be interesting in a tool like that.

**Comment by NathanSweet** [comment]
It's in 4.0.00-beta. Sneak peek: 
![](http://n4te.com/x/923-YmhN.png)
