### ISSUE TITLE
[beta 3.5] Copying a summary key incorrectly only copies one key if you selected a specific item first.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#123]
Repro:
![summary copy paste incorrect](https://cloud.githubusercontent.com/assets/1911082/19798066/7168651a-9d21-11e6-90b0-68338e6c02b7.gif)

Expected:
![summary copy paste correct gif](https://cloud.githubusercontent.com/assets/1911082/19798098/98b5b9e2-9d21-11e6-9c0d-bedc01fc019a.gif)

**Comment by NathanSweet** [comment]
This was interesting. Pasting uses the tree and viewport selection to determine the target of the paste, eg to paste keys to a different bone or slot. It is both invalid to copy from multiple objects and paste to a single one, and is also invalid to paste attachment keys to a different slot. Fixing that fixes this bug. 3.5.16-beta
