### ISSUE TITLE
Mesh manipulation improvements

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#126]
- [x] Weight painting.
- [x] Loop selection.
- [x] Soft selection for moving vertices.
- [x] Wireframes, being able to see edges when placing bones is helpful.

**Comment by NathanSweet** [comment]
The weights view will get a falloff distance and bias sliders, and a profile graph. Since you can have a mesh without weights and the Weights view is getting crowded, we'll have a Mesh Tools view or some other place for UI to control mesh selection and manipulation. Controls:
- direct selection (current functionality)
- soft selection: falloff distance/bias/profile, neighbors checkbox
- loop selection checkbox

@Shiu we'll need a few icons:
- [ ] "Display" icon for new section in mesh tree properties: ![](http://n4te.com/x/130-vqH1.png)
- [ ] "Direct" button
- [ ] "Soft" button

**Comment by Shiu** [comment]
"Display" Shows wireframe?

**Comment by NathanSweet** [comment]
@shiu It's too wide to fit in the Options row. So far every row has a label. Are you proposing to have no label under options / left of wireframe?

**Comment by Shiu** [comment]
Unless there are more Display options coming, I think it makes sense to put it under options.
![]http://www.fainted.dk/esoteric/45-BbZf.png

Options could still be vertical aligned top if you prefer.

**Comment by NathanSweet** [comment]
@Shiu a few more:
- [ ] icon-selectVerts
- [ ] icon-selectVerts-disabled
- [ ] icon-weightDirect
- [ ] icon-weightReplace
- [ ] icon-weightAdd
- [ ] icon-weightRemove
- [ ] icon-weightSmooth (or we can use icon-smooth)

**Comment by NathanSweet** [comment]
Soft selection is in `3.6.17-beta`:
![](http://n4te.com/x/1904-spine-soft-select-tr.gif)

**Comment by NathanSweet** [comment]
Punted to a later release: lasso selection (#178) and primitives (#179).
Also to be done later: rotate/scale vertices in edit mode (#60).
