### ISSUE TITLE
Copy & pasting bones does not work

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-editor#127]
Create new project, select root bone, ctrl + c, ctrl + v. Project is marked as modified, but no additional bones are added.

**Comment by NathanSweet** [comment]
Copy/paste on bones does [transform copy](http://esotericsoftware.com/spine-tools#Transform-copy). It's a little strange it thinks the project has been modified when the bone's own transform is applied to itself, leaving it in the same state, but it's not really a problem.

The orange duplicate button in the tree properties for a bone can be used to make a copy of that bone and its children.
