### ISSUE TITLE
Crazy Auto-Keying: Scroll over a text field during playback

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#128]
1. Enable Auto-key
2. Go to Animate Mode.
3. Play an animation.
4. Hover over one of the transform property text fields
5. Scroll up/down (mouse scroll wheel).
BUG: Crazy number of keys get added.

![gg](https://cloud.githubusercontent.com/assets/1911082/20001639/1927d7f4-a2b8-11e6-991f-43d0570e3234.gif)

**Comment by NathanSweet** [comment]
This is actually working OK, you are changing values and it autokeys properly. We should disable the scrolling while playback is active though.

**Comment by NathanSweet** [comment]
3.5.07-beta

**Comment by pharan** [comment]
Just making sure. Did this also handle the case where it's a mesh? If you scroll on those boxes and it's a mesh selected, it adds deform keys.

**Comment by NathanSweet** [comment]
Yep, all cases of scrolling in the boxes (and dragging up/down).
