### ISSUE TITLE
Flashing on resize on macOS

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-editor#129]
See http://esotericsoftware.com/forum/OSX-problems-7258

**Comment by NathanSweet** [comment]
Flashing is much reduced in 3.5.11-beta. Is it enough to consider this closed? I haven't been able to find why the flashing is red.

**Comment by badlogic** [comment]
Yes, it's pretty much perfect now. Viewport doesn't get resized in the same frame, so it's lagging a bit when resizing, but other than that it's perfect.

**Comment by NathanSweet** [comment]
Great! I've seen other apps, like Photoshop, also lag slightly when resizing, so I think it's probably ok.
