### ISSUE TITLE
Mouse clicks not processed or in wrong location on macOS Sierra

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-editor#131]
See http://esotericsoftware.com/forum/3-5-08-beta-Inability-to-click-on-Spine-after-dragged-to-7323, can repro on my local machine. Resizing of window fixes the issue.

**Comment by badlogic** [comment]
More Sierra issues http://esotericsoftware.com/forum/Right-mouse-clic-on-app-return-7320

**Comment by NathanSweet** [comment]
Hopefully fixed in 3.5.11-beta, can anyone confirm?

**Comment by badlogic** [comment]
Can confirm, both in single monitor and dual monitor setups.
