### ISSUE TITLE
Multi select for mesh properties

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#137]
http://esotericsoftware.com/forum/Configurable-hotkeys-are-here-1493?p=34558#p34558

**Comment by erikari** [comment]
I add also: Allow to bulk check "Select" and "Export" http://prntscr.com/g0fk6s

**Comment by erikari** [comment]
**+ 2 [here](http://esotericsoftware.com/forum/Questions-and-requests-9786)**
>When selecting multiple attachments (either in the same slots or in different ones), I can't tick boxes such as 'Export' on or off - I have to select them all, one by one, manually. 

and 

>I'd like to +1 both of the topics mentioned in this thread. The ability to select Multiple Meshes and edit their properties as well as the ability to view Multiple skins at one time in the editor.

**Comment by pharan** [comment]
https://github.com/EsotericSoftware/spine-editor/issues/368

**Comment by NathanSweet** [comment]
3.7.34-beta
