### ISSUE TITLE
Potential "Clean Up" issue.

### ISSUE THREAD

**Issue by Fraggle** [EsotericSoftware/spine-editor#141]
Hi,

I think there is an issue with the clean up tool from the 3.5.x 
It removes the attachment keys (wich image is used) if they match the setup pose but in the runtimes, the attachment is not reset to the setup pose.
From others discussions i understand that the runtimes are behaving correctly.
In that case, I would say that the clean up tool should not remove a attachement key, ever.

Thanks,

Seb

**Comment by NathanSweet** [comment]
In 3.5, attachments and bones which are keyed in animations should work the same way. When an animation will no longer be applied, it leaves the attachments or bones in their setup pose state. If you see something different, please check the behavior in Skeleton Viewer. If it doesn't match your runtime behavior, you can report a runtime bug. If it does match your runtime, then please provide a JSON file and any images we might need and explain what you expected to happen in SV, and what actually happened instead.

**Comment by Fraggle** [comment]
Hello,

The same behaviour is present in the latest Skeleton Viewer, the flash runtime and the c runtime.
Attached is an example to show you, the animations have been "cleaned up" by the new cleanup button.

Step to reproduce:
1 - run "getset" (no loop)
2 - when the animation is done, run "run3" animation (with or without loop, doesn't matter)
Notice the left hand of the hare, it's wrong, it's the same image as the last image from the "getset" animation, not the one from the setup (as it should be, we had a key there to set the attachment but it has been removed by "cleanup").

So either the runtimes are correct and the attachments should not reset to the setup pose and the "cleanup" should be fixed to leave the attachments keys that matches the setup at the edges of the animations OR the runtimes are wrong and they should be fixed.

Notice that it's the same runtime behaviour that confused me before and you didn't think it was a bug then. https://github.com/EsotericSoftware/spine-runtimes/issues/789

Thanks,

Sebastien

[hare.zip](https://github.com/EsotericSoftware/spine-editor/files/651483/hare.zip)

**Comment by Fraggle** [comment]
Hello,

I'm sorry to ask, but do you have any new feedback regarding this?

Thanks,

Seb

**Comment by NathanSweet** [comment]
I'm so sorry this issue got missed and so much time has passed! The latest Skeleton Viewer (and therefore AnimationState) in the master branch appears to no longer have this problem. As soon as I switch from `getset` to `run3`, the hand attachments are changed to the setup pose (closed hands).

**Comment by erikari** [comment]
I think this might be related to this issue: http://esotericsoftware.com/forum/Mixing-to-animation-with-starting-as-setup-with-no-keys-11339
(read the thread for a good description of the problem)

I confirm the first frame gets removed if it is the same.

**Comment by Abuki** [comment]
I read the comments above, and it looks like a regression — both in the editor and runtime. The comments are talking about the same issue I have in 3.7

**Comment by NathanSweet** [comment]
We have fixed the problem in 3.7 in this commit:
https://github.com/EsotericSoftware/spine-runtimes/commit/c7d71a8eb1fcc64ec53b1667f9cd13ca8e9f1f96

Please follow this issue for porting of the fix to all runtimes:
https://github.com/EsotericSoftware/spine-runtimes/issues/1274

There are some cases where you need a key that animation cleanup will remove. We might consider a way to lock keys so they won't be cleaned. Eg, the above behavior works on the first track that keys something, if higher tracks key the same property and don't have a key at frame 0, they do not affect the lower tracks until the first key.
