### ISSUE TITLE
[3.6 Beta] Keys seem to be losing their graph settings.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#142]
Keys seem to be losing their graph settings.

diff:
![screen shot 2016-12-18 at 8 15 58 pm](https://cloud.githubusercontent.com/assets/1911082/21305197/25549876-c605-11e6-9c83-3415c5437e04.png)

Forum topic:
http://esotericsoftware.com/forum/Did-something-change-regarding-curve-JSON-exports-7628
The changes seem to be saved in the project, so it's not just an export problem as the topic title suggests.

**Comment by Xelnath** [comment]
For what it's worth, I am a sloppy tester. I'll pass along the .spine files if desired.

**Comment by NathanSweet** [comment]
Are there repro steps for this issue? Issues should stay in Unsorted column on Waffle until they are complete enough to be worked on.

I checked a version of Xelnath's project he emailed for other reasons and 3.6.19-beta seems to export curves OK.

**Comment by Xelnath** [comment]
This was so long ago, I haven't seen it again since the 3.6.11 or so beta. I think it's resolved.
