### ISSUE TITLE
Easier way of binding many bones for weights

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#144]
http://esotericsoftware.com/forum/Feature-request-if-not-already-implemented-7637

**Comment by Abelius1** [comment]
I'd say a good and simple way would be Shift + Click on the tree.

And for bonus points, a mouse dragging selection box in the model view would be also great. But a key would be perfectly enough by me. :-)

**Comment by NathanSweet** [comment]
Can now select any number of bones, click `Bind` on the `Weights` view, then choose a mesh, bounding box, path, or clipping attachment.

3.6.31-beta
