### ISSUE TITLE
[3.5] Using the path constraint position handle in the viewport doesn't update the properties box.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#146]
![propbox](https://cloud.githubusercontent.com/assets/1911082/21560763/bcdefbfe-ce9e-11e6-8eae-df4dbc1791b6.gif)

Using the Path Constraint position handle in the viewport doesn't update the properties box position value, even after you've released the mouse button.

It updates if you deselect and reselect the Path Constraint.

**Comment by NathanSweet** [comment]
3.6.13-beta
