### ISSUE TITLE
Skins with different proportions

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#147]
Sometimes, different character variations call for differently-proportioned skeletons. (ie, tall skinny character, wide ogre-like character).
If animations are mostly bone rotations and slight movements, they would be compatible despite different proportions.

It would be useful and save time if there was a way for the user to define a set of different setup pose values to be compatible with different skins, and preview them with animations.

**Comment by NathanSweet** [comment]
This can be done in 3.8 using skin bones and constraints. The 3.8 features release video will have a link to the mix-and-match project which shows this:
![](http://esotericsoftware.com/img/blog/3.8-released/tall-short.gif)
