### ISSUE TITLE
Setup Mode: "Mirror" a chain of bones and images.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#150]
Use case 1:
- Artist is making a robot character facing the camera.
- The left and right arms are intricate, but are just duplicates of each other.
- The artist can set up and rig one arm with a chain of bones.
- Then all they need to do is just duplicate it and mirror it.

Have a button somewhere (seems like it's related to the compensate tools but I don't think the button should necessarily be there).
When you click the button (for mirroring/Flip X for example):
It applies no scale to bones, it just changes the rotations so everything pointing right points left and vice versa. The attachments are flipped accordingly with negative scale or flipped vertex positions.

**Comment by pharan** [comment]
Forum user case (spider legs): http://esotericsoftware.com/forum/Duplication-of-linked-bones-with-and-without-linked-images-7829

**Comment by pharan** [comment]
Erikari's use case: http://esotericsoftware.com/forum/Duplication-of-linked-bones-with-and-without-linked-images-7829?p=36669#p36669

**Comment by NathanSweet** [comment]
4.2.59-beta can duplicate constraints and all their bones.
