### ISSUE TITLE
Have a toast for CTRL+C CTRL+V operation on bones?

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#152]
1. Select a bone.
2. `CTRL`+`C`
3. `CTRL`+`V`

Some people may assume it duplicates the bone. It actually just copies the transform values of one bone to another.

So maybe we should have a toast that appears that notifies the user what just happened.

http://esotericsoftware.com/forum/Duplication-of-linked-bones-with-and-without-linked-images-7829

Suggestions:
"Bone transform values applied from clipboard."
"Bone transform values pasted."
"Bone transform values from bone XXXX copied."

**Comment by NathanSweet** [comment]
We now toast all copy/paste actions (bones, vertices, keys, etc).
