### ISSUE TITLE
Pasting an IK key on a different bone causes nonsense duplicate dopesheet timeline.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#154]
![m](https://cloud.githubusercontent.com/assets/1911082/22775491/eb32871a-eee6-11e6-89d6-36a9526025d8.gif)

Steps:
1. Create a skeleton. Add two bones in a chain (thigh, shin), and another child of the root bone (ik target).
2. Create an IK Constraint, constraining thigh and shin, and targeting ik target.
3. Go to Animate Mode.
4. Select the IK Constraint in the tree, and key it by clicking on the key icon next to it. (at this point, you will have a single IK key)
5. Deselect everything.
6. Select the IK key in the dopesheet.
7. Copy it (CTRL+C or the Copy button)
8. Move the dopesheet cursor to frame 10.
9. Select the root bone.
10. Paste (CTRL+V or the Paste button)
11. BUG: You'll have a single IK key on frame 10.
12. BUG: Deselect everything. Now you see that you have two separate dopesheet rows for the same IK Constraint. Each has one IK Key.

**Comment by pharan** [comment]
Ah, forgot to mention.  Spine 3.5.46

**Comment by NathanSweet** [comment]
Great find, fixed in 3.5.48!
