### ISSUE TITLE
Copying and pasting a color key between skeletons crashes the editor.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#155]
http://esotericsoftware.com/forum/Spine-Crash-during-paste-7882

1. Setup Mode. Have two skeletons in one project (A and B). Each has their own slot under the root bone. No attachments needed.
2. Animate Mode
3. Key the color in Skeleton A's slot. (can be the default white)
4. Select the newly created key in the dopesheet.
5. Copy.
6. Select the slot in Skeleton B in the tree.
7. Paste. (CRASH)

**Comment by NathanSweet** [comment]
Good bug, thanks for the steps! Fixed in 3.5.48.
