### ISSUE TITLE
Multi-selecting bones in certain cases causes random rotations.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#156]
http://esotericsoftware.com/forum/Painful-Bug-7896
Forum user helpfully posted a video.

Will take a closer look at it for specific conditions.

It looks like it might be related to that weird auto-key bug too.

**Comment by NathanSweet** [comment]
It's a crazy bug, but we shouldn't create issues without repro steps, since without that we don't have any actionable tasks. I can't repro and I've asked for the project file, can reopen if we can repro.
