### ISSUE TITLE
Persisting play state can be confusing if animation has zero duration.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#157]
http://esotericsoftware.com/forum/Mesh-not-selectable-during-animation-7904

Steps:
1. Have a skeleton with a mesh. You can use Raptor.
2. Make a new animation with no keys.
3. Switch to Animate Mode.
4. Enable playback looping (or CTRL+R)
5. Press play (or CTRL+D)
6. PROBLEM: It looks as if nothing is happening. But you try to select or modify anything, and you can't.
7. Switch to Setup Mode.
8. Switch to Animate Mode.
9. PROBLEM: It still looks like nothing is happening. But the animation is actually still looping.

Expected:
1. Probably don't let the playback state persist if the animation duration is 0.
2. Have some kind of indicator during playback that it's looping a zero-duration animation.

**Comment by NathanSweet** [comment]
3.6.13-beta
Also handled playing backward without repeat on, reaching frame 0 stops playback.
