### ISSUE TITLE
Extend L hotkey functionality

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#162]
http://esotericsoftware.com/forum/Meshkey-shotcut-7945

Currently:
Pressing `L` with a bone selected keys the currently active transformation tool's transform property.
Pressing `L` with a slot selected does nothing.
Pressing `L` with a mesh selected does nothing.

Possibly:
Pressing `L` keys the mesh deform when a mesh is selected.
Pressing `L` keys a slot attachment when a slot is selected.

... but what about slot color? (Hwadock requested)

Summoning @Shiu

**Comment by NathanSweet** [comment]
By default, `L` is `Key Active` and keys the transform of the active tool (rotation, translation, scale, or shear). Currently it also keys the deform of a selected mesh, path, bounding box, or clipping attachment. I think `Key Active` should key only based on the viewport selection, which means it should not key slots.

It seems you had in mind `Key Selected`, which is `ctrl+L` by default. Currently that keys based on the viewport selection:

1) If it is a bone, it keys rotate, translate, and scale (but not shear).
2) If it is a mesh, path, bounding box, or clipping attachment, it keys the deform.

Shear should probably be added to 1. I wonder if keying all 4 transform values is really that useful? I guess it's OK with animation `Clean Up`.

`Key Selected` could be expanded to act on the selection of either the tree or viewport, whichever was last clicked, and to work on all keyable items (slots, constraints, etc).

**Comment by NathanSweet** [comment]
3.8.10-beta

Keys events, draw order, constraints. For path constraints mix, position, and spacing are keyed. For slots the slot color is keyed. For an attachment selected in the tree, the slot attachment is keyed. For mesh, path, bounding box, or clipping attachment selected in the viewport, the deform is keyed. For bones shear is keyed along with rotation, translation, scale.
