### ISSUE TITLE
[3.6.06-beta] Duplicating a slot doesn't duplicate its Tint Black state.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#163]
1. Have a slot.
2. Check "Tint Black"
3. Duplicate that slot using the Duplicate button under Tree View
4. BUG: The duplicated slot's Tint Black checkbox is not checked.
5. ???: You can still paste TwoColor dopesheet timeline keys from one with Tint Black checked to one with it unchecked. The animation appropriately plays back without the black tint. The pasted values appropriately show that the keys are not different if only the black tint differed.

**Comment by NathanSweet** [comment]
3.6.13-beta
