### ISSUE TITLE
Update example projects

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#164]
- [x] Spineboy-ess
- [x] Spineboy-pro
- [x] Alien-ess
- [x] Alien-pro
- [x] Raptor-pro
- [x] Tank-pro
- [x] Stretchyman-pro
- [x] Powerup-ess
- [x] Powerup-pro

**Comment by Shiu** [comment]
All updates example projects will be finished this week (Week 9)

**Comment by Shiu** [comment]
- [ ] Tank clipping mask

**Comment by Shiu** [comment]
Please provide input to the 3.6 example projects if any.

**Comment by NathanSweet** [comment]
- [ ] For every project, we should center the viewport and set zoom to an appropriately level so when the project is opened it looks reasonable. The default window size is pretty small and some projects may not look when first opened. The most important project is spineboy, since it is opened on the first run. The Spine window is 933 x 700 by default, with the tree on the side. Smork your `prefs.json` to see the exact size, but not a HDPI display has a UI scale of 200% (change to 100% and restart).

- [ ] Similarly we should collapse the tree nodes (click minus with nothing seleted, then expand the skeleton(s)).

- [ ] Raptor, inside of the mouth inside doesn't stretch when the mouth opens.

**Comment by Shiu** [comment]
- [ ] lowercase and dash for all naming

**Comment by badlogic** [comment]
[ ] Spineboy-ess death animation seems to be two animations, also Spineboy moves downwards in second half of animation
[ ] Alien-ess, hit anim starts out strangely skewed/scaled regarding head 
[ ] Alien-ess and Alien-pro have both unused images. I guess they are used in the other version respectively?
[ ] Raptor-pro, bone colors are inconsistent, e.g. in other skeletons, bones are nicely colored by body part, in raptor all of Spineboy is white, raptor is segmented by body part mostly.
[ ] Raptor-pro, unused images
[ ] There's a tank.spine and tank-pro.spine. Should tank.spine be removed or renamed to tank-ess.spine?
[ ] Tank-pro, drive has a very long 20 frames delay in beginning where nothing happens. Not sure if we should get rid of that?

**Comment by NathanSweet** [comment]
- [ ] In spineboy-ess, root bone has 2 keys on frame 67 that should be deleted. Pro is OK.

**Comment by NathanSweet** [comment]
- [ ] In `tank-pro`, clipping deforms better when barrel is raised by changing this vertex weight: http://n4te.com/x/2117-khRt.png

**Comment by Shiu** [comment]
- [ ] annotations where required

**Comment by Shiu** [comment]
- [ ] dragon example - change ODI Entertainment to www.thiagobrayner.com
- [ ] remove dust from Spineboy
- [ ] better shoot effect for Spineboy

**Comment by NathanSweet** [comment]
As discussed on Slack, I don't think we need to remove the dust. Example projects don't need to be directly usable in a game.

**Comment by NathanSweet** [comment]
I finally went over all the examples projects:

alien
- [ ] -pro has missing images (looks likes attachments need dashes, eg `front_lower_arm`).
- [ ] burst01 image doesn't seem to match head or burst02 images during the death animation. The head shape jumps a little but especially the nose changes (eg frame 13 -> 14).

dragon
- [ ] Missing images.
- [ ] I guess we should name it -ess to follow the other project naming.
- [ ] template image is not used, we should just delete it.

hero
- [ ] -ess, walk, frame 5, the legs look odd: http://n4te.com/x/2208-oO2t.png He has no butt, so the legs should probably not move forward until hidden by the hand. -pro has the same issue, but less.
- [ ] -ess should not have constraints (or bones that used to be constrained, eg LookTarget).
- [ ] Naming conventions don't match other example projects.

powerup
- [ ] Naming (tokenRoot).
http://n4te.com/x/2209-G9es.png

raptor
- [ ] raptor-mouth-inside still doesn't stretch when the mouth opens. Currently roar keys it to stretch, but breaks at frame 20. http://n4te.com/x/2209-G9es.png Could use a 4 vertex mesh with weights like: http://n4te.com/x/2210-XrYH.jpg Then it doesn't need its own bone.
- [ ] jump, should we have a little dust when lifting off? Around frame 12.
- [ ] jump, I wonder if the raptor neck could stretch a bit during lift off? Similar to how it stretches when landing.
- [ ] jump, I like the raptor head rotation lifting off, but afterward it levels and stays level for the rest of the animation. I think the raptor would start to look down at (or just after) the apex. The translation at the end is good, but the head is level. The rotation could anticipate the translation.
- [ ] jump, knees pop between frames 11 and 12 (hold shift).
- [ ] jump, it feels like the raptor rear arms lift too soon between frames 12 and 16. They could hold frame 12 until 16 to give a sense of flying upward.
- [ ] empty animation can be deleted (AnimationState supports this better now).

speedy
- [ ] Should rename to -ess.
- [ ] I'm not sure users will gain anything by seeing the 3 run animations. What do we want to show with this project? It has some images changes. It has a Rayman style, should we do some Rayman-style animations?

spineboy
- [ ] Can delete the test animation.
- [ ] -ess, walk, front foot lifts from frames 3 to 7.
- [ ] -pro, portal-exit, can we rename to just portal? 
- [ ] -pro, portal-exit, when he lands his feet stick instantly, like he landed on a fly trap. What if he slid slightly for a couple frames starting at frame 42?
- [ ] -ess, select all animations, Clean Up, 240 keys are deleted. I didn't try this on every project, but I guess there are lots of savings possible. Is it safe to Clean Up all projects? I can write a tool to do this (I need to process the files anyway to remove stored paths).
- [ ] I wonder if the hoverboard is better as a separate project? It would be easier for people to find.
- [ ] -pro (maybe -ess too), walk feels somehow stiff/awkward, like he has a stick up his butt. His back leg knee joint pops when the leg is extended both on the front and back of the step. It also may be too fast?
- [ ] It would make a good track demo (eg for the Preview view) if we could play shoot during idle, walk, and run. To do that we should add an "aim" bone and use 1 bone IK on the rear upper arm. The IK mix would be zero except for the shoot animation. The run animation might need adjustment to look good, as he ducks his head quite a bit.

spineboy-old
- [ ] Can delete headPop.

spinosaurus
- [ ] To make this a little more realistic, like it might be used in a game, we could have 4 animations: intro, play, settings, quit. A game would play intro, then play and change to settings or quit when a player presses up/down. It could also have bounding boxes on the menu items for detecting clicks.
- [ ] Should rename to -ess.

stretchyman
- [ ] Should rename to -pro.
- [ ] The torso and arms could be rigged like the legs (similar to the demo project). This would show off constraint order.
- [ ] The head is a mesh but looks like it could be a region.
- [ ] Maybe add another animation? Wacky wavy inflatable arm flailing stretchyman?

tank
- [ ] Naming conventions (caps: tankBottom, tankBottom-shadow, tankTop, smokePuff*, smokeGlow, cannonConnector).

vine
- [ ] Should rename the animation to "grow" (or something).

**Comment by NathanSweet** [comment]
I have a tool for doing Clean Up on all animations, so don't bother doing it manually. It also strips recent paths from the project files, so users don't see our paths and get confused.

**Comment by NathanSweet** [comment]
- [ ] Tank drive and shoot have different starting poses (machine gun).

**Comment by Shiu** [comment]
I have made changes to hero-pro, but I think the hero-ess project should be removed. All animations in hero-ess would need to be redone if constraints were removed.  The hero project was never made for ess, only pro since it uses constraints for the Unity project Mitch made. We just had a mesh version.

**Comment by Shiu** [comment]
- [ ] Finalize gun muzzle images for Spineboy

Other remaining issues will be done after 3.6 release

**Comment by Shiu** [comment]
- [ ] Spineboy-pro: animate mouth in `run` animation
