### ISSUE TITLE
[3.6.?? beta] Are color timeline key values intact?

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#168]
I saved a duplicate/copy of spineboy to fiddle around with in various versions of 3.6 over the past several weeks. And the other day, I checked the "shoot" animation (as far as I can recall, I never edited it during that span of time).

All the color keys seemed to have the value of "0000803E" regardless of what they originally were ("ffffffff" and "ffffff00")

**Comment by NathanSweet** [comment]
That's is super weird. Do we have repro steps? If we do, please re-open the issue.
