### ISSUE TITLE
Allow multiple skins to be active at once

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#17]
For preview of combining skins at runtime:
http://www.esotericsoftware.com/forum/viewtopic.php?f=3&t=618

For adding an attachment to all skins to save time:
http://www.esotericsoftware.com/forum/viewtopic.php?f=3&t=1885
http://esotericsoftware.com/forum/viewtopic.php?f=11&t=2803

**Comment by pharan** [comment]
Why is this a bug?

**Comment by erikari** [comment]
+1! http://esotericsoftware.com/forum/Questions-and-requests-9786

**Comment by erikari** [comment]
another +1 from the same thread posted above by a different user!

**Comment by erikari** [comment]
Another +1 by Adenscott on same thread!

**Comment by djmisterjon** [comment]
+1 
https://github.com/pixijs/pixi-spine/issues/239

**Comment by supersaiyansubtlety** [comment]
+1 from me

**Comment by erikari** [comment]
+ 1 here: http://esotericsoftware.com/forum/Multiple-skins-in-editor-ETA-10749

**Comment by NathanSweet** [comment]
3.7.32-beta has a `Skins` view to preview combining skins. Doesn't yet have a way to duplicate an attachment for each skin.

**Comment by NathanSweet** [comment]
We'll open a new issue for duplicating an attachment to each skin once we've completed internal discussion on how best to handle that.
