### ISSUE TITLE
English subtitles for documentation videos

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#172]
Can list videos here, check off progress.

**Comment by pharan** [comment]
Can anyone add subtitles to it or only the creator can?

**Comment by Shiu** [comment]
- [x] Getting Started
- [ ] Basic Concepts
- [ ] Images
- [ ] Tools
- [ ] Tools Continued
- [ ] Key Frames (1/2)
- [ ] Key Frames (2/2)
- [ ] Animating 
- [ ] Animating Pose to Pose
- [ ] Attachments & Meshes (1/2)
- [ ] Attachments & Meshes (2/2)
- [ ] Bounding Boxes &  Paths 
- [ x] Events
- [ ] Constraints
- [ ] Inverse Kinematics
- [ ] Transform Constraints

**Comment by Shiu** [comment]
Tools videos should be redone before subtitled. Missing skew and they are too long (too much talk)
