### ISSUE TITLE
Shear text input breaks if typing in negative numbers

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-editor#173]
Enter `-10`, get `0-1``

![https://libgdx.badlogicgames.com/uploads/Screen%20Shot%202017-04-10%20at%209.47.29%20AM-nJosmHg7Tj.png](https://libgdx.badlogicgames.com/uploads/Screen%20Shot%202017-04-10%20at%209.47.29%20AM-nJosmHg7Tj.png)

See also http://esotericsoftware.com/forum/Shear-input-box-bug-8251

**Comment by NathanSweet** [comment]
3.7.43-beta
