### ISSUE TITLE
Wacom modifier ExpressKeys have strange behavior in OSX

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#174]
http://esotericsoftware.com/forum/Wacom-osx-custom-keybinding-3822

By default in **Mac OS X**, the bottom set of **Wacom Tablet ExpressKeys** (buttons on the side of the tablet) are bound to "modifiers" `Shift`, `Cmd` and `Option` (and Pan/Scroll).

These correspond to common Photoshop modifier keys for drawing straight lines, moving layer contents, color picking and panning.

Using these express keys in programs like OSX Finder, and Photoshop, these work fine and as expected.

In Spine, they have strange behavior:
- Pressing these buttons in Edit Mode seems to do nothing. Holding the `Cmd` ExpressKey does not allow you to multi-select bones.
- Using `Cmd`, `Shift` and `Option` ExpressKeys in Animate Mode seems to be equivalent to pressing the "Play Backward" button.
- Holding down the `Pan/Scroll` ExpressKey causes Spine's `Zoom Drag` function (default `U`) to be used. But using that key on a text field does not type `U`.
- It does not seem to be raw input. eg. Changing the keybindings of the ExpressKeys so Pan/Scroll is on a different button causes the Zoom Drag on that button. Same with `Shift` and `Cmd`.
- Remapping an ExpressKey to `Spacebar` and using it causes it to deselect. (expected)
- Having a Wacom On-Screen control that does `Shift` also seems to be the equivalent of pressing the "Play Backward" button. Binding it to `Shift-Spacebar` will play backward.
- When editing any text box (Rename dialog or String field on events):
  - Holding `Shift` express key, then typing a letter causes that letter to not come out, but the subsequent letters (while still holding `Shift` ExpressKey) come out uppercase.
  - `Cmd` express key, then using `C` or `V` does not perform a copy or paste operation.

Confirmed on OSX and a Cintiq24HD and an Intuos 5.

Intuos/Cintiq on Windows 10 does not seem to have this problem.

**Comment by NathanSweet** [comment]
@shiu Where is Wacom? How does it get lost?!

**Comment by badlogic** [comment]
The JGLFW backend appears to report all modifier keys as `A`, including `CMD`, `SHIFT`, `OPTION`. Remapping does not fix anything.

The LWJGL2 backend doesn't know the modifier keys at all and reports `unknown modifier key: 0`.

I'll dig into the JGLFW backend and see if I can figure out why modifier keys aren't send properly.

**Comment by badlogic** [comment]
Fixed in JGLFW GLFW 3.0 fork.

**Comment by pharan** [comment]
wtf is jglfw glfw?

**Comment by badlogic** [comment]
Language. Plus, you wouldn't understand.

**Comment by pharan** [comment]
Sorry, that wasn't me. The cat was walking on the keyboard.
