### ISSUE TITLE
Photoshop script: store absolute images path

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#182]
When choosing the `New Project` option, in the `Import Data` dialog box, it should offer to immediately save the new project as a file (or set the skeleton image path as an absolute path) so the user doesn't run into problems like:
- all images are shown as missing images
- user needs to navigate to the correct folder to save the project (so Spine can find the images) or
- user needs to navigate to the correct folder to set the image path so Spine knows where to find them

http://esotericsoftware.com/forum/pngToJson-Photoshop-completely-broken-8515

(I think this will commonly be one of the first experiences of a new Spine user. It's important that clear direction is provided and things are taken care of seamlessly where possible. But this also greatly benefits experienced users who need to work on a lot of skeletons.)

**Comment by NathanSweet** [comment]
Forcing the project to be saved is a bit odd. We should use absolute paths in the JSON. This will ensure the images are shown after import. Later, when the project is saved, the paths will be converted to relative, if possible.

**Comment by pharan** [comment]
Sounds good. Whatever makes the process feel less janky.

**Comment by NathanSweet** [comment]
Done! The script now writes an absolute path for the images folder, allow images to be found in Spine even before the Spine project is saved.

https://github.com/EsotericSoftware/spine-scripts/commit/1075d8fbe4f48336b1e657073a33158084e29eb6
