### ISSUE TITLE
PS Script crashes in CC 2014 and CC 2017.1.1

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-editor#184]
See issue description and temporary workaround here http://esotericsoftware.com/forum/export-script-crashes-Photoshop-with-workaround-8635

**Comment by Shiu** [comment]
I'm unable to reproduce this. Have tried with a PSD saved locally as well as on a network drive.

**Comment by NathanSweet** [comment]
PS script has been heavily revised, no one else has been reporting crashes. Will close unless we can get more information about the OP's problem.
