### ISSUE TITLE
[3.6.20 beta] Messed up images when moving certain bone hierarchies

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#185]
Repro steps:
1. Open goblins project
2. New Skeleton
3. New Skin
4. Copy the images path to the new skeleton so it can find the images.
5. Move the "left shoulder" bone from the old skeleton to the root of the new skeleton.

BUG:
AT THIS POINT, the left shoulder will show up correctly in the new skeleton. But the original skeleton's slots will behave weirdly. The neck shows up as a fist. The left foot looks like an upper arm.
Selecting and hovering over the original slots for the neck and the foot shows that its skin placeholders pointing to the correct paths/images. But they render incorrectly when not selected/hovered.

**Comment by NathanSweet** [comment]
3.6.21-beta
