### ISSUE TITLE
[3.6.20 beta] Imaginary bone selected when moving bones across skeletons.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#186]
Repro steps:

1. New project
2. New Skeleton (in addition to the original skeleton named "skeleton")
3. Make a new bone in the original skeleton. (`N`, then drag new bone in viewport)
4. Switch to move/translate tool. `V`
5. Drag that new bone from the original skeleton to the second skeleton.
(At this point, it will look like the bone you moved is selected in the tree.)
6. Drag around the viewport to attempt to translate the bone. It doesn't move. It seems to be controlling some kind of imaginary bone. You need to deselect and select the bone again to be able to manipulate it.

**Comment by NathanSweet** [comment]
3.6.21-beta
