### ISSUE TITLE
[3.6.21 beta] Dopesheet Offset sometimes smorks the last key value

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#189]
https://www.dropbox.com/s/zhgrv7kelrt0o22/offsetbug-debug-3-6-21.spine?dl=0
Steps:
(1) Enable the Dopesheet Offset toggle.
(2) Box select all the keys in the dopesheet.
(3) Drag the keys to the right.

![repro](https://cloud.githubusercontent.com/assets/1911082/26544884/2840533a-4496-11e7-935e-169e12ccd6b0.gif)

Observations:
- The bug is immediately seen as the line between the last and 2nd to the last keys disappearing, on some but not all dopesheet rows.
- The last key seems to take the value of the 2nd to the last key, instead of the calculated/interpolated value.
- The bug is reproducible by using the Dopesheet Shift toggle instead of box-selecting.
- The bug does not seem to happen when offsetting one dopesheet row at a time.
- The bug doesn't exist in the latest Spine 3.5

**Comment by NathanSweet** [comment]
3.6.22-beta
