### ISSUE TITLE
[Editor UI Idea] Add "shortcut buttons" for common pair-views.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#192]
Example:
Add `Graph` and `Animations` buttons to the Dopesheet to open Graphs view or Animations view right beside it.
The dopesheet used to have the Graph button.

This is so that:
- graphs view is discoverable like it was in Spine 2.x
- related views can open in a recommended place (like Graphs beside the dopesheet).
- it's easier to temporarily open and immediately close these views from a working on a task where the need arises

**Comment by NathanSweet** [comment]
Added `Graph` in 3.6.25-beta. I'm not sure about `Animations` in the dopesheet, it is already packed with buttons.

Note all `alt + ?` hotkeys toggle a view. Usually it's the first letter, eg `alt + A` for animations, `alt + G` for graph. When the letter is taken, it's the next letter eg `alt + H` for ghosting.
