### ISSUE TITLE
[Editor UI Idea] "Line grid" and "Dot grid" background options.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#194]
In addition to the "classic" checkerboard background, add options for "line grid" and "dot grid".

![bg-concepts-linegrid1](https://user-images.githubusercontent.com/1911082/26943708-137a8256-4cb9-11e7-8f29-757f471c6a40.png)
![bg-concepts-dotgrid3](https://user-images.githubusercontent.com/1911082/26943709-13b3c16a-4cb9-11e7-9c22-87ab85fa984e.png)
![bg-concepts-dotgrid4](https://user-images.githubusercontent.com/1911082/26943710-13b810bc-4cb9-11e7-8775-b3d2f90b673b.png)

I like them because they're a nice middle-ground between wanting less visual noise, and still wanting a grid.

**Comment by Shiu** [comment]
I like that idea. Additionally it would be great to be able to place vertical and horizontal guide lines similar to PS.

Note how the horizontal line is used in this image
![](https://s-media-cache-ak0.pinimg.com/600x315/35/e7/db/35e7dba96d255ee9367ba901e2f874d6.jpg)

**Comment by pharan** [comment]
@Shiu I think that would be this: https://github.com/EsotericSoftware/spine-editor/issues/145

**Comment by NathanSweet** [comment]
3.7.62-beta
