### ISSUE TITLE
More bone icons

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#196]
http://esotericsoftware.com/forum/it-would-be-nice-if-6347?p=35965#p35965

Could make it in 3.6 if done soonish.

**Comment by Shiu** [comment]
Need to create 16x16 icons. Viewport icons are done.
16x16
- [ ] Warning
- [ ] Asterisk
- [ ] Star
- [ ] Rotate
- [ ] ArrowsB
- [ ] Spiral (And better viewport Spiral)
- [ ] Diamond
