### ISSUE TITLE
[3.6.24] The Show FPS checkbox does nothing

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#198]
Every time I switch between versions, the prefs get smorked so I haven't bothered re-enabling it.

But I tried enabling "Show FPS" just now.
It seems like it's not working. I don't see the FPS counter anywhere, even in Animate Mode with an animation playing.

**Comment by NathanSweet** [comment]
It appears left of the views 1 second after playback begins:
![](http://n4te.com/x/2227-97Oh.png)
I see it in 3.6.24-beta, reopen if it's really broken.

**Comment by pharan** [comment]
It's more like 3 seconds on mine.

**Comment by NathanSweet** [comment]
Oops, it's 2 seconds. Spine renders only as needed until playback starts, so the FPS can't be accurate until some time has passed and we have collected enough samples.

**Comment by pharan** [comment]
I would show it at half-opacity or something for the first seconds, just so we know it's working immediately but "might not be accurate". 2 seconds seems too long for this sort of feedback.

**Comment by NathanSweet** [comment]
We can show something so it's clearly active, but not a number. It's not just inaccurate, it's completely wrong. It would show eg "12".

**Comment by NathanSweet** [comment]
Now show "-- fps".
