### ISSUE TITLE
Group folders for animations, slots

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#20]
Makes it easier to organize/find animations. Makes controlling draw order easier.

http://esotericsoftware.com/forum/viewtopic.php?f=11&t=3520

**Comment by erikari** [comment]
+1 for this user, who is also suggesting to at least be able to color-code the names of the animations to retrieve them easily:  http://esotericsoftware.com/forum/Feature-Request-more-ways-to-sort-animations-9863

**Comment by erikari** [comment]
and another +1 from here: http://esotericsoftware.com/forum/Feature-Request-Animation-Organization-11200?p=50325#p50325

**Comment by NathanSweet** [comment]
It's happening!
![](http://n4te.com/x/6474-FMrn.png)

**Comment by NathanSweet** [comment]
We have it for animations, skins, and events in 3.8.10-beta, but not for slots and constraints. Slots are already a sort of folder for attachments and I'm not sure it would be great to have folders of slots under the bones. Constraints and slots in the draw order are ordered and while folders could make reordering groups of them more easily, folders would also interfere with the order.

**Comment by djmisterjon** [comment]
it would be nice to be able to assign a colors to the folders. For most people, the colors helps the eye sweep a lot .
