### ISSUE TITLE
[3.6.30 beta Trial] Offset functionality is broken in trial version.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#203]
http://esotericsoftware.com/forum/Offset-error-not-sure-whats-the-cause-8794

![mm](https://user-images.githubusercontent.com/1911082/27231371-ffca18e8-52e4-11e7-9bc7-dda21c1f84b6.gif)

Seems to work fine in Spine Pro 3.6.30 beta

**Comment by NathanSweet** [comment]
3.6.31-beta
