### ISSUE TITLE
Prompt for user decision when mesh images are resized

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#205]
Currently Spine assumes 1) when a mesh image is larger, whitespace has been added to the edges, and 2) when a mesh image is smaller, the image has been scaled down. We should prompt so the user can decide how they want their mesh UVs adjusted when the image size changes.

http://esotericsoftware.com/forum/Mesh-changing-to-a-larger-images-messes-scale-8812

**Comment by erikari** [comment]
+1 http://esotericsoftware.com/forum/Issue-to-edit-the-scale-s-mesh-10788?p=48609#p48609

**Comment by NathanSweet** [comment]
3.7.61-beta
