### ISSUE TITLE
Keying Weights

### ISSUE THREAD

**Issue by EliteCAT1** [EsotericSoftware/spine-editor#209]
Hiya,

Are there any plans to support keying weights? It would be very helpful in simulating Blend Shapes or Morph Targets.

**Comment by NathanSweet** [comment]
No, not in the near term. It seems a bit tricky to have multiple sets of weights for different scenarios. We've considered implementing blend shapes but have tabled it for now. The computations are pretty expensive (at least compared to weighted meshes).
