### ISSUE TITLE
Random bone influence in meshes

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#211]
See the gif:
http://esotericsoftware.com/forum/Meshes-direct-mode-adds-random-bone-influences-8861

And also the thread here: http://esotericsoftware.com/forum/Multiple-vertices-weighting-9138

**Comment by NathanSweet** [comment]
@erikari Can you provide a repro case? The GIFs are sufficient to reproduce the problem on, for example, the raptor project.

**Comment by erikari** [comment]
@NathanSweet sure,
1. open raptor project
2. click on Mesh tool
3. select attachment raptor_front_leg
4. select Direct mode
5. click and drag over a portion of vertexes on the leg (better if it has only two colors/bones so it's easier to spot the problem)
6. select a bone from the Weights panel to influence
7. drag the Weight slider
admire bug.

**Comment by erikari** [comment]
Also please note that this problem didn't occurr before the introduction of brushes for mesh painting.

**Comment by NathanSweet** [comment]
Thanks! Fixed in 3.6.39.
