### ISSUE TITLE
Hotkey popup dialog background renders incorrectly

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#212]
In some cases, the container for the hotkey popup does not render correctly.

CTRL+SHIFT+K looks off
![](http://i.imgur.com/vPF0crz.png)

Same with Pose 
![](http://i.imgur.com/NoES941.png)

While Translate looks ok
![](http://i.imgur.com/9FoIIm9.png)

Font: Unicode
Font Size: Medium
Interface Scale: 100

**Comment by NathanSweet** [comment]
3.6.41
