### ISSUE TITLE
Frame-by-frame scrubbing in preview view

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#214]
Adding the ability to scrub frames during preview view, at least by enabling the frame shortcuts "jump to start" "next frame" "previous frame".

**Comment by pharan** [comment]
Do you mean in Preview View?

**Comment by erikari** [comment]
Yep, thanks for pointing it out (:

**Comment by NathanSweet** [comment]
Consolidated preview improvements into #371. I asked some questions about timeline scrubbing there, please respond there.
