### ISSUE TITLE
[3.6.36 Editor quirk] Settings window scrolls to the bottom when you click Other...

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#216]
When you click on `Other...` under Version in the Settings window, it very quickly scrolls to the bottom.
Weird.
![2017-07-04_18-49-53](https://user-images.githubusercontent.com/1911082/27827391-9dba0a06-60e9-11e7-9786-bf51ba626fc0.gif)

**Comment by NathanSweet** [comment]
What the heck? I can't get it to happen in 3.6.36. It is consistent for you? What could possibly cause that!?

**Comment by pharan** [comment]
Just updated to 3.6.37. Seems to be still happening.
I remember this happening before and you fixed it.

Ok, so I resized the Spine Settings window. And now it doesn't do it anymore.
Can't seem to find the size that causes it to happen again.
Weird.

**Comment by NathanSweet** [comment]
I believe this has been fixed.
