### ISSUE TITLE
[3.6.36 Editor] Skeleton tree scrolling issue

### ISSUE THREAD

**Issue by desertkun** [EsotericSoftware/spine-editor#217]
Updated to 3.6.36 and noticed that I cannot edit some skeletons anymore, simply because I cannot scroll to see them.

As you can see, there's half of skeleton at the bottom of the list. But what even worse that it's like 10 of them there and I cannot edit them anymore.

<img width="558" alt="skeletons" src="https://user-images.githubusercontent.com/1666014/27830420-08d09ce4-60cf-11e7-9a5a-844fc3c79ba3.png">

if you open last one and collapse you have a 0.2s chance to see them because of transition animation

<img width="554" alt="transition" src="https://user-images.githubusercontent.com/1666014/27830441-17b77d72-60cf-11e7-9042-82d3003de6ce.png">

**Comment by NathanSweet** [comment]
Sorry, that is really bad! We've fixed it in 3.6.37, available in a few hours.
