### ISSUE TITLE
Dragging skin placeholder with linked mesh inside to a different slot is possible until restart.

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#218]
It shouldn't be possible to move a linked mesh to a different slot, but this way it is.

Repro steps:
1. create linked mesh
2. put the linked meshes in different skin placeholders
3. drag the skin placholder with the linked mesh to a different slot
4. save and reopen spine, on restart linked mesh is removed

Video attached to the topic.
See: http://esotericsoftware.com/forum/Project-Warning-removed-Linked-Mesh-when-re-open-8958

**Comment by NathanSweet** [comment]
3.6.46
