### ISSUE TITLE
Ghost mesh keys

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#219]
REPRO STEPS:
1. import image green
2. make image green a mesh
3. create bone green
4. parent image to bone
5. duplicate bone green
6. rename duplicated bone to red, rename its image to red, 
7. move aside bone red to see it
8. go to animate mode, then select a vertex of green and move it
9. press spacebar, then select the created deform keyframe, copy it and paste it at e.g. 40 in the timeline
10. create a couple more keyframes in the timeline by moving the vertexes of green
11. press spacebar, then select all the deform keyframes of green and copy them
12. position timeline line to 0, select the slot red, paste by pressing ctrl+v
> Bug occurs
13. select a vertex of red and move it, a new timeline is created.

BRIEF WORKAROUND TO PASTE THOSE KEYFRAMES (For Crocodilium):
- after point 10. go back to setup mode
- parent the slot red under the green bone
- go to animate mode and perform from 11. onwards, this time keyframes will be correctly created
- after that you can re-parent the red slot to your red bone and keyframes will stay.

https://www.dropbox.com/sh/et5k73sp7dfmdv4/AACkNkb0jYIl7EYokQO553hsa?dl=1 is the repro folder.
animations "test 1" "test 2" "test 4" show the bug
animation "test 3" demonstrates the workaround works.

for more information please see topic: http://esotericsoftware.com/forum/Weird-ghost-mesh-keys-8945?p=40679

**Comment by NathanSweet** [comment]
3.6.46 Thanks for the nice repro steps!
