### ISSUE TITLE
Inputing values in color dialog does not work

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-editor#222]
Confirmed in 3.6.36 and latest beta. See http://esotericsoftware.com/forum/Typing-color-values-is-not-functioning-correctly-9009

Repro:
1. Select image
2. Click on color
3. Try to enter a value in any of the R/G/B fields, e.g. `3` + `2` will result in `23` not `32`.

**Comment by badlogic** [comment]
Related: http://esotericsoftware.com/forum/HELP-Double-digits-when-changing-scale-in-setup-mode-O-o-8992

**Comment by NathanSweet** [comment]
3.6.41

**Comment by badlogic** [comment]
This does not appear to be fixed. The behaviour in 3.6.41 is now different. 

1. Open color dialog for image/mesh/whatever
2. Enter `3` in `R` field
3. Click on `G` field, `R` field changes value to `2`.

**Comment by NathanSweet** [comment]
This doesn't appear to be new behavior. Multiple RGB values can result in the same HSB values, and vice versa. Fixed by being sure to only change the values not being edited, 3.6.42.
