### ISSUE TITLE
transformed bones affected by IK, influences vertex positions when changing weights

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#223]
Reproduction. 
1. Create two bones (child/parent)
2. Place slot and attachment on second bone.
3. Convert attachment to mesh and click generate a couple of times.
4. Bind the two bones to the mesh under weights.
5. Select both bones and create IK. Create the IK with some distance to the tip of the second bone or move the IK target after creation.
6. Edit the weight of a single vertex.

Note how the vertex is transformed while changing the weight. Changing the mix to 0 on the IK constraint and THEN changing the weight will give the desired result.

http://esotericsoftware.com/forum/Bug-with-weights-9019?p=40914#p40914

**Comment by NathanSweet** [comment]
This appears to be correct behavior. IK transforms the bones after binding bones. Changing weights on transformed bones in setup mode will cause the vertices to move. `Update Bindings` can be used to store the IK transformed mesh as the bind pose, then the vertices will not move in setup mode when adjusting weights.
