### ISSUE TITLE
Animation panel not detecting change of skeleton

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#228]
Tiny bug confirmed, 
Refer to this repro case: http://esotericsoftware.com/forum/Any-progress-in-bug-fixing-9064?p=41103#p41103

"Create the project with two or more skeletons and make them all visible.
Switch to Animation mode.
Then try to switch between different skeletons by clicking on the bones that belong to these skeletons.
In the Animation Tool the skeletons won't be switched. In Spine 3.5.x this worked fine"

**Comment by NathanSweet** [comment]
3.6.41
