### ISSUE TITLE
Wireframe mesh editing bug

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#229]
Repro steps:
In setup mode
1. activate wireframe of a mesh
2. select a different attachment
3. make it a mesh, try to edit the mesh

Gif:
!(https://media.giphy.com/media/26zz2Fw5jUXaSVWFi/giphy.gif)

**Comment by NathanSweet** [comment]
I couldn't repro the weird clicking behavior, but I fixed in 3.6.40 that the wireframe mesh appeared in mesh edit mode when editing a different mesh.
