### ISSUE TITLE
Autoscroll on tree does not work with numerical stored selections

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#231]
From: http://esotericsoftware.com/forum/3-6-36-9084

> "Expand and scroll tree as the editor select changes" don't work with store keys (1,2,3,4,5,6,7,8,9,0) 
> work if manualy off then on button, but show last selected object in tree (if selected object > 1)

Little bug confirmed.
Just store a selection, scroll somewhere else and select something, press the number of the previously stored selection and it's not scrolling.

**Comment by NathanSweet** [comment]
3.6.40
