### ISSUE TITLE
Editor crashes on clipping/bounding box creation

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#237]
See this topic for repro steps and video
http://esotericsoftware.com/forum/Clipping-Bounding-box-crash-9121?sid=83ef1ff94a7f6b3c0c9de0115a679983

**Comment by erikari** [comment]
Bug confirmed and reproduced. Basically what makes it crash 100% is hitting the *New* button.
Works on any file.

Steps:
1. open file
2. select root
3. new>bounding box/clipping mask (both will crash)
4. give random name
5. hit the "New" button
crash.

(this button)
!(https://image.prntscr.com/image/9wpdMrdmRT2jxpk0zfbmFQ.png)

**Comment by erikari** [comment]
This happens in trial too http://esotericsoftware.com/forum/clipping-crash-in-trial-version-3-7-1-9184

**Comment by NathanSweet** [comment]
Fixed in 3.6.40. Thanks @erikari!
