### ISSUE TITLE
Add the currently selected animation as a label next to animate mode

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#239]
Or maybe in the windows bar?

Link to the topic: http://esotericsoftware.com/forum/viewtopic.php?f=11&t=9131&p=41381#p41381

**Comment by NathanSweet** [comment]
There isn't just one animation for projects that have multiple skeletons. The Animations view shows the chosen animation, as does the first row in the dopesheet (which is clickable BTW).
