### ISSUE TITLE
Bounding box doesn't empty the space when the new button is selected

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#240]
Fifth comment in the thread by master2015hp here: http://esotericsoftware.com/forum/Clipping-Bounding-box-crash-9121

Repro steps:
1. open Spineboy project (or any project)
2. select a bone (hip in my case)
3.  new>bounding box
4. create a 4 points bounding box (with a triangle it does not work)
5. hit "new" in the edit bounding box section
6. instead of empting the space, a point sticks to the mouse and you can't get rid of it.

Two examples of result:
![example1](https://image.prntscr.com/image/h0bZL_IKS2iLRgT4xFS4lQ.png)
![example2](https://image.prntscr.com/image/W8ysudGmSNqlWWzH6VUk0g.png)

**Comment by badlogic** [comment]
Related issue reported in "Spine crashing, steps to reproduce bug" email. Clicking "New" while in boundingbox creation mode and not having placed any vertices yet also crashes editor.

**Comment by NathanSweet** [comment]
3.6.40
