### ISSUE TITLE
[Import Data] When importing a json, then saving, the image path is set as the examples folder.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#242]
When importing a json (from the photoshop layers to png script), then saving, the image path is set as the Spine install folder.
![image](https://user-images.githubusercontent.com/1911082/29237195-c71d6052-7f4b-11e7-8dbd-caf5dd9e6982.png)

This will probably confuse the hell out of new users who might not know to look for the images node.

**Comment by pharan** [comment]
Just happened to me again! Damnit!

**Comment by NathanSweet** [comment]
This shouldn't happen anymore as of 3.6.40. If it does, please provide steps.

**Comment by pharan** [comment]
Happened to me with a new project.

Steps:
1. New Project
2. Check the Images node. Path is empty. But in the tree shows the Spine folder.  
![spine_2017-09-25_16-17-54](https://user-images.githubusercontent.com/1911082/30798696-1e787574-a20d-11e7-9e5d-0c20cb9b1181.png)
3. Save the project in a specific folder. (tried folder on the desktop)
4. Check the Images node. Path is now the Spine folder (`C:/Program Files(x86)/Spine/`).  
![spine_2017-09-25_16-19-18](https://user-images.githubusercontent.com/1911082/30798758-4f8c0658-a20d-11e7-98a4-b94ce25cc7d8.png)

**Comment by NathanSweet** [comment]
Should be fixed in 3.6.44.
