### ISSUE TITLE
Save Changes prompt after closing should allow the program to close.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#243]
**CURRENT BEHAVIOR**
Close Spine while your project is unsaved.
It asks if you want to save your project.
After you choose save, it saves, but then Spine doesn't close.
![m](https://user-images.githubusercontent.com/1911082/29252867-b0d6f98c-80a1-11e7-8228-4cec06f6832a.gif)

**EXPECTED**
Close Spine while your project is unsaved.
It asks if you want to save your project.
Then after your choice— save, or don't save— it should close it.

http://esotericsoftware.com/forum/Prompt-to-Save-Nitpicking-9158

**Comment by NathanSweet** [comment]
3.6.40
