### ISSUE TITLE
[GIF Export] Indicate that 50fps is the maximum that popular browsers will handle correctly.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#244]
In this context: http://pharanpostsartndevtrivia.tumblr.com/post/126581964275/how-is-an-animated-gifs-time-delay-between

Spine GIF Export should indicate that 50fps is the maximum recommended fps, because that's the limit of web browsers and image viewers.

Theoretically, it's 100fps based on the encoding scheme of gifs, but I have not seen a single browser or viewer that can play that back correctly. I wonder if this is written in a spec somewhere.

Suggestion:
The FPS text should turn red when it's over 50, or show the "!" warning icon.
with a hint message: "Most browsers can only handle up to 50fps."

**Comment by NathanSweet** [comment]
3.7.20-beta
