### ISSUE TITLE
[New Project Bug] Zoom to fit uses bones?

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#245]
When importing a new set of images into Spine for setting up, by importing a json generated by the Photoshop script, Spine editor normally does a "Zoom to Fit."

Currently, it judges "fit" according to the bones.
In a new project, there's only the default root bone.
So in a new project, it always zooms it at maximum level at (0,0) , usually putting all the images out of view.

This will also confuse the heck out of new users.

REPRO:
Existing:
1. Open the goblins project.
2. Select all slots
3. Parent it to the root bone.
4. Delete all the other bones.
5. Choose "Zoom to Fit"

New:
1. Get json and images from a photoshop script
2. Import Data, new project.
3. When it's done, it will Zoom to Fit.

Existing new:
1. Save a project with lots of images and only the root bone.
2. Close that project.
3. Open that project. It will zoom to fit.

**Comment by NathanSweet** [comment]
Couldn't repro using goblins, zoom to fit uses bones and verts. Did repro doing import with new project checked. Fixed in 3.6.40, thanks!

**Comment by pharan** [comment]
Looks fixed!
