### ISSUE TITLE
[bug] Unidentified cause. Missing image only in playback? See repro project

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#246]
REPRO:
1. Open "swap pose error state" project: [swap pose project with error state.zip](https://github.com/EsotericSoftware/spine-editor/files/1226518/swap.pose.project.with.error.state.zip)
2. Switch to Animate mode.
3. Choose the "jump" animation.
4. Press play (or "D") >>>> missing image
5. Stop playback.
6. Scrub the timeline. >>>> loading image blinks.

![2017-08-16_05-39-14](https://user-images.githubusercontent.com/1911082/29337794-4a54e016-8245-11e7-9e99-e0da54e9fefc.gif)

**Comment by NathanSweet** [comment]
In the project data, the key has a mesh attachment, but the slot has a region attachment. Both have the same name. Any idea how you got it in that state? Did you change it mesh <-> region? Maybe it was something you did in an older version of spine that had a bug? I can't repro it, changing mesh <-> region updates the keys correctly. Undo doesn't seem to be a problem either.

**Comment by NathanSweet** [comment]
Without knowing how the project got in such a state, we can't fix it.
