### ISSUE TITLE
Improve Graph curve preset editing

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#250]
You can already do this, but it's kinda weird, non-obvious, non-discoverable and too easy to accidentally do.

Current way to do it:
- Have an animation
- Have two keys on property in the dopesheet.
- Select the first one.
(The above is the minimum to show the graph in Graph view, and make presets selectable.)
- Adjust the graph. (this automatically applies it to the preset with no confirmation, which makes it easy to accidentally change your preset)

Possible safer implementation:
- (Only) allow editing the graph presets in a modal window that shows the graph.
- When you click the `+` button, it opens the window to prompt you to name it and save it.
- If you had a graph selected when you clicked `+`, it uses that as the graph for the new preset. Otherwise, it starts as linear.
- If you had a separate preset selected when you clicked `+`, uses the graph of that preset for the new preset.
- Double-clicking on a preset in the list opens the modal window for editing that preset. It allows you to change the graph and change the name, or delete it.

- issue: how do you update a preset's graph based on an existing key?

**Comment by NathanSweet** [comment]
The graph has changed so much in 3.9, this issue has become obsolete.
