### ISSUE TITLE
Spine PSD Export

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#252]
This would simplify drawing additional attachments for existing skeletons.

**Comment by pharan** [comment]
What would it do for attachments that were rotated or scaled or mapped to deformed meshes?

**Comment by NathanSweet** [comment]
It would likely rasterize each attachment in the current skeleton pose to a separate layer in the PSD.

**Comment by pharan** [comment]
Oh, is this just for drawing new attachments?
Not for exporting a PSD that you can later re-import?

Should clarify that somewhere in Spine if it's in a menu somewhere.

**Comment by NathanSweet** [comment]
Yeah, I think it's primarily useful for drawing new attachments.
