### ISSUE TITLE
Renaming skins does not sort them alphabetically

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#253]
Tested and confirmed!

From the forums: http://esotericsoftware.com/forum/Skin-sorting-in-the-Hierarchy-8803
>It seems that Spine does not trigger alphabetical skin sorting when renaming an existing skin (restarting Spine does not help).

>I'm testing this on 3.7.01 and the solution seems to be to either create a new skin or duplicate an existing one in order to trigger the alphabetical sorting. After that you can just delete the new or duplicated skin

**Comment by NathanSweet** [comment]
3.6.40
