### ISSUE TITLE
Vertex can be moved outside the mesh border

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#254]
Expected result:
Vertex should stay inside the border

Result I got:
it was possible to move the vertex outside

Repro steps:
1. open the raptor example
2. select the mesh of the body(or whatever mesh)
3. click on Edit mesh
4. create a new point inside the mesh
5. move the new point outside the mesh
6. the point can't be moved again, only deleted

Post in the forums about the topic:
http://esotericsoftware.com/forum/MeshVetex-9229

Repro gif:
![complete gif](https://media.giphy.com/media/xT9Igt9iDZ26cDb0Zy/giphy.gif)

**Comment by NathanSweet** [comment]
This is actually allowed, though it isn't very useful. The enforcement is only that hull edges and internal edges must not cross. The point can be moved if `Deformed` is unchecked.

We can look into disallowing moving a vertex with no edges outside the hull. Changing the enhancement.

**Comment by NathanSweet** [comment]
Disallowing moving a vertex with no edges outside the hull isn't so easy. I think we can leave this edge case for now, especially since it can be moved with `Deformed` unchecked.
