### ISSUE TITLE
First point when creating a Path Attachment always creates a 45° handle.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#255]
repro video: https://streamable.com/k7c7q

**Repro:**
1. New Skeleton.
2. Select the root bone.
3. Choose `New ...` > `Path`
4. Create the first point on the viewport: click and drag to the left, then release. (nothing is visible at this point)
5. Create the second point: Click and drag anywhere and release. BUG

**What happens:**
The first point will have a handle at 45° to its lower right, regardless of where you dragged the first point's handle when you created it.

**Expected:**
The handle should be where you released the drag when you created the first point.
OR some other sensible default.

**Comment by NathanSweet** [comment]
The first handle was picked using what made sense if you were to click rather than drag the second handle. In 3.6.40 it now adjusts the first handle as you drag.
