### ISSUE TITLE
[UI] Add icons to the Spine menu.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#256]
I feel like icons would improve the readability of the menu.

Especially for the "Import Project" and "Import Data" items.
"Import Project" can have the Spine Project icon,
(and Import Data can have a text icon?)
to clearly communicate what type of file you're trying to import.

**Comment by NathanSweet** [comment]
@Shiu Let's get this done for 3.8! I've jammed in the icons we already have:
![](http://n4te.com/x/6545-DYVa.png)

**Comment by NathanSweet** [comment]
![](http://n4te.com/x/6549-cuCW.png)
Going to roll with this. @Shiu reopen and commit new files to improve, but I'm closing this (1.5 years is too long for such a simple issue).

**Comment by Shiu** [comment]
I'll reopen tomorrow and fix up/improve some icons
