### ISSUE TITLE
Allow importing multiple animations at once

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#258]
Currently it is only possible to import animations one by one, it would be nice:
1. to be able to import multiple animations at the same time by selecting them
2. to import them all at the same time

Refer to the forum topic: http://esotericsoftware.com/forum/Feature-Request-Importing-multiple-animations-9264

**Comment by erikari** [comment]
+ 1 http://esotericsoftware.com/forum/x-10478

**Comment by NathanSweet** [comment]
In 3.8.23-beta, sorry it took so long!
