### ISSUE TITLE
Whitespacing trimming for meshes

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#260]
Texture packing needs to know about mesh UVs, so it can know how much whitespace can trimmed without affecting parts of the image used by meshes.

**Comment by pharan** [comment]
http://esotericsoftware.com/forum/Stripping-WhiteSpace-and-Mesh-animations-10754?p=48413

**Comment by NathanSweet** [comment]
Done in 3.7.77-beta and EsotericSoftware/spine-runtimes#1232
