### ISSUE TITLE
Keying transparency makes the alpha reset to 254

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#262]
See the forum post http://esotericsoftware.com/forum/Editor-3-6-37-Alpha-resets-to-254-9303

Repro steps:
1. Create new skeleton
2. Add an image
3. Insert a keyframe with color 255, 255, 255, 255
4. Save file
5. Reload file
6. Open keyframe and see that the color has changed to 255, 255, 255, 254

**Comment by NathanSweet** [comment]
3.6.41
