### ISSUE TITLE
Changing mesh influence on vertexes moves them in setup mode

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#264]
**Expected result:**
Changing the weight of a bone on a vertex in setup mode shouldn't move the vertex. 

If they should move,(e.g. in animate mode) I expect many vertexes at 100% of one bone to retain the original aspect of the selected portion, but oriented according to the new bone influence.

**Actual result:**
Very weird influence positions on the mesh vertexes even when many vertexes are influenced by the same bone at 100%.

**Repro steps:**
1. Open Raptor project
2. Select Weights tool
3. Switch to Direct mode
4. Select portion of the vertexes in the tail
5. Select Torso1 from the list of bones in weights panel
6. raise influence to 100% using the slider

**Repro gif:**
![gif](https://media.giphy.com/media/3ov9jEr7bqa4HfD5n2/giphy.gif)

**Comment by NathanSweet** [comment]
This is a very old raptor project where the bones were bound and then rotated. Later we changed to adjusting the bind pose when bound bones are transformed. Even later we changed to not adjusting the bind pose, but providing an `Update Bindings` button. TL;DR, the latest raptor should not have this problem. Projects can be "fixed" by using `Update Bindings`.
