### ISSUE TITLE
Export incorrectly shows "image [...] not found" warning.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#265]
User submitted a case where exporting a project causes Spine (3.6.41) to show an "image not found" warning.
http://esotericsoftware.com/forum/export-waring-image-for-slot-not-found-9316
![image](https://user-images.githubusercontent.com/1911082/30856010-932ac26e-a2e9-11e7-98b1-c46ab0c2671c.png)

Nothing seems to be out of the ordinary in the project except that the images are very large.
The image "eff1.png" definitely exists and is in the correct folder.
The slot is "Additive".
The attachment has "Select" and "Export" checked.

**Comment by NathanSweet** [comment]
No repro?

**Comment by pharan** [comment]
Sorry, I accidentally pressed the submit before being able to write the body. Repro project is in the forum link.

**Comment by NathanSweet** [comment]
3.6.46
