### ISSUE TITLE
Vertices count is wrong when creating clipping

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#267]
Repro steps:
1. create new project
2. select root bone
3. new>clipping
4. call clipping "portal"(lol or whatever)
5. create geometrical figure
vertices remain 0, when closing the figure, vertices are the actual number -1

Repro gif:
![sigh](https://media.giphy.com/media/xT9IgpH6NXqhkpgSqc/giphy.gif)

**Comment by NathanSweet** [comment]
3.6.42
