### ISSUE TITLE
Editor fails to import json - but the skeleton is there

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#275]
Very weird bug that happens with the latest version of PhotoshopToSpine script.
First the Editor says it can't import the json file, then the skeleton magically appears if you create a new bone.

**Links to the files:**
https://www.dropbox.com/sh/g0cfu7u7x1ywygo/AABkVJBQoauRiDYWEUA8mYk8a?dl=1

**Repro steps:**
1. drag and drop json file on a new project window
2. error pops out, close it
3. select root bone
4. click new bone and create one
5. new skeleton magically appears
(why is this happening? O:)

**Repro gif:**
![](https://media.giphy.com/media/3o7aCTYmNid7SLPrMs/giphy.gif)

**Comment by pharan** [comment]
Probably related but different: https://github.com/EsotericSoftware/spine-editor/issues/273

**Comment by badlogic** [comment]
Works in 3.6.43
