### ISSUE TITLE
Dragging bone from one skeleton to another crashes

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-editor#277]
Repro: http://esotericsoftware.com/forum/download/file.php?id=3773
Thread: http://esotericsoftware.com/forum/Spine-Crashes-9346
Steps:
1. Drag `bone11` from `Shotgun` skeleton to `root` bone of `Characters_CUT` skeleton.

**Comment by NathanSweet** [comment]
Still crashes, not sure why user said it doesn't.

**Comment by NathanSweet** [comment]
3.6.46
