### ISSUE TITLE
Mesh flips when using "generate" button

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#278]
It either does this at the very beginning or when you close the mesh editing tool.
See http://esotericsoftware.com/forum/Bug-when-editing-the-mesh-in-version-3-6-43-9362 for a repro video.

Repro steps: 
1. click on any attachment that isn't a mesh
2. check the Mesh thick to make it a mesh
3. edit mesh
4. click on "generate" (I clicked 3 times)
5. in my case, the image got flipped instantly, in the user's case, when he closed the dialog.

**Comment by erikari** [comment]
related topic with the same problem (and a video!) http://esotericsoftware.com/forum/Rotate-the-mesh-object-when-Generate-button-is-clicked-9384

**Comment by NathanSweet** [comment]
3.6.45: Improved keeping the mesh position when removing deformation for: `Reset` in the tree properties in setup mode, `Reset`, `Generate`, and `New` in edit mesh mode, and when converting a mesh to a region.
