### ISSUE TITLE
Duplicated paths have same name

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#279]
Repro:
1. open spineboy project
2. select gun slot
3. create new path, make a couple points
4. duplicate "rear_upper_arm"

All the new slots get a 2, path does not, it keeps the same name instead.

Reference thread: http://esotericsoftware.com/forum/duplicated-path-has-same-name-9375

**Comment by NathanSweet** [comment]
Slots names are unique within the skeleton, so get a 2. Path (and all attachment) names are unique within each slot, so do not get a 2. If the attachment is moved to a slot which already contains an attachment by that name, the moved attachment is renamed with a 2.
