### ISSUE TITLE
"Jump to last key" shortcut does not display keyed tools correctly

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#280]
Reference topic:
http://esotericsoftware.com/forum/Icon-key-displayed-red-green-9361

Repro project:
https://www.dropbox.com/s/rurebtnt2r11fcb/repro-last-key.spine?dl=1

Repro steps:
1.go to animate mode
2.select bone "nate"
3.press shortcut "E"

Espected results:
Green keys next to tools, since there are no keys

Actual results:
3 keyframes are red
If you manually go to last key, though, results are correct.

**Comment by NathanSweet** [comment]
3.6.46
