### ISSUE TITLE
Pressing space to deselect everything with 2+ skeletons doesn't show all dopesheet keys

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#281]
When only one skeleton is present, pressing space will deselect everything ans show all the dopesheet keys, with 2+ skeletons though, pressing space only deselects everything without allowing to see all the keys in a skeleton/both skeletons.

proposed solution: 
Either allow to see all the dopesheet keys of the skeletons, or the keys of the last selected skeleton.

See http://esotericsoftware.com/forum/all-keys-disappear-from-dopesheet-9396 for more info

**Comment by NathanSweet** [comment]
3.7.35-beta, dopesheet should work intelligently when deselecting with projects that have multiple skeletons.
