### ISSUE TITLE
Creating bones on macOS is slow

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-editor#282]
1. Switch to Create mode
2. Drag new bone
3. See it drag at 1fps

Also see email "Crash log" from the 14th of October.

**Comment by NathanSweet** [comment]
I'm not seeing anything that looks suspect, nor slowdown on Windows. @badlogic can you narrow it down on OS X? Probably comment things out in BoneCreateTool#drag until it's not slow.

**Comment by badlogic** [comment]
This issue does not show up anymore. Tested on latest beta and macOS.
