### ISSUE TITLE
[UI] Add indicator that tree items can be reordered.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#284]
Nate mentioned adding up/down arrows for tree items that can be reordered to make them more discoverable. http://esotericsoftware.com/forum/Combining-path-and-transform-constraints-doesn-t-work-9432

I think another common and more simple symbol is the grooved handle.
![reorder handle 2](https://user-images.githubusercontent.com/1911082/31761537-cc32cb98-b4ea-11e7-9340-2aea397dde4b.gif)
![reorder handle](https://user-images.githubusercontent.com/1911082/31761540-ce28e09a-b4ea-11e7-8d2c-483bb178d2be.gif)

**Comment by pharan** [comment]
Another lost soul: http://esotericsoftware.com/forum/viewtopic.php?f=11&t=9500

**Comment by pharan** [comment]
http://esotericsoftware.com/forum/IK-Constraints-works-differently-due-to-its-creation-order-10300

**Comment by NathanSweet** [comment]
3.7.16-beta
