### ISSUE TITLE
Create Bone tool clicks through title bar

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#286]
Repro steps:
1. Maximize the window
2. Select the Create Bone tool
3. Move the mouse to the very top of the window and click

Repro image:
![](http://esotericsoftware.com/forum/download/file.php?id=3820)

Related topic:
http://esotericsoftware.com/forum/Create-Bone-Tool-Clicks-Through-Title-Bar-9438

**Comment by NathanSweet** [comment]
3.6.46
