### ISSUE TITLE
Missing and failed image and audio files

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#287]
Currently, under the Audio node, audio files that are not used yet are red and audio files that are used in events are green. This matches image file icons under the Images node, but maybe red is not the best choice for either, now that we have audio files which are more likely to fail to load. Actually, images can also fail to load and that state could be reflected in their icon. Currently we do not indicate an image file is missing or failed to load for an attachment.

We should consider revising the used and unused icons for both image files and audio files. Unused might be yellow, orange, black, or otherwise not highlighted (but not red!). Used is probably best as green.

Next, we could also use an overlay for failed and missing image files and audio files. Failed could be a red exclamation point. Missing could be a red question mark. We would also use this overlay with region attachments, mesh attachments (normal/source/linked), and audio events when the corresponding image file or audio file is failed or missing.

**Comment by NathanSweet** [comment]
Updated issue description.

**Comment by NathanSweet** [comment]
I also noticed region attachments use the same icon as image files. Should we do something different? It should stay quite different from meshes, but doesn't have to be the exact same as image files.

**Comment by NathanSweet** [comment]
Here's an example showing failed image, audio, audio event, and missing image for `red` mesh:
![](http://n4te.com/x/2921-TKKA.png)

**Comment by NathanSweet** [comment]
Also, icon for region attachments is `icon-region`.

**Comment by pharan** [comment]
Other options.
![image](https://user-images.githubusercontent.com/1911082/31858641-3b76745a-b72f-11e7-91cb-501fbf70c37c.png)

**Comment by NathanSweet** [comment]
Yep, that is much nicer. Mine is just programmer art so I could add the logic. :)
