### ISSUE TITLE
Png/gif export crops animation

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#289]
**what happens**
Exported png sequences are cropped not according to the animation size.

**Repro project:**
mail n° 15f52542edc32bb3 by Fikri.

**Repro steps:**
1. open project
2. go to animate mode
3. Ctrl+E (export)
4. if unselected, choose png export. settings should be already set, but in case they aren't:

Type: Sequence
Animation: Current
Skins: Current
Output folder: E:/fireing/
images is the only one selected
no background
25 FPS
no atlas

Export and bug occurs, the fire image is cropped.

-----

If one of the images in slot `skeleton-animation_0` is activated though, the animation exports without cropping. I think Editor is not considering images not visible in setup mode.

**Comment by recircle** [comment]
I ran to it today, please can you fix this soon :)

**Comment by erikari** [comment]
Another user reporting this and in his case **nothing** shows in the video 
http://esotericsoftware.com/forum/Exporting-to-AVI-or-MOV-Doesn-t-show-images-9539?p=43239#p43239

**Comment by NathanSweet** [comment]
Sorry for the delay. Fixed in 3.6.48!
