### ISSUE TITLE
Images in subfolders show export warnings

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#290]
**expected results**
Images in subfolders shouldn't give problems exporting

**actual results**
Spine fails to export images that are in subfolders

**repro steps**
1. create new project
2. select an image folder that includes a subfolder with an image
3. drag image from subfolder in the viewport
4. export json
> witness error

**repro project**
https://www.dropbox.com/sh/nzwc8ft47zh0dcq/AADKZuEl76IS-BAwXpoYaTega?dl=1
(it's actually just a new file in the goblin example, can also not download it)

**repro gif**
![buggie bug](https://media.giphy.com/media/3o7aD8CsIOh6oNEj3G/giphy.gif)

**Comment by NathanSweet** [comment]
Those are warnings, so I don't think it actually failed to export. Certainly shouldn't show the warnings though!

**Comment by erikari** [comment]
It exported a json but not the atlas s:

**Comment by NathanSweet** [comment]
3.7.07-beta

**Comment by NathanSweet** [comment]
Also 3.6.47
