### ISSUE TITLE
Skin placeholder on bone makes Spine crash

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#291]
Expected results:
Creating skin placeholders should be disabled for bones

Actual results:
it is possible, if you do, Spine crashes.

Repro steps:
1. new project
2. select root bone
3. select new>skin placeholder
4. rename skin placeholder "moo" and press ok
> crash

**Comment by NathanSweet** [comment]
Creating on a bone is OK (it will create a slot, like when dragging to a bone), crashing is not OK!

**Comment by NathanSweet** [comment]
3.7.07-beta

**Comment by NathanSweet** [comment]
Also 3.6.47
