### ISSUE TITLE
Scaling with direct input fails if there are decimals

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#296]
**Description of the problem:**
When a bone is scaled by typing the value in the field and pressing enter/tab, if the value has numbers after the decimals, the new value is ignored or is different than the one typed inside.

**Explanation:**
What is seen is local axis, even though the world axis was selected. But there is no visual clue that it's local instead of world.

**Possible solution:**
when a field that is not editable in the current axis is selected, it would be better to show that the axis changed, and then go back to the axis previously selected by the user once the field is unselected.

**Repro project:**
Open repro project included in mail 15f9b9a45c5b1955

**Repro steps:**
1. open repro project (it's ok to see images missing)
2. switch to animate mode
3. select bone `head` (tool is not important, mine is rotate)
4. in the `transform` box find the value `1.05` and replace it with `1.00`
5. press `TAB` two times
> the value is back to `1.00`
or:
4. in the `transform` box find the value `1.05` and replace it with `9`
5. press `TAB` two times
> the new value is  `9.45` (which makes absolutely no sense)

**Repro gif present in discussion thread:**
esotericsoftware.com/forum/Scale-transform-values-9530

**Comment by NathanSweet** [comment]
This only happens when `World` axes are selected. It happens because only local scale can be edited, but world scale is shown. The scale should change from world to local when focused. A bug has been fixed in 3.8.48-beta regarding that.
