### ISSUE TITLE
Tree filters cause slots to be grayed out when trying to drag a new image.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#297]
When you drag an image to a slot in the tree, it will add an attachment to that slot.
But you can't do that when tree filters (slots or slot+attachments) are active. The slots are being grayed out when you are in the middle of dragging an image.

Repro:
Open Spineboy.
Enable tree filters for (slots) or (slots and attachments).
Try dragging any image into any of the slots.
Doesn't work.

User report:
http://esotericsoftware.com/forum/Drag-and-Drop-Image-While-Filters-Active-Feature-Request-9550

**Comment by NathanSweet** [comment]
3.6.48
