### ISSUE TITLE
In Weights panel, if Direct mode was the last selected tool, it doesn't show the correct options

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#299]
When starting Spine and opening the Weights tool this is what is shown:
![actual](https://image.prntscr.com/image/SWP8X10WSQi14W9TnkcF9w.png)

but it is unusable, so the user is obliged to change mode and then change back to see the correct option:
![desired](https://image.prntscr.com/image/pyOdbbv5Qb_4lgrdaP9j7w.png)

**Comment by NathanSweet** [comment]
3.6.52
