### ISSUE TITLE
Restore "Tab to set and move to next textbox"

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#3]
Pressing Tab when entering values in the transform text boxes reverts the value and moves focus to the next textbox.

Expected: Pressing Tab should should apply the value in the current textbox before moving focus.

User reported it was working correctly before but now it doesn't.
http://esotericsoftware.com/forum/Using-the-TAB-key-to-enter-values-removed-6337

**Comment by pharan** [comment]
User also noted that it happens in some textboxes but not others.

"Yep, you know what's strange. This happens on the Translate boxes BUT if you are in the Scale X box, enter a value and hit TAB you will have the value applied as expected."

**Comment by NathanSweet** [comment]
Related, the number shown is rounded, so it should only be applied if they user edited it before tabbing or pressed entered.

**Comment by NathanSweet** [comment]
In 3.3 values are applied as you type.
