### ISSUE TITLE
Photoshop script merges two layers into one on export

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#300]
**Problem:**
With the latest version of the script and the repro file, exporting will merge two eyelashes on the same layer. (as described in the mail)

**Repro files:**
Refer to mail 1600746793148a49

**Attempted solutions:**
- Renaming the first folder to [skin] did not solve the problem
- Inverting the position of the folders made the second folder present the problem
- Inverting the layer order inside the problematic folder made the middle element always show the problem.
- changing the names of course solved nothing

**Comment by NathanSweet** [comment]
Fixed in script v2.5.
