### ISSUE TITLE
Allow transferring weights from one bone to another

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#301]
**Use cases**
- Splitting the influence of a bone in two bones that should retain the same influence.
- Tranferring the influence from a bone to another in a different position
- Correcting a bone after unbinding it

**Proposed workflow:**
Add a Mode (that would be rightfully called Replace, while the Replace that exists now would be called "Set, Force, Define" or something else) that once selected would have two more fields:
1. source bone (the bone from which the weights are taken)
2. target bone (the bone that receives the weight percentages)
maybe a button to replace them all with one click, or the brush to strike on the parts that need to be changed.

**Actual workflow:**
taking screenshots or note down the percentages for over 30 vertexes in order to add a new bone to influence the same area another bone was influencing, and having to manually type in all those weights

**Comment by erikari** [comment]
"Weights swap" could be a decent name for this.

**Comment by erikari** [comment]
a +1 here: http://esotericsoftware.com/forum/Tool-for-replace-weight-from-one-bone-to-antoher-13512

**Comment by Lhescar** [comment]
+1 here too!

Something like that:

![Transfert feature](https://user-images.githubusercontent.com/17269663/78511620-23dbc480-776c-11ea-93b3-0d4fc373bb1b.jpg)

**Comment by Lhescar** [comment]
It could work this way.
Once transfert mode is selected, three options are displayed:
1. choosing the bone we need to transfert weights
2. selecting bone which will receive the weights
3. defining % of transfert.

What i'm not sure is if the new target bone must be already in the bent bones list to make it work?

![Transfert_mode](https://user-images.githubusercontent.com/17269663/78512287-3b697c00-7771-11ea-96f0-c3cba9d2eb7f.jpg)

**Comment by NathanSweet** [comment]
Detailed use case here:
http://esotericsoftware.com/forum/Feature-Request-14703

**Comment by WArmanW** [comment]
+1

**Comment by munderfire** [comment]
Or will be better if we can lock values of the bone weights on mesh?
This is same in use, but more fundamental
![Weights_lock](https://user-images.githubusercontent.com/81576913/112859612-aa935b00-90bb-11eb-951e-d425b51a6944.jpg)

**Comment by FabianoIlCapo** [comment]
I think the 2 tools would be useful in different scenarios (1: I want to transfer weight between bones or 2: I want to keep one or more bones influence untouched).
But yes, Weight Lock is more versatile and could be used in both cases (therefore I think it should be prioritized), while the Transfer couldn't.

**Comment by erikari** [comment]
Another +1 for the feature here: http://esotericsoftware.com/forum/Replace-Weights-to-another-bone-16094

**Comment by 73tunnel** [comment]
I am convinced that this feature will be very useful for creating advanced skeletons using mesh deformation.
As we move forward in the project, there will always be times when we need to improve the skeleton. I believe that this feature will greatly improve my work efficiency.

**Comment by NathanSweet** [comment]
4.1.16-beta allows locking bone weights. You can lock all bones except for 2, then remove or add to one of the unlocked bones to transfer weight from one bone to the other. This covers the desired use case and more.

Note that selected bones are always affected, even if locked. So you can lock all bones, unlock one, then select another and adjust it.

To quickly lock/unlock many bones, press an hold on one of the lock buttons (the colored squares), then drag to other lock buttons.
