### ISSUE TITLE
Spine crashes when trying to parent a bone from one skeleton to the bone of a different skeleton

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#302]
Repro steps:
1. open a project (e.g. spineboy-mesh that already has two skeletons within)
2. select a bone from one skeleton (e.g. the head)
3. press `P` and try to parent it to a bone in the other skeleton (e.g. the other head)
> spine crashes

It should probably be disallowed instead.

**Comment by supersaiyansubtlety** [comment]
+1 to fix this. Disallowing would be fine short term, but making it work properly in the future would be great.

**Comment by NathanSweet** [comment]
Duplicate of #341, which appears has been fixed.
