### ISSUE TITLE
Shift button and pressing alt don't move all the keyframes after the selected one

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#305]
Instead, they only move all the keys of the bones that have a key on the selected column but not any other key that comes after.

See topic: http://esotericsoftware.com/forum/Shift-all-frames-at-once-dope-sheet-9409

**Comment by NathanSweet** [comment]
Fixed in 3.7.16-beta.

Correct behavior: when a white "overview" key is moved, either all keys (if first row overview key is moved) or all keys under the bone (if bone overview key is moved) should also move.
