### ISSUE TITLE
While binding bones to a mesh, the first bone gets selected, making auto weights only weight one bone

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#308]
Repro:
1. open the raptor project
2. select a mesh (I selected a leg)
3. open the weights panel
4. select all the bones in the weights view
5. remove them
6. click bind
7. select some bones again (note that only the first will appear selected in the weights view)
8. click "bind" again
> weights will be calculated on only one bone

Notes: one must click on the bone to make sure it gets deselected, then click on "auto" again.
In older versions this wasn't necessary.

Refer to this topic for discussion and repro gifs:
http://esotericsoftware.com/forum/Weight-issues-2-pictures-for-the-same-bone-9692

**Comment by NathanSweet** [comment]
Changed to bone is deselected after binding bones, before running auto weights. Also added a toast when not all vertices or bones were auto weighted
3.6.51
