### ISSUE TITLE
Point attachments

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#31]
This is an attachment that is just a single point, useful for spawning projectiles, etc at runtime. By using an attachment rather than a bone, different skins can have different points. The point could also have rotation.

http://esotericsoftware.com/forum/viewtopic.php?f=11&t=2872&p=13993#p13993

**Comment by Xelnath** [comment]
Handy!

**Comment by pharan** [comment]
Maybe related. Some people have been looking for a way to define a circle (like a bounding box attachment, but a circle).

Is it as simple as giving PointAttachment a radius?

**Comment by NathanSweet** [comment]
@pharan It could be, though the editor won't show the circle of course. The right way would probably be a BoundingCircleAttachment (what a lovely name).

**Comment by Xelnath** [comment]
A beautiful bounding circle!

**Comment by NathanSweet** [comment]
3.6.00-beta
