### ISSUE TITLE
Draw order not kept when moving slots across skeletons

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#312]
**Repro steps:**
1. open a project (the easiest thing to do is use a json from a photoshop export and not click "new project" so you already will have two skeletons)
2. select all the slots in a skeleton
3. drag them in the other skeleton releasing them on the root
> draw order is different, can't say it's inverted, but it's not respected.

**Repro screenshots:**
![before](https://image.prntscr.com/image/Hkt6dB3_Trm5iXju4vxIIA.png)
![after](https://image.prntscr.com/image/fQcWhER4RQqhXF8JKh25dw.png)

**Forum topic:**
http://it.esotericsoftware.com/forum/x-9828

**Comment by NathanSweet** [comment]
3.7.43-beta
