### ISSUE TITLE
Improve "Shift" hotkey functionality when creating straight edges in Edit Mesh mode

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#314]
Currently when holding shift and creating a straight edge, the edge will only stay straight as long as the end does not touch another edge.

An example:
1. Create mesh.
2. In Edit Mode, click and edge, hold shift and drag the cursor towards the opposite side edge. Once the cursor is over the opposite side edge, it loses it's "Straight edge" functionality.

**Comment by Joel-Hjerten** [comment]
This one is driving me nuts. I'd love to see this resolved.

**Comment by NathanSweet** [comment]
Agreed! Sorry it's taking so long. We're doing the v4.0 beta now, then we'll do a v4.1 release that focuses on many quality of life improvements like this.

**Comment by NathanSweet** [comment]
This has been fixed a long time. When the new vertex hits an edge while holding `shift`, it snaps to the edge while staying straight.
