### ISSUE TITLE
Favorite image dialog will not close and be empty if an absolute path is selected

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#315]
**What happens:**
When selecting an absolute path it is possible to remove it from the folder list of the "image files" dialog. 
Following the repro steps will prevent the dialog from closing and will still show an empty list after selecting a new folder.

**What should happen:**
The dialog should close when the new path is selected, and the list should not be empty.

Reproduced on 3.7.09-beta, and 3.6.51 (ess and pro) using Windows 10. 

**Repro steps:**
1. open project
2. select images node in the tree
3. select the "favorites" star button next to the path 
4. the "image files" opens. right click every name in the list "folders" until they are all gone.
In my case right-clicking the images folder in use does not clear it (I think because the path is not absolute, but relative to the project). therefore I cannot perform this part.
so I:
5. click "browse" and select an absolute path (e.g. something like "E:/spine/hello/images/"). 
the new path is used, the window is closed. <- ok behavior
6. click on the "favorites" star button next to the path (again, like in point 3)
7. now I only see the folder of the new path. I right-click it and it disappears. no folders are left in the list.
8. I select "browse" and pick a folder (an absolute path again in the computer)
> the path is selected because it is shown in the images node. 
>The "images file" window stays open instead of closing. 
> The "folder" list inside it does not list the folder I just selected.
![bug final screenshot showing point 8](https://image.prntscr.com/image/8MAn3fxpSyGHmmeqzvzrTg.png)
So I have to click "cancel" to exit the window, opening the favorites again will show the folder.

**Forum topic with more steps, repro gif, etc:**
http://esotericsoftware.com/forum/More-Problems-with-Improved-File-Dialog-9856

**Comment by NathanSweet** [comment]
3.7.16-beta

Fixed dialog staying open. Also favorites are no longer shown if the dialog contains only the "default" entry (eg the current images path).
