### ISSUE TITLE
shortKey and macro visualizer

### ISSUE THREAD

**Issue by djmisterjon** [EsotericSoftware/spine-editor#317]
**suggest:** 
A contextual menu, which will display all shortcut for study and affectation.
i nice example visualiser here from AE.
i can not find the shortKeyt list !!!
![keyboard](https://user-images.githubusercontent.com/24865815/35785577-4e5852d8-09ef-11e8-8bf9-28e7e4da0d37.png)

**Comment by NathanSweet** [comment]
Agreed, though this is a duplicate of #206. There's this:
http://esotericsoftware.com/spine-cheat-sheet
Also the `hotkeys.txt` in your Spine user folder defines all the hotkeys and you can edit them:
Windows: <user home folder>\Spine\hotkeys.txt
Mac: <user home folder>/Library/Application Support/Spine/hotkeys.txt
Linux: <user home folder>/.spine/hotkeys.txt
