### ISSUE TITLE
Constraint the same bone multiple times is allowed

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#318]
**Repro steps:**
1. open Stretchyman-pro
2. select a path constraint from the constraint list (I picked front-arm-path)
3. In the options box, click the pencil in the Bones row to edit the bones that are part of it
4. repeatedly click on the same bone

**Repro image:**
![repro image](https://image.prntscr.com/image/fKskT5eUQwaqhY7muXM7uQ.png)

**Reference Thread:**
http://esotericsoftware.com/forum/Bone-listed-twice-in-path-constraint-9905

**Comment by NathanSweet** [comment]
3.7.16-beta
