### ISSUE TITLE
Clipping / masking

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#32]
This is a rectangle aligned with the screen axes which clips rendering (see glScissors).

Need some way of controlling what attachments are clipped. Maybe 2 attachments are used, one to turn it on and one to turn it off. Any slots in the draw order between these two are clipped.

**Comment by kanevsky** [comment]
is it really planned on 3.6?

**Comment by manuelsongokuh** [comment]
sorry i want to know what is clipping and masking? are there any example?

**Comment by NathanSweet** [comment]
@kanevsky Yes, the Milestone field is accurate.

@manuelsongokuh This is an issue tracker. Please use the forum to ask questions.
