### ISSUE TITLE
Allow the user to choose if clicking on a selected item in tree view deselects it or not

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#323]
Proposal:
Add a tickbox in Settings to make clicking an element in Tree view do nothing instead of deselecting.

Original request:
> More over, I don't like clicking on a already selected item will causing it deselected. Its better to have an option to disable this "feature".
[original post](http://esotericsoftware.com/forum/Hierarchy-search-box-9916)

**Comment by NathanSweet** [comment]
That a user doesn't like it is good to know, but not terribly helpful. We need more information about *why* a user doesn't like it before we can consider making a change.
