### ISSUE TITLE
Numeric Shear Y value entered in reverse when Auto Key active

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#326]
Reproduction steps:
1. Select bone
2. Enable Auto Key
3. Enter value in Shear Y
Value will be entered in reverse.
Without Auto Key active, numeric input is entered correctly.

http://esotericsoftware.com/forum/Shear-input-box-bug-9996

**Comment by NathanSweet** [comment]
3.7.43-beta
