### ISSUE TITLE
Renaming multiple sequential bones

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#330]
From the forum:
>Add the ability to select multiple bones (or any other item), then give it a name like:
>"tail_bone_1", and all other selected bones, will get a sequential name according to their selection order,
so spine will automatically will name them tail_bone_2, tail_bone_3 etc..

Original discussion with more info:
http://esotericsoftware.com/forum/renaming-multiple-sequential-bones-9093

**Comment by NathanSweet** [comment]
3.7.33-beta
