### ISSUE TITLE
Mesh path bug

### ISSUE THREAD

**Issue by chronszcz** [EsotericSoftware/spine-editor#332]
Hello!

When you set a path to a mesh it instantly becomes "missing". If you do the same to regular image attachments they work perfectly.

Note: It seems to have problems with paths with extensions.

Am I doing something wrong?

**Comment by NathanSweet** [comment]
Setting a path uses the path instead of the attachment name. Please see the documentation here:
http://esotericsoftware.com/spine-images#Image-file-lookup
If you are still having trouble, please post on the editor forum:
http://esotericsoftware.com/forum/viewforum.php?f=11

**Comment by chronszcz** [comment]
I've read the documentation...

Please take a look at this example:

[spine_test.zip](https://github.com/EsotericSoftware/spine-editor/files/1811117/spine_test.zip)

**Comment by NathanSweet** [comment]
Can't blame me for not making assumptions. :)

Project looks fine. Please provide steps to reproduce your problem.
![](http://n4te.com/x/3697-sheh.png)

**Comment by chronszcz** [comment]
Hmm... This example looks like this on my computer:

The left tree is a mesh and it doesn't have an extension and it's fine:

http://prntscr.com/ir2tn4

The middle one is a mesh and it has an extension. It's "missing":

http://prntscr.com/ir2uaa

The right one is a regular image attachment. It's fine:

http://prntscr.com/ir2uou

**Comment by NathanSweet** [comment]
OK. In 3.6.52 I see a missing placeholder for the middle mesh. In 3.7.14-beta I see the middle mesh works fine, so it seems the issue is fixed in 3.7. If you omit the file extension, it works fine in 3.6.52.

**Comment by chronszcz** [comment]
Yes. But in my situation I actually need the file extension. I'm glad that it got fixed in 3.7. Any chance the 3.6 will get a patch for this?

**Comment by NathanSweet** [comment]
You'd only need the extension if you have another image with the same name, but different extension. In that case I'd suggest renaming one of the images.

Unfortunately we don't currently have plans to backport the fix into 3.6, sorry. Despite appearances, the fix involves attachment loading and is actually a bit involved. It's riskier than we like for fixes applied to a stable, non-beta version.

**Comment by chronszcz** [comment]
I need the extension so exporting to json has the full path. Maybe I will use 3.7 then instead. Thanks for your time!

**Comment by NathanSweet** [comment]
No problem. Likely all your images are PNG, so you could avoid extensions everywhere, then append ".png" at runtime (or wherever you use the JSON).

FWIW, JSON exports from 3.7 should be fine to use with 3.6 runtimes. Binary exports probably are not, since binary is extremely sensitive to changes.
