### ISSUE TITLE
Define viewport for image and video export

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#334]
**Actual behavior:**
On image and video export Spine wraps the single animation and this defines the output proportions, different animations may have different proportions making sprite-sheet creation difficult.

**New suggested behavior:**

- [ ] Viewport could be specified by a bounding box (or clipping box?) and animatable (probably in its position but not its proportions)
- [ ] Viewport could be specified on export, maybe with a numeric entry to choose e.g. a size like 1280x720 (possible problem: how to remember the position of the export if one exports many videos or animations?)  

As stated by indiumindeed:
> There should be an option to crop the video to the specified resolution of a specific location.

**Similar to:**
https://github.com/EsotericSoftware/spine-editor/issues/11

>Allow a size to be specified so image sequences use the same world origin http://esotericsoftware.com/forum/Pivot-Problem-On-Export-Sequence-Anim-5585 Alternatively, provide the ability to set (and animate) a viewport rectangle which is used for image/video export. http://esotericsoftware.com/forum/viewtopic.php?f=3&t=262

**Comment by NathanSweet** [comment]
Functionality provided by the new export dialog in 3.7.20-beta.
