### ISSUE TITLE
Width and length are set to 0 if skeleton is not visible on export

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#335]
**Repro steps:**
1. open repro project Elements2 from mail 1625cc68e6e23573
2. Ctrl+E to export, (export to the export folder in the project, it doesn't matter)
[Nb: select json export, the export had Nonessential data, pretty print and atlas all active. but whatever setting still outputs the same problem so it doesn't matter.]
> Width and length of the skeleton in the JSON file are 0

**How to resolve the problem:**
1. make all skeletons visible
2. **SAVE** the project (important, or else it won't work)
3. export
> Width and length of the skeleton in the JSON file are fine.

My guess is Spine takes into account the visibility of a skeleton the last time this was saved instead of it on export. But it should be independent of skeleton visibility.

**Comment by NathanSweet** [comment]
3.7.43-beta
