### ISSUE TITLE
Export gif missing images on some frames

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#337]
**Expected behavior:**
Exporting at whatever frame rate should be able to avoid images to be missing for a couple frames.

**Actual behavior:**
Some of the frames display a Missing image png instead of the actual attachments.

**Mail with repro project:**
162a29d0905b3a7b

**Repro:**
1. Download project attached in the mail (nb insert the .Spine in the images folder)
2. Ctrl+E and select gif export. You should see weird settings like Repeat `2` and Fps `31`
> The export will result in a glitch where the images go missing for a frame
But changing the frame rate back to 30 and repeat to 0 still reproduces the bug.

**Solution:**
Moving the images into a dedicated "Images" folder, and relinking the images of the Spine file so that the Spine file is not among the images allows the gif or video to be exported correctly.

[Related Forum Thread](http://esotericsoftware.com/forum/Export-Missing-Image-Glitch-10175)

**Comment by NathanSweet** [comment]
3.7.16-beta

**Comment by zephyo** [comment]
Still encountering this issue

**Comment by zephyo** [comment]
Solution is not working for me.
