### ISSUE TITLE
Weight locking

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#338]
Add the possibility to lock some bones from the Weight panel list so that they won't be influenced by editing.

See related forum post:
http://esotericsoftware.com/forum/weight-influence-locks-10209

**Comment by erikari** [comment]
An interesting take on this is here: http://esotericsoftware.com/forum/want-to-add-something-Weights-tool-Transform-Constraints-11798

**Comment by erikari** [comment]
A +1 here: http://esotericsoftware.com/forum/Lock-bone-weight-options-12352?p=55072#p55072

**Comment by FabianoIlCapo** [comment]
A +1 from me as well!!

**Comment by RahulAnim** [comment]
A +1 from me as well!!

**Comment by Fainder86** [comment]
big +1!

**Comment by erikari** [comment]
Another +1 here http://esotericsoftware.com/forum/Lock-a-bone-s-weights-in-specific-percent-16165

**Comment by NathanSweet** [comment]
In 4.1.16-beta!
