### ISSUE TITLE
Control X and Y separately with a transform constraint

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#342]
As a user on the [forum](http://esotericsoftware.com/forum/viewtopic.php?f=11&t=10226&p=46170#p46170) suggested, having X and Y axis as separate values would allow better control.

Possible UI:
![image](http://esotericsoftware.com/forum/download/file.php?id=4287&sid=ff2b1f3fedeb6a2c78472f3caeb46a6a)

**Comment by Monkeyzav** [comment]
A huge yes! Right now in some ways, either we can't use the constraint at all (because we need it to constraint horizontally, not vertically for example), or we have to do some compensations.

**Comment by iAqu** [comment]
agree

**Comment by supersaiyansubtlety** [comment]
One more yes vote

**Comment by erikari** [comment]
A +1 from this thread: http://esotericsoftware.com/forum/Any-way-for-bone-to-inherit-constrain-to-X-translation-only-11426

**Comment by emjaykidd** [comment]
Chiming in a +1 here as well! Would be excellent for ensuring a simplistic ground shadow always tracks side to side with the core of the body's motion (besides plenty of more creative uses, I'm sure).

**Comment by djmisterjon** [comment]
also need to found a way to unlock the limit , or add a multiplication .
The slider is easy and fun , but have limitation :)

**Comment by WArmanW** [comment]
+1 on this..  
I see ready labels. does that mean we get it soon?

**Comment by ArtJimp** [comment]
Would love to see this feature added soon!

**Comment by NathanSweet** [comment]
4.0.26-beta
