### ISSUE TITLE
You can tab out of a modal window through textboxes.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#346]
![2018-04-24_10-42-24](https://user-images.githubusercontent.com/1911082/39180532-b93b1e54-47e9-11e8-990c-2d4136b326d9.gif)

Repro:
1. New Project
2. Spine > Export. (or `CTRL`+`E`)
3. Click on any textbox to focus on it.
4. Repeatedly press `Tab`.

Bug - It will also cycle through textboxes outside of the export window.
This can be reproed in other "modal" windows. (ie, windows you can't click out of without pressing cancel or escape)

Original user report : http://esotericsoftware.com/forum/Tab-to-change-parameter-10258

**Comment by NathanSweet** [comment]
3.7.16-beta
