### ISSUE TITLE
Click and drag over projection line in path creation mode freezes Spine

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#349]
**Repro steps:**
1. Create new project
2. Select root
3. New>Path
4. **Press** to create a point that goes **over the infinite line**, **drag** to make it over it, release
![user image slowed down](https://media.giphy.com/media/dtVtP0R4h6lTViyVwl/giphy.gif)
> NB: tested 50 times, it works every time. It's not a problem if you just click, but if you click on the line and drag, Spine freezes, 100% guaranteed.

**Reference post:**
http://esotericsoftware.com/forum/viewtopic.php?f=9&t=9885&p=46295#p46295
> It happens when I drag drop a point, not when I just click to create one.
> Spine freeze to death.

**Comment by pharan** [comment]
This bug looks familiar. I think I opened a similar issue a few months ago.

**Comment by pharan** [comment]
https://github.com/EsotericSoftware/spine-editor/issues/320

I have a couple of video links there.

**Comment by erikari** [comment]
Oh you're right it's the same! >.<

**Comment by NathanSweet** [comment]
3.7.16-beta

**Comment by pharan** [comment]
Where is 3.7.16?

**Comment by NathanSweet** [comment]
Release is before EOD CET May 7th.
