### ISSUE TITLE
Preview tracks always active

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#350]
**Repro steps:**
1. open a project (e.g. Spineboy-mesh)
2. in the preview panel set an animation on track 0, track, 1, track 2 (it can be the same)
3. open a different SPine project (e.g. Vine, Goblins, doesn't matter)
> even though no animation is playing at all, the tracks will be marked in orange.
![image](https://image.prntscr.com/image/UIoH808rSd6Zz2Lpjv8y_g.png)
> doesn't happen if Spine is restarted.

**Reference forum post:**
http://esotericsoftware.com/forum/Preview-tracks-always-activated-10265?p=46314#p46314

**Comment by NathanSweet** [comment]
3.7.16-beta
