### ISSUE TITLE
Setting to use middle click for panning

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#357]
Some people are used to using middle click.

**Comment by NathanSweet** [comment]
Setting added in 3.7.75-beta+, but it's too late to add it to the UI. Until then, you can use it by opening your prefs.json:

Windows: <user home folder>\Spine\prefs.json
Mac: <user home folder>/Library/Application Support/Spine/prefs.json
Linux: <user home folder>/.spine/prefs.json

Add `mouseMiddlePans:true,` just after the opening brace (`{`). Eg, from this:
```
{version:<snipped>
```
To this:
```
{mouseMiddlePans:true,version:<snipped>
```
We'll add it to the settings dialog in 3.8.

**Comment by SamMacedo** [comment]
Adding `{mouseMiddlePans:true,` as suggested doesn't seem to work for me, once I open Spine the setting gets automatically removed from the **prefs.json** file.

OS: Windows 10
Spine version: 3.8.69 Professional

**Comment by NathanSweet** [comment]
@SamMacedo The setting needs to be added in the `advanced` section. Eg:
```
{version: 7, ..., advanced: {mouseMiddlePans: true, ...}}
```
Sorry the above information was wrong!

This issue was missed for 3.9, so I will mark it for 3.9.

**Comment by SamMacedo** [comment]
@NathanSweet Adding it inside the `advanced` section worked, thank you!

**Comment by NathanSweet** [comment]
4.0.00-beta
