### ISSUE TITLE
Add Krita export script

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#358]
http://esotericsoftware.com/forum/Krita-export-plugin-10507

**Comment by mangojambo** [comment]
Hello. Is there a schedule, foreknowledge when this will be implemented? I'm no linux user, but I'm not Adobe user as well. Unity give us a great deal supporting open plataforms, like Blender instead Autodesk only, so we can spend money on Unity only and still have a full workflow. Would be great to have Krita in the alignment with Spine. Cheerios.

**Comment by bencresty** [comment]
Isn't this request something more suitable for Krita developers instead? Just like Affinity Designer also created their Spine export script. Than Spine developers could focus on handling Spine?
