### ISSUE TITLE
Create bone on the upper edge of the Spine window

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#359]
It is possible to create bones in the upper edge. When focusing/unfocusing the window it's therefore possible to accidentally create bones without seeing them.

Repro:
1. select create tool
2. move the mouse to the upper border
3. click

Repro image:
![](https://image.prntscr.com/image/kVRWo1P4QP_U2pfARQFPGg.png)

**Comment by pharan** [comment]
I really can't repro in 3.7.19.
I tried different sizes and positions for the window, and also maximized and fullscreened too.

**Comment by erikari** [comment]
Nevermind, I was on an old Spine version for testing today, on the new one the problem is gone. Good job Nate!
