### ISSUE TITLE
Allow dragging bones, slots, and attachments between skeletons

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#36]
http://esotericsoftware.com/forum/Transfer-bones-from-a-skeleton-to-another-6655

http://esotericsoftware.com/forum/Skeleton-Merger-Tool-5070

**Comment by Xelnath** [comment]
+1 Awesome idea.

**Comment by kanevsky** [comment]
i was waiting for this from the beginning! Love you guys!

**Comment by macguffin** [comment]
+1 would love to see this, is it still a possibility for 3.6?

**Comment by hyf042** [comment]
+1 We are looking forward to this feature!

**Comment by jimmymjing** [comment]
+1 We also desperately need this feature! Really looking forward to have this in 3.6!

**Comment by evanrosenbaum** [comment]
@NathanSweet do you have an ETA on when this issue will be ready in the next 3.6 beta? Need it for an ongoing project.

**Comment by NathanSweet** [comment]
Can't give an ETA, sorry, but it is in progress.

**Comment by evanrosenbaum** [comment]
Could we try an early version of it? We are working on a big project in Spine and have many licenses.

**Comment by NathanSweet** [comment]
As soon as it is working, it will be in the beta releases. It's at the top of our list, should be soon.

**Comment by mariuspena** [comment]
we want this asap +1 thank you guys!

**Comment by anelle** [comment]
yeeesss need this badly! +1

**Comment by NathanSweet** [comment]
3.6.19-beta
