### ISSUE TITLE
If no animations are present in Animations view, "New Animation" button doesn't work

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#361]
**Repro steps:**
1. open Spineboy
2. go to Animate mode
3. select all the animations and delete them from the tree
4. open Animations view
5. in the Animations view, try to click the New Animation button
> nothing happens
But if animations are present, a new animation will be created.

[Link to forum thread](http://esotericsoftware.com/forum/3-7-19-beta-last-animation-deleted-issue-10603)

**Comment by NathanSweet** [comment]
3.7.24-beta
