### ISSUE TITLE
packing error

### ISSUE THREAD

**Issue by soulpoint** [EsotericSoftware/spine-editor#363]
Error: String index out of range: -1

**Comment by soulpoint** [comment]
![ertett.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b6a5e3a11fde6001163e274/125516c66e82c728ace21e0d46ed868e269697ebc3abaf51ab57f5973d047d317c5cf3297186e77fea4622535b0e4ef941585d42adfd8b2ab4aa2e32db025fb28c341521842f1bbeb98b15be04b9238d468dbeb88e44c0ed2f68.PNG)

**Comment by soulpoint** [comment]
Image can not be wrapped because it can not be packed Thank you for your support.

**Comment by soulpoint** [comment]
from spine 3.7.21

**Comment by NathanSweet** [comment]
Thanks for the report, and sorry for the delay. How can we reproduce this problem? I can run the [examples export script](https://github.com/EsotericSoftware/spine-runtimes/blob/3.6/examples/export/export.sh) without any errors, and exports JSON, binary, and packs many atlases. Can you please provide images and texture packer settings (screenshot or save the packer settings as JSON)? Or if you can get the error to occur when packing one of the example project images, maybe we just need your specific texture packing settings to see the error.

**Comment by NathanSweet** [comment]
Ah, I see you emailed with your spine.log file. That was helpful, thanks. Turns out it was a problem unrelated to the texture packing. We have fixed it in 3.7.23-beta. Cheers!
