### ISSUE TITLE
Tint black not working if attachment has Color

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#364]
**Repro steps:**
1. select an attachment and set the color to black
2. select the slot of the attachment, activate tint black, set both colors to white
> resulting color is black
If no attachment color is set, the attachment will become completely white.

**Desired behavior:**
The attachment should become white no matter what color was set for the attachment.
Attachment color is often used to differentiate skins as slot color is applied across all of them.

**Comment by NathanSweet** [comment]
Colors are multiplied, so as soon as you set the attachment R, G, or B to black, then no amount of multiplying can bring back the original color.

Your proposal:
> The attachment should become white no matter what color was set for the attachment.
Why would it be white? In other words, why would the attachment color be discarded? Consider it isn't a problem just with black -- if the attachment color was green (RGBA 00FF00FF) the red and blue is gone.

I understand the use case, using attachment color for skins and then wanting to tint the whatever attachment comes from the current skin using a slot, however the way colors are combined manipulatively gives the current behavior. Unless there are suggestions for alternative ways of combining colors, I don't know what else we can do.

**Comment by NathanSweet** [comment]
Can reopen if there are ideas on how to improve this.
