### ISSUE TITLE
Allow multi-editing for attachment color.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#368]
A few users report needing to set the colors of a large number of attachments (not slots) in Spine editor. But because they can't be multi-edited, they had to set the color one by one.

It would be useful if they could set multiple attachment colors by selecting multiple attachments and then setting the color once.

An unrelated post was necroed for this request: http://esotericsoftware.com/forum/Tint-Black-in-Region-Attachment-9995?p=48007#p48007

**Comment by erikari** [comment]
another +1 here: http://esotericsoftware.com/forum/Any-way-to-change-color-of-multiple-attachments-at-once-10737?p=48334#p48334

**Comment by NathanSweet** [comment]
3.7.26-beta
