### ISSUE TITLE
[3.7.23 GIF export] Strange flicker, and nonvisible parts of path are incorrectly included.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#370]
Exported a gif using 3.7.23-beta.

![stretchyman-pro-sneak](https://user-images.githubusercontent.com/1911082/44109334-5c1f044e-a02f-11e8-9567-9423a69e96c8.gif)

- [x] 1. FLICKER. What's that weird flicker at the end of the loop?
non-transparent background: #2f2f2f. (transparent bg doesn't exhibit this problem)
scale doesn't seem to matter (tested 50%, 100%)
framerate doesn't seem to matter (tested 50, 33, 25)

I opened it in Photoshop. The last frame looks like this:
![image](https://user-images.githubusercontent.com/1911082/44109782-7bd93a4c-a030-11e8-8e70-5049ee1b25be.png)

- [ ] 2. CROP TOO TALL. This was exported with `Render: Other` enabled.
I suspect invisible points of paths (the tangents) seem to be included in the auto-calculation of the crop, even if they're not actually visible in the export. But I checked the paths and I'm not even sure those points exist. If they do, they're not editable or visible to the user.

![image](https://user-images.githubusercontent.com/1911082/44109996-19440938-a031-11e8-98e7-9a939a9ac971.png)

So I could totally be wrong.

**Comment by NathanSweet** [comment]
3.7.30-beta

**Comment by NathanSweet** [comment]
You can see why the bug adds extra space if you make the paths closed:
![](http://n4te.com/x/4861-iiR3.png)
