### ISSUE TITLE
[3.7.24 MOV export] Default Scale is 1. Should be 100.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#372]
Here are the default settings when I try to export MOV from spineboy-pro for the first time:
![image](https://user-images.githubusercontent.com/1911082/44228849-e908cf80-a1c8-11e8-89dd-457e9d288e1d.png)

Notice the Scale is 1 instead of 100.
I would've thought it was normal, but scale doesn't show units. 😛

**Comment by NathanSweet** [comment]
Woopsie! Fixed in 3.7.25-beta.
