### ISSUE TITLE
[3.7.24] Selecting an event causes "unsaved" state.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#373]
0. Open Spine.
1. Open spineboy-pro.
2. Expand the Events node in the Tree.
3. Select the "footstep" event. Don't change anything.
4. Close Spine.

Step 3 causes the title to say "*spineboy-pro" despite not actually changing anything.
![image](https://user-images.githubusercontent.com/1911082/44302417-a414a280-a35a-11e8-8752-4e3156eb9edd.png)

Step 4 causes the "unsaved changes" dialog to appear.
![image](https://user-images.githubusercontent.com/1911082/44302413-83e4e380-a35a-11e8-97b4-1fdb69759a66.png)

**Comment by NathanSweet** [comment]
3.7.29-beta
