### ISSUE TITLE
Importing a project into another makes the second use the images path of the first

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#377]
Repro steps on thread discussion here: http://esotericsoftware.com/forum/Import-project-path-folder-problems-10726

**Comment by NathanSweet** [comment]
Both projects use `./images` as their images path, relative to the project file. When imported into a project in a different location, naturally this relative path finds a different folder. We should adjust the path so it continues to point at the previous images folder (audio too).

**Comment by NathanSweet** [comment]
3.7.31-beta
