### ISSUE TITLE
shear not taken into account on json import

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#378]
**Repro steps:**
1. open `raptor.spine`
2. select the hips bone
3. shear the hips bone
4. export json (atlas unchecked, no pretty print, but nonessential data checked)
5. create new project
6. import json
> the shear is completely absent

**Reference thread:** http://esotericsoftware.com/forum/Import-data-issue-with-folder-path-10658

**Comment by NathanSweet** [comment]
3.7.29-beta
