### ISSUE TITLE
Photoshop script improvements

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#380]
- [x] Names validation could loop till the end and tell all the issues instead of showing them one by one. 
- [x] When there is a dot in the name of a layer, the exported file will truncate the layer name/(export without the file extension <-unverified yet) therefore not exporting different layers that varied on the name after the full stop
- [x] Export progress keeps stealing focus, suggestion is to make it gain focus only once at the beginning and then on export complete
- [x] The script appears to be merging several layers on the same file

Reference thread:
http://esotericsoftware.com/forum/Export-to-Photoshop-script-bugs-10752

**Comment by NathanSweet** [comment]
All these are fixed as of script version 3.3.
