### ISSUE TITLE
Attachments flip when parenting with negative scale

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#382]
How do you fix a skeleton facing the wrong direction?
This is especially important considering a negative root seems to cause (inevitably?) weird behavior when using world axes in the editor.

Use case:
http://esotericsoftware.com/forum/Images-flipping-when-parenting-10790

**Comment by NathanSweet** [comment]
Simple, you don't rig it facing the wrong way. :p Negative root scale is fine. You could also rig it facing one way and flip it at runtime, which has the benefit that it will flip even bones which disallow scale inheritance.

An attachment flipping when parenting with negative scale is an issue.

**Comment by NathanSweet** [comment]
3.7.35-beta
