### ISSUE TITLE
Retina support on OS X

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#389]
Ideally we always have a 1:1 mapping of pixels:points. This way we should not have to worry about monitor DPI changes -- Spine renders in pixels and the size of Spine's rendering is controlled via the `interface scale` setting.

**Comment by plamenterziev** [comment]
As 13-inch MacBookPro user I'd be very happy to see this implemented because right now the editor looks very ugly on my Retina display.

**Comment by NathanSweet** [comment]
It's in 3.8.34-beta! @badlogic you get to do the honors!
