### ISSUE TITLE
downgrading Spine causes Weights panel sliders to disappear

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#395]
First, it's been months I've been trying to get this bug to repro. I finally succeeded.

**What happens?**
This slider disappears and there's no way to make it reappear unless you restart Spine.

![bug](https://image.prntscr.com/image/KVaXL3dQRa2JLeCCeTcMaQ.png)

**Repro steps:**
1. on stable, go to settings and enable beta.
2. restart spine.
3. disable beta from settings
4. restart spine
5. if spineboy project pro opens, select his hair or any mesh
6. select weights tool so that the weights panel opens
> bug happens

**Repro gif:**
![gif](https://media.giphy.com/media/3Fewf5iGazsWntgLj8/giphy.gif)

**Comment by NathanSweet** [comment]
I expect this is a bug in 3.6. We miiight do one last 3.6 release for this a OS X file dialogs when using the latest launcher. Then again, moving to 3.7 is pretty easy for 3.6 users, and 3.7 is almost out of beta.

**Comment by NathanSweet** [comment]
I think it's better not to risk disrupting 3.6 users with a new 3.6 release after so much time. Better that people move to 3.7, which is out of beta in a week or so.
