### ISSUE TITLE
Auto Key requires an extra Undo Step when using Scale to deform

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#397]
in 3.7.51-beta an extra undo press is required when you have `Auto Key` enabled and set deform keys using Scale. The expected behavior is to only have a single undo press even with `Auto Key` on.

Reproduction.
1. In raptor-pro project, go to Animate mode.
2. enable Auto key.
3. select vertices on the mesh of the body and use Scale to set deform keys.
4. Undo your deform keys. Note you will need to press undo twice.

Disabling `Auto Key` before setting a deform key, gets the right behavior. As does using translate or rotation.

**Comment by NathanSweet** [comment]
3.7.52-beta
