### ISSUE TITLE
Prune showing wrong amount weights removed in vine project

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#400]
**Reproduction**
1. Open vine-pro project
2. Select `vine`mesh.
3. In `Weights` dialog, click `Prune`. Dialog should say `222 weights removed`. 
![](https://i.imgur.com/toTGcNw.png)
4. Change `Threshold` and set it back to the default `5.5`again. Dialog should now say `13 weights removed` despite being the same settings as in step 3.
![](https://i.imgur.com/qkKDJ3h.png)

**Comment by NathanSweet** [comment]
3.7.58-beta

**Comment by Shiu** [comment]
Should this issue be reopened? bug is still there in 3.7.59-beta

**Comment by NathanSweet** [comment]
Nah, fixed in 3.7.60-beta.
