### ISSUE TITLE
Background type Dots causes world origin lines to move when changing background color

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#404]
*Reproduction*
1. Open Spine Settings.
2. Set `Background type` to `Dots`. Size doesn't matter.
3. Open `Background color` dialog.
4. Move the alpha slider all the way to the top, setting alpha to `FF`. 
Note how the  world coordinate 0,0 lines move by one pixel. Moving the slider up and down around `FF` will repeat the error.

**Comment by Shiu** [comment]
moving to public issue tracker.. sorry!

**Comment by NathanSweet** [comment]
3.7.63-beta
