### ISSUE TITLE
Export gif freezes/fails to export when multiple skins are selected

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#411]
Exporting a skeleton with many skins can be very slow. The project in the mail can be used to optimize such a case.

**Ref mail and project:**
FMfcgxvzMBnzrLbfTwgzcGfJKjcjMQbf

**Steps:**
1. Open project
2. Press Ctrl+E
3. Choose gif export
4. Choose skins: All
> Editor freezes (probably creating the preview)
If you wait long enough, it will eventually unfreeze. 
5. All the other options are as default, but FPS are set to 30. choose an export location
6. export 
> as I write, it has been stuck at 0% for half an hour already

PS. if a PSD is exported, it will fail to be opened by Photoshop.

**Comment by NathanSweet** [comment]
The project has 26,263 attachments, which itself is a bad idea. Probably they should have [created attachments at runtime](http://esotericsoftware.com/spine-runtime-skins#Creating-attachments). Still, we made some improvements for loading projects like this. Opening the project used to take 5.7 seconds, now it opens in 0.6 seconds!

Next there are 118 animations and 130 skins. Choosing to export all animations for all skins is 449,933 frames and just calculating the frame sizes will take a long time, so clearly we need some way of limiting the preview so it doesn't freeze the app. We ended up limiting it by time in 3.7.75-beta -- if it takes longer than 500ms to prepare the preview, the preview will not show (it will say "Too large for preview."). Preparation means to count the frames and pose the animation for every frame to get the max size (which is done even when the preview pane is hidden). It does not include rendering the preview frame, which is not time limited. Posing the skeleton for each animation frame involves updating the attachments, so having 26k+ attachments causes this to take extra long.

This change only prevents preview from freezing Spine. If you are exporting so many frames, you will likely wait a long time for it to finish and the resulting file may be too large to be opened by other programs. Nothing we can do there.
