### ISSUE TITLE
Add bones to existing "Bones" list under constraints

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#419]
Currently if you want to edit the list of bones affected by a constraint, you have to add all bones again.
This is a slow workflow which could be improved by adding/subtracting from the list instead of clearing it every time it is edited.

http://esotericsoftware.com/forum/Add-extra-bone-to-already-exisiting-constraint-11304

**Comment by erikari** [comment]
a +1 here: http://esotericsoftware.com/forum/Quick-select-all-child-bone-of-a-transform-constraint-16220

With the additional request of the ability to select all of the bones in the constrained list:
> why cant we mass select all of them?

**Comment by misaki-eymard** [comment]
+1 here: https://esotericsoftware.com/forum/d/25456-transform-constrain-add-a-new-bone-instead-of-reselect-all-of-them

**Comment by NathanSweet** [comment]
4.2.60-beta
