### ISSUE TITLE
Translate example labels

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#421]
The text "Spine version" and "Tags" is not translated on the example pages. We need to change the HTML and modify each example page with the translations below.

## Japanese
Spine version: Spineバージョン
Tags: タグ
- [x] windmill
- [x] alien
- [x] coin
- [x] dragon
- [x] powerup
- [x] raptor
- [x] spineboy
- [x] stretchyman
- [x] tank

## Chinese
Spine version: Spine版本
Tags: 标签
- [x] windmill
- [x] alien
- [x] coin
- [x] dragon
- [x] powerup
- [x] raptor
- [x] spineboy
- [x] stretchyman
- [x] tank

## Korean
_The Korean translation is in progress, so this section has to wait until it is ready. It's too late to change the text to be translated._
Spine version: Spine 버전
Tags: 태그
- [x] windmill
- [x] alien
- [x] coin
- [x] dragon
- [x] powerup
- [x] raptor
- [x] spineboy
- [x] stretchyman
- [x] tank

**Comment by Shiu** [comment]
I've removed `Tags` and `Spine version:` temporarily from the Korean pages (this was done automatically when I removed the CSS that rendered the text). 
Will add Korean version as soon as we get them
