### ISSUE TITLE
RegEx in find and replace hides some results from the list when using specific character

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#423]
**Description of the problem:**
When  `_` is typed, some of the bones are hidden from the Find and replace window, but still get affected by it.

**Steps:**
1. Have bones such as these in a project:
![](http://www.erikari.it/uploads/33-WD3s.png)

> Attempt to replace their names so that they all get the same name but different number: 
2. Open Find and Replace, enable Regular Expression, 
Find: `mustache(.*)_(.*)`
Replace: `mustache_$2`
 ![](http://www.erikari.it/uploads/34-VbYD.png)

> `mustache_3` is missing from the list
3. Click replace, `mustache_3` gets replaced too (as it would be expected, despite not being shown in the list earlier):
![](http://www.erikari.it/uploads/35-Kk22.png)

3.This does not happen if instead of `_` we use `-`
![](http://www.erikari.it/uploads/36-8Pj0.png)

By the way the result using `-` is still correct:
![](http://www.erikari.it/uploads/37-b9K6.png)

Why is the `_` problematic and makes some results hidden?

**Repro project:**
[Download project](http://www.erikari.it/uploads/38-mustache.spine)

**Comment by erikari** [comment]
![screenshot_10](https://user-images.githubusercontent.com/29667068/51043033-f9797680-15bd-11e9-8097-5aedc96ace2d.png)
The group is captured correctly, also according to the above screenshot.

I tried the characters you suggested in Spine's Find and Replace window, and they don't seem to work the slightest.

In fact, I was (am) convinced only the below syntax would work:
![immagine](https://user-images.githubusercontent.com/29667068/51043108-275ebb00-15be-11e9-98ce-540ffd925912.png)

Do you confirm the suggested characters _should_ work in that window?

**Comment by NathanSweet** [comment]
All regex works.

Did you check first occurrence?

**Comment by erikari** [comment]
I did, I still only see results when I use the characters suggested in the box above, and not the ones you suggest, unfortunately.

**Comment by NathanSweet** [comment]
You did replace the x with the characters you are trying to find (_),
right?

**Comment by NathanSweet** [comment]
Responding to the first post in this issue, ignoring the rest. `mustache_3` is matched and replaced by the regex `mustache(.*)_(.*)`, but the replacement is `mustache_3` -- the same as we started with. Since the name does not change, it is not shown in the replacement preview. Eg, if you find `(.*)` and replace with `$1`, nothing changes so nothing is shown in the preview.

FWIW, this is probably a better regex: `mustache_(.+)_(.+)`
The result is the same, but it's less likely to match things you don't want it to match.
