### ISSUE TITLE
Exporting with whitespace stripping gives "Error: (x + width) is outside of raster"

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#425]
As per title, it is unclear why an error is output and no atlas and png are generated when whitespace stripping is enabled, while everything exports normally when disabled.

**Repro steps:**
1. open repro file
2. open export window for binary file
3. enable whitespace stripping on x and y
4. export
> "Error: (x + width) is outside of raster"
If whitespace stripping is disables, it will export as it should.

**Repro mail:**
FMfcgxwBVDMBQQbzmtkgNZFDWpKFNpMR

**Comment by erikari** [comment]
Possibly related: http://esotericsoftware.com/forum/Scaling-strip-whitespace-doesn-t-work-in-3-7-81-11402

**Comment by NathanSweet** [comment]
Turns out this only occurred when using a texture packer scale != 1. Fixed in 3.7.88!
