### ISSUE TITLE
Dropdown list for selecting which skeleton is displayed in the Dopesheet

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#426]
User reports that the new way of choosing which skeleton keys are visible in the dopesheet slows down their workflow.

See http://esotericsoftware.com/forum/Spine-3-7-released-11309?p=51053#p51053 for suggestion on how this could be improved.

Summarized: User would like to be able to select which Skeleton is visible in the dopesheet by using a dropdown list

**Comment by NathanSweet** [comment]
3.7.89 (details in forum thread)
