### ISSUE TITLE
Tooltip for Maximize/Restore Down always displays "Maximize"

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#427]
*Reproduction*
1. Open Spine
2. Click Maximize
3. Hover cursor over maximize button to show tooltip. 
Tooltip will always display "Maximize".

*Expected*
When Spine is maximized, the tooltip should read `Restore Down` if we want to stick with Windows system standard.

**Comment by NathanSweet** [comment]
3.8.00
