### ISSUE TITLE
Make Spine remember the last used setting on bone split

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#428]
For example, nested is used 90% of the time, but it is deselected by default.

forum thread:
http://esotericsoftware.com/forum/Export-to-GIF-doesn-t-ignore-images-with-export-unchecked-11406

**Comment by NathanSweet** [comment]
Agreed though FWIW, I prefer non-nested when the bones will be constrained to a path.

**Comment by erikari** [comment]
The fact is that un-nesting is easy, you select all the children bone, press P, parent them to the first bone.
Parenting manually each bone is more tedious.

**Comment by NathanSweet** [comment]
While that is true, I don't see how it is relevant to this issue. You'd never use the wrong split setting, then fix it up manually.

**Comment by NathanSweet** [comment]
3.7.89
