### ISSUE TITLE
Attachments with export unchecked still appear in image and video exports

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#429]
The Export checkbox of a region property is not taken into account on GIF exports, 
When unselected, the region will still be visible.

Many times this is not a problem, but with some reference images left active, it would be nice if it was possible to have Spine respect it. (I suggest adding a checkbox)

Reference thread:
http://esotericsoftware.com/forum/Export-to-GIF-doesn-t-ignore-images-with-export-unchecked-11406

**Comment by NathanSweet** [comment]
3.7.90
