### ISSUE TITLE
Vertex copy creates weird geometry on pasted mesh

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#430]
**Repro steps:**
1. open `square-bug1.spine`
2. Select local axes
3. Select all the vertices of the red shape and copy them
4. Select all the vertices of the yellow shape in the exact same order and paste them
You should get the same result of `square-bug2.spine`

**Repro file:**
https://www.erikari.it/uploads/55-square-bug.zip

![bug](https://www.erikari.it/uploads/54-HlXP.png)

**Comment by NathanSweet** [comment]
The triangulation of the meshes is very different. The red mesh's triangulation:
![](http://n4te.com/x/6448-7muH.png)

The yellow mesh's triangulation:
![](http://n4te.com/x/6449-4WNH.png)

Copy/paste of vertex positions places the vertices as expected. Even if you move the vertices with the translate tool, you get the same result. How a mesh deforms is dependent on its triangulation.
