### ISSUE TITLE
How I can open or edit .skel.bytes?

### ISSUE THREAD

**Issue by XenonKusanagi** [EsotericSoftware/spine-editor#431]
Hello, I am new to this, I have obtained the files of a Mobile game called KOF ALL Stars and extracted the spine files from the game, and I generate several files, including the extension ".skel.bytes", ".atlas" and ". png. " And other files that I show below:
![image](https://user-images.githubusercontent.com/45806359/51651285-f03ec100-1f50-11e9-96e0-07d037a4c509.png)

![image](https://user-images.githubusercontent.com/45806359/51651273-e4eb9580-1f50-11e9-9728-48b765510520.png)

![image](https://user-images.githubusercontent.com/45806359/51651296-fc2a8300-1f50-11e9-8c75-90195f8a91a5.png)

 I know that these files open in Spine but when I open the file ".skel.bytes" I get an error that the file was not recognized, I would like to know why this error occurs, I have the latest version of spine and I would like to know if someone could help me, here is the complete folder that I generated. Greetings.

[Kulita.zip](https://github.com/EsotericSoftware/spine-editor/files/2790013/Kulita.zip)

**Comment by NathanSweet** [comment]
Hello, would you please post your question on the Spine forum? The is an issue tracker, meant for reporting problems and tracking our work tasks. The forum is a better place for a discussion like this. Thank you! Cheers!
