### ISSUE TITLE
Increase zoom out amount or add setting to specify min/max

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#432]
User requests additional zoom out levels for large assets or large sprawling scenes.

http://esotericsoftware.com/forum/Maximum-Viewport-Zoom-11416

Maybe this issue could be combined with https://github.com/EsotericSoftware/spine-editor/issues/413

**Comment by NathanSweet** [comment]
Increasing bone size increases zoom out limit. If user still has an issue, please reopen.
