### ISSUE TITLE
Incorrect gif export

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#433]
Reference thread:
http://esotericsoftware.com/forum/viewtopic.php?f=9&t=11427&p=51365

Steps:
1. Download the project from the thread's first post, unzip and open
2. Make sure the `empty` animation is selected
3. Ctrl+E and export a gif. This is also visible in the preview of the export panel. The tail does not move

If on 2. you select the `animation` animation, everything will be exported correctly.

**Comment by NathanSweet** [comment]
3.7.89
