### ISSUE TITLE
CLI missing output path

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#434]
in v3.7.81 CLI doesn't recognize "output" in the json file, giving this error: 
> ERROR: Missing output path.

This happens both on Mac and Windows.

**Reference thread, and example json:**
http://esotericsoftware.com/forum/ERROR-Missing-output-path-when-exporting-from-command-line-11425

**Comment by erikari** [comment]
Possibly related problem in the Spine texture packer:

**Error:**
![error](https://www.erikari.it/uploads/90-88ox.png)

**Reference mail with steps:**
FMfcgxwBVWQNQRkGqdBLCDfxdjkzQdnL

**Repro project:**
[Download modified Spinosaurus](https://www.erikari.it/uploads/91-spinosaurus.zip)

**Comment by NathanSweet** [comment]
3.7.88

**Comment by jeremyfa** [comment]
Still having the same issue (CLI) with latest launcher and update I could download (**launcher 3.7.82 + version 3.7.89**). Still works with **launcher 3.7.82 + version 3.6.53**.

**Comment by NathanSweet** [comment]
@jeremyfa To be clear, you see the `Missing output path.` problem with 3.7.89? Note erikari's second post in this issue is a separate problem from the first. Both have been fixed though, and I just verified they are indeed fixed with launcher 3.7.82 and editor 3.7.89. Can you please post or email your export settings JSON and the console log after trying to export?  contact@esotericsoftware.com

**Comment by jeremyfa** [comment]
Yes, I am talking about the ``Missing output path`` error on CLI. At the moment I can't export with spine 3.7+ from command line.

The export settings I use, and the console logs are the one I provided on this topic: http://fr.esotericsoftware.com/forum/ERROR-Missing-output-path-when-exporting-from-command-line-11425

The output is still exactly the same after having updated to launcher 3.7.82 and editor 3.7.89

For reference, these are my current settings when I check in the spine editor:
<img width="493" alt="capture d ecran 2019-02-12 a 12 29 49" src="https://user-images.githubusercontent.com/164094/52637542-c33a5a00-2ecf-11e9-8422-0dd393d14a36.png">

**Comment by NathanSweet** [comment]
Aha, you are right of course. Sorry for the confusion, I see it now. There is actually a new and old export settings format. Both should work just fine, but the old one has a problem. We've fixed it in 3.7.90!

**Comment by jeremyfa** [comment]
Ah I see thanks, cannot download 3.7.90 yet but I guess it will be released later!

**Comment by NathanSweet** [comment]
Yes, in a day or so. Sorry for the wait!
