### ISSUE TITLE
Offset should respect the loop start/end

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#437]
When you set a delimited loop, the Offset tool now moves all the keyframes outside of it and loops them all inside, while in the past it left those keys alone.

A user reports:
> For instance, I could have an idle animation where I've looped the idle several times with some fidget changes throughout the timeline, and I'm going back to the original loop to modify something. I don't really want it to blow away everything outside that loop, as I would usually just select any changes I made and copy/paste propagate them to the rest of the timeline after my edit.
> Now I need to copy that segment of loop, create a new animation for it, make the adjustments, then copy the key changes and paste them like I used to into my original animation

**Comment by NathanSweet** [comment]
3.7.88
