### ISSUE TITLE
Unable to run Spine on OS X 10.9 "Mavericks"

### ISSUE THREAD

**Issue by Eroica** [EsotericSoftware/spine-editor#438]
Hi,

I'm not able to run Spine on my 10.9 machine anymore. Spine worked in the past without problems, then I had to do a long pause from working with Spine, and only noticed recently that the newest Spine version (available from one's download page) does not run on this version of OS X anymore.

When opening Spine, it briefly shows up and then closes automatically.

If I run Spine from the command-line, it shows this error:

    /Applications/Spine/Spine.app/Contents/MacOS/Spine
    <JAVA_HOME>/lib/ext exists, extensions mechanism no longer supported; Use -classpath instead.
    .2019-02-08 16:21:05.360 Spine[2543:6a03] Unable to create Java VM, error: -1

As far as I'm aware, Spine comes with its own JRE, but for completion's sake I also tried installing a separate Java runtime for OS X from Oracle, with no success.

Spine's minimum system requirement is still 10.7 (Lion), and I'd be happy if I Spine continues to work on older machines.

Feel free to ask for more information if you ned to. Thanks for creating Spine!

**Comment by NathanSweet** [comment]
We test every build using OS X 10.9, so it's not a problem that you are using 10.9. It appears the OS X installer doesn't clean old files and that having an `ext` folder at `/Applications/Spine/Spine.app/Contents/MacOS/launcher/jre/ext` causes Spine to fail to load. We've updated the Spine installer so it first removes `Spine.app` (launcher version 3.7.82). Can you please try downloading it and reinstalling? If there is still a problem just respond here and we'll reopen this issue.
