### ISSUE TITLE
Offset tool not creating correct curves

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#441]
Repro steps:
1. [Download and open repro project](https://www.erikari.it/uploads/125-incorrect-offset-curves-bugrepro.spine)
2. Offset only one of the two bones in the first `animation`
3. It will result in curves such as `animation2`

Expected: offset curves should look like before they were offset.

Reference topic: http://esotericsoftware.com/forum/different-offset-3-7-90-11559

**Comment by NathanSweet** [comment]
Fixed in 3.7.93 and 3.8.07-beta.
