### ISSUE TITLE
3.7.91 CLI temp files not removed

### ISSUE THREAD

**Issue by Wizermil** [EsotericSoftware/spine-editor#446]
Hi,

Investigating an export error on our server I noticed at least 2 files + 1 directory are created in temp (`echo $TMPDIR` on macOS) and never removed.
Because we don't reboot our server often we are experiencing out of space issues from time to time making the export impossible :(

* +~JF[0-9]+.tmp
```
+~JF11882546229789058401.tmp: TrueType Font data, 17 tables, 1st "GDEF", 15 names, Microsoft, language 0x409, Copyright 2012 Google Inc. All Rights Reserved.Noto SansRegularMonotype Imaging - Noto SansVers
```
* [0-9].tmp
```
7034f8049314824136186456640.tmp: Mach-O 64-bit dynamically linked shared library x86_64
```
* libgdxwizermil
```
libgdxwizermil
├── 7034f804
│  └── libgdx-freetype64.dylib
├── 25838d9c
│  └── libspine-editor64.dylib
└── e6d6dca3
   └── libgdx64.dylib
```

Thanks

**Comment by NathanSweet** [comment]
These files are part of Spine and are only a couple megabytes. Spine leaves them so they don't need to be extracted next run, reducing Spine's start up time.

In 3.7.92 Spine will attempt to leave fewer files behind, but for a server that doesn't reboot very often, you might add a cron job that deletes temp files older than a day or so.
