### ISSUE TITLE
Adjust mesh weights to match another mesh 

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#447]
Allow mesh weights to be "glued" to the weights of a different mesh.
See discussion here: http://esotericsoftware.com/forum/Request-I-want-Glue-function-11611

**Comment by NathanSweet** [comment]
+1 http://esotericsoftware.com/forum/Weights-feature-improvement-17870

We should do this soon!

**Comment by misaki-eymard** [comment]
+1 http://esotericsoftware.com/forum/Weights-feature-improvement-18162

**Comment by NathanSweet** [comment]
4.2.43-beta

**Comment by ThuongMinhDuong** [comment]
i hope there also a funtion of Copy and Paste exactly Vertices's weights , same to 3D software (Maya ...)
