### ISSUE TITLE
Cross skeleton reference - Clipping End slot

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-editor#448]
A clipping area of a first skeleton can have another skeleton's slot set as `End slot` reference. Since separate json files are exported per skeleton, these cross-skeleton references will lead to errors upon import.

Reported on the forum, repro files and description:
http://esotericsoftware.com/forum/Error-reading-skeleton-JSON-file-for-SkeletonData-asset-11629

Steps to reproduce:
1) Download project package from here: https://www.dropbox.com/s/zq1k7lvatm0l49c/TyphonFiles.zip?dl=0. Unzip to `TyphonFiles`.
2) Open project `TyphonFiles/Project/TyphonTEST.spine` in Spine editor.
3) Filter for `clipping`, select element  named `root`in first skeleton `Typhoon 1x2`.
4) Notice that `End slot` is set to `appear_00`. This slot belongs to second skeleton `Typhoon 1x3`. No error message is provided although this is an illegal reference.

Note that in the current version 3.8. 03-beta of Spine a slot of another skeleton cannot be selected, it is greyed out.

Was first reported as ticket
https://github.com/EsotericSoftware/spine-runtimes/issues/1308

**Comment by NathanSweet** [comment]
3.7.92 projects with this problem are fixed on load.
