### ISSUE TITLE
Mesh manipulation improvements

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#459]
- [x] Show vertices that have been transformed by FFD in a different color.
- [x] Reset selected vertices that have been transformed by FFD to their setup pose position.
- [x] Easy selection of ONLY vertices that have been transformed by FFD.

**Comment by NathanSweet** [comment]
@Shiu I'm assuming these suggestions come from creating mouth shape deforms, likely single frame animations? Did you consider other deform use cases? Eg, vertices should be color if different from the setup pose, or if different from the last deform key? Reset is back to setup pose, not last deform key?

**Comment by NathanSweet** [comment]
3.8.11-beta

Partial reset is done by selecting vertices then using the `Reset` button (animate mode only). Deformed vertex selection is done by ctrl+double clicking a deformed vertex (can select all non-deformed by double clicking an undeformed vertex).

**Comment by Shiu** [comment]
@NathanSweet I didn't consider the other deform use cases you mentioned. Having a different color if the mesh is different from the previous key could be useful in addition to what you already implemented . But a way to reset to previous key would also be needed then.

**Comment by NathanSweet** [comment]
Hmm 3 colors (undeformed, deformed from setup, and deformed from last key) might get busy, but we can try. Maybe we can just do deformed from last key? If there is no last key, then it uses the setup pose which covers your use case while also being useful for pose-to-pose deforming.

I guess copy/paste is one way to reset to whatever you like, if maybe more annoying.

**Comment by Shiu** [comment]
Let's try 3 colors first, if it's too cluttered we can try just resetting to previous key and check if that is sufficient.

**Comment by NathanSweet** [comment]
With 3 colors, if a vertex is different from the last key, it would be colored as "deformed from last key" and the "deformed from setup" color won't be seen.

**Comment by Shiu** [comment]
@nate Giving it a little more thought. Since it's possible to copy vertex positions between frames, I think resetting to only Setup mode is enough. Your last comment made me realize that it could become very confusing with multiple reset options.
