### ISSUE TITLE
Skin specific bones and constraints

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#460]
**Original suggestion from the forum:**
> can we set bones to follow skins so that some bones will be hidden for unrelated skins? i could imagine it would be very messy when my character supports multiple hair styles in the next update.
[- fantasyz](http://esotericsoftware.com/forum/Keying-skins-for-different-animations-11856)

**Example:**
an AK47 has bones for the bullets that fly out. the bones are animated in animations, but really only used when the AK47 is equipped. If the AK47 is a skin and the bones specific to it can be associated to only be shown/computed when the skin is active, then there is less clutter in Spine from all the bones from many different item skins and those bones don't need to be computed at runtime when the item is not active. Another way to do it might be to create a separate skeleton for the AK47.

**Discussion points:**
- it could maybe have a section at the bottom of the skins view to add bones to a skin.
- a bone could be in multiple skins. 
- a bone in skin would only be shown (and computed at runtime) if that skin is active, although this could break things, eg if such bones are used as constraint targets. 
- skin specific bone hierarchy has an overlap with [skeleton attachments](https://github.com/EsotericSoftware/spine-editor/issues/8) but is easier to implement for us and easier for users to manage at runtime (managing a single skeleton vs multiple).
- There could be a list at the bottom of skins view, where one can add/remove bones similar to weights view. maybe bones still show up in tree but not in the viewport.
- In the list panel there could be "show all bones" and "show bones for selected skin" buttons and a bone would need to have the possibility to be assigned to one or more skins.

**Comment by NathanSweet** [comment]
Related to #362

**Comment by TowerCrow** [comment]
Can confirm, I'm now at 6 characters and the extra bones for hairstyles are making everything really messy to work with. And I need to do two more which I dread! Not to mention each character having additional accessories that require unique bones. 

This would solve pretty much all my problems with the current project.

**Comment by NathanSweet** [comment]
We have finished the runtime portion and are working on the editor side. We hope to have it in 3.8 soon!

**Comment by NathanSweet** [comment]
Almost done, another day or two!

**Comment by NathanSweet** [comment]
3.8.12-beta
