### ISSUE TITLE
Super skin mode

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-editor#462]
It is hard to view information across multiple skins, i.e. which placeholders have attachments from what skins, In the current tree view. It also makes actions like deleting attachments across many skins cumbersome. Users have to switch between skins and scroll back up to the editing location multiple times.

Super skin mode will show all attachments across all skins under every placeholder:

```
placeholder
   skinA
      attachment1
   skinB
      attachment2
   skinC <- has no attachment for this placeholder
```

The feature can be toggled in the tree view settings:

![https://marioslab.io/uploads/screenshots/mCN6VLEsRq.png](https://marioslab.io/uploads/screenshots/mCN6VLEsRq.png)

Whether skins without an attachment for a placeholder (like `skinC` above) should be displayed could be an option.

**Comment by HaraldCsaszar** [comment]
Thoughts on colors / providing more visual clues:
Color could be used to highlight to which skin something belongs (if a skin-color cannot be defined by the user, chose randomly from skin name).

Items at other skins could be displayed as greyed-out entries.

One more thing that comes to my mind, but maybe not necessary / adding too much clutter:
When not in Super skin mode, we could (additionally) add one or multiple small (colored) numbers or skin-initials next to an item to display (a) how many or (b) which other skins an item is assigned to.

**Comment by HaraldCsaszar** [comment]
Above mentioned colors / numbers could be shown in a collapsed view - when expanded, everything shows as described in the topmost comment.

**Comment by NathanSweet** [comment]
3.8.20-beta
