### ISSUE TITLE
Skin bones create wrong draw order state 

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#467]
**Reproduction**
Use https://slack-files.com/T16HNUL6L-FJGMN0XA5-983081c446

1. Open the attached project.
2. Go to animate mode.
3, Activate `goblingirl` skin. (note: `Draw order` has now changed as indicated by the icon next to `dagger`. `dagger` also happens to be the only bone in the `goblin` skin).

I believe this is already a bad state for the project, and there are probably many ways to make it crash now, but one way to do it is.

4. Activate `Auto Key` and Create a deform key on `spear-path` by translating a vertex.  (note: A draw order key was also created)
5. Copy the deform key using Ctrl+Shift+Drag, Spine should crash now.

**Comment by erikari** [comment]
I think I got the same bug.

**Repro steps:**
1. open https://www.erikari.it/uploads/289-twitch-dudes.zip
2. in animate mode, move a bone in the walking animation (a draw order key is created)
3. press play, or select anything in the tree
> crash

I had Auto Key on as well.

Here's the log:
https://www.erikari.it/uploads/294-ZO5h.txt
