### ISSUE TITLE
Add folders to Preview and Animations views

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#473]
With a long list of animations it can become hard to find the animation you're looking for in the `Preview` and `Animations` views. 
Prefixing the animation names to keep them grouped together is currently the best option. This makes the use of folders in the `Tree` view less useful than intended.

For example, if I have a folder called `expressions`, I would put in animations named `anger`, `joy` etc. 
```
Expressions
- anger
- joy
```

But due to no folders in `Preview` and `Animations` views, I instead have a folder called `expressions` and in this folder I have `expression anger` and `expression joy`.
```
Expressions
- expression anger
- expression joy
```

It's possible this will also need to be reflected in the exported names. An option could be `prefix animations with folder name`.

Related issue: https://github.com/EsotericSoftware/spine-editor/issues/474

**Comment by NathanSweet** [comment]
3.8.10-beta
