### ISSUE TITLE
On export, prefix animation names with Tree folder names.

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#474]
Using the following Tree structure
![](https://i.imgur.com/HELYAdP.png)

the animation names `anger` and `joy` should be prefixed with `expression` when exporting JSON.
Resulting in: 
```
expression-anger
expression-joy
```

The prefix should be forced!
Forcing the prefix allows using the same animation name in multiple folders.

related issue https://github.com/EsotericSoftware/spine-editor/issues/473 needs to be closed before allowing the same animation name in multiple folders.

**Comment by NathanSweet** [comment]
3.8.20-beta
