### ISSUE TITLE
Process PSD files similar to the PhotoshopToSpine script

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#476]
This provides a path to bring images into Spine at the correct positions without needing Photoshop. It could have similar functionality to the Photoshop script:
- Scale and trim images with padding.
- Maybe it can support tags in image file names: `bone`, `slot`, `skin`, `folder`. Tags would need the value in the file name, eg `[bone head]` or `[skin red]`. However, you wouldn't want tags in your skeleton image files. Importing could copy the image files into the images folder with the tags removed.

http://esotericsoftware.com/forum/Is-there-any-alternate-ways-to-import-psd-to-spine-12098?p=54010#p54010

**Comment by lalexedwards** [comment]
This would be awesome, do we have an eta?

**Comment by NathanSweet** [comment]
PNG files lose the layer hierarchy, greatly reducing usefulness. Many tools can export PSD, so we could have Spine process a PSD file similar to the PhotoshopToSpine script. Discussion here:
http://esotericsoftware.com/forum/Paint-Tool-SAI-Exporter-17955?p=79016#p79016

**Comment by NathanSweet** [comment]
4.2 supports [processing PSDs directly](http://esotericsoftware.com/blog/Import-PSDs-directly-no-Photoshop-scripts-needed).
