### ISSUE TITLE
Deform keys not pasted in 3.8.21-beta

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#477]
**Description:**
Deform keys are not pasted when copied in the dopesheet

**Repro steps:**
1. Open Spineboy example project
2. Go to animate mode
3. Select the mesh torso
4. Select the keys of the last frame of the animation in the dopesheet and copy them (Autokey is enabled)
5. Paste them on a different empty frame
> the deform key is not pasted.

**Reference mail that shows a video of the problem:**
FMfcgxwChJdGFrnmbTKgLJxNDtQXVZMS

**Comment by NathanSweet** [comment]
Duplicated? Copied?

**Comment by NathanSweet** [comment]
3.8.22-beta
