### ISSUE TITLE
Vertex could not be deleted

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#480]
In the repro file, an edge is present for all the vertices in contact with the vertex that can't be deleted. 
Recreating the edge in case a spot was missed still didn't allow to delete the vertex. 
Deleting or moving a vertex from the edge makes deleting the problematic vertex possible. 
It's possibly not a bug, still, it seems like this is a case where it should be allowed to delete the vertex.

**Repro steps and project in mail:**
FMfcgxwChchShvwtQsdSXDLZCKxftgSG

**Related forum topic:**
http://esotericsoftware.com/forum/Vertex-could-not-be-deleted-why-12226

**Comment by NathanSweet** [comment]
3.8.36-beta
