### ISSUE TITLE
libgdx TextField should behave as expected on OS X

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#481]
TextField has Windows-like behavior when using backspace, ctrl+arrow, home, end, etc which is confusing for Mac users.

**Comment by badlogic** [comment]
Works as intended. `CMD` + arrow does what it is intended to do, backspace works as intended. home and end aren't really used. The only thing that's different is that `CMD` + arrow jumps by word, not by line, same as on Windows/Linux.
