### ISSUE TITLE
Atlas packing wrong when two mesh attachments map to a single input image

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-editor#483]
As reported in this email:
FMfcgxwDqTkCzQbTXMlvpvsZlDKGcxfg

[Edit:] Also reported by a different user on this forum thread:
http://esotericsoftware.com/forum/Only-first-attachment-will-be-exported-12435

Reproduction asset included in the first email as zip package.

Context:
When taking a look at the input image at `Bugged Slingshot/images/Slingshot_idle_Top.png` (the only colored one in the image set), it contains the complete `V` part of the slingshot.
In the Spine project, the mesh attachments `Slingshot_TopFar2` and `Slingshot_TopNear2` map to only the left or right half.

Reproduction Steps:
1. Open the included Spine project in the package.
2. Export the skeleton with setting `Texture Atlas` `Pack` enabled, and packing type `Attachments`, Texture Packer settings `Packing` set to `Rectangles` or `Polygons`.
3. Take a look at the generated png atlas file, a half slingshot is included in the atlas page, but only one half - the second half is missing.

Polygonal packing:
![texture-packer-slingshot-polygon](https://user-images.githubusercontent.com/32591206/62556419-1dabe600-b875-11e9-8470-61107a0cf473.PNG)

Rectangular Packing:
![texture-packer-slingshot-rectangle](https://user-images.githubusercontent.com/32591206/62556420-1dabe600-b875-11e9-959f-39f02d1363c4.PNG)

**Comment by HaraldCsaszar** [comment]
A different user also reported the same problem on this forum thread:
http://esotericsoftware.com/forum/Only-first-attachment-will-be-exported-12435

**Comment by NathanSweet** [comment]
3.8.61
