### ISSUE TITLE
Undo causes images attached through timeline to disappear in viewport

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-editor#484]
See http://esotericsoftware.com/forum/Undo-causes-images-in-animations-to-disappear-12456

Repro steps:

1. Open raptor
2. Switch to animate mode
3. Make `gun-grab` animation active
4. Select all keys in dopesheet and move them to the right
5. Undo

The arm image `front-hand`, which is attached through a timeline, disappears.

**Comment by NathanSweet** [comment]
3.8.60
