### ISSUE TITLE
Mix-and-match project won't open in 3.8.60

### ISSUE THREAD

**Issue by eskalation** [EsotericSoftware/spine-editor#485]
Whenever i try to open the Mix and Match project from the examples section of the menu, i get an error.

**Comment by eskalation** [comment]
Mac, Pro version, if that makes any difference. I don't think the spine file is there.

**Comment by badlogic** [comment]
I've tested this, installing the latest launcher 3.8.58 from my license page, and setting the Spine Editor version to 3.8.60. The project shows up in the example grid in the welcome screen. Clicking on it opens the project just fine.

Could you send me your spine.log file? You can find it in this location:

`/Users/<yourusername>/Library/Application\ Support/Spine/spine.log`

**Comment by badlogic** [comment]
Closing this out. Will re-open if you still see the issue and can supply the spine.log file.
