### ISSUE TITLE
Entering decimal point in filled input field sometimes fails

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#486]
In version 3.8.60 user reports that entering a decimal point in a field that already has a number fails.

**Reproduction steps.**

- Create new project.
- Go immediately to export dialog `Pack Settings`.
- Type in `5.0` in the first scale box.
- Select the `5.0` and enter `.5`.
The entry will not be accepted.

Related thread and similar reproduction steps can be found here: http://esotericsoftware.com/forum/Feature-Request-Floating-Point-Input-Field-Tweak-12428

This also affects entering values in an offset fashion. See:
http://esotericsoftware.com/forum/About-numeric-entry-12552

**Comment by NathanSweet** [comment]
3.8.64
