### ISSUE TITLE
IK constraint options keys incorrectly exported 

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#491]
IK Constraint options that have been keyed are incorrectly exported.

**Reproduction:**

Using the project found here: http://esotericsoftware.com/files/issues/491-ikConstraintExportBug.zip
1. Export JSON.
2. Import the JSON into a new file.
3. Go to Animate mode and notice that both IK constraints are not following the IK targets. Additionally the settings for each IK constraint is no longer identical to what we exported.

Looks like `"bendPositive": false`  is not having an effect in the animation at all, even if the key is there, and `"bendPositive": true` is exported as `"compress": true`.

**Comment by rh101** [comment]
How soon may we expect a fix for this issue? We can't import modified JSON spine files back into Spine without corrupting it, so for the time being we're stuck.  Unfortunately, the work-around mentioned in the email response didn't work (checking/unchecking "Positive" under your IK Constraints at frame 0 of our animations after importing the JSON).

**Comment by NathanSweet** [comment]
Sorry for the delay! Fixed in 3.8.73.
