### ISSUE TITLE
Dragging bones in the weights view and then undoing the action does not update the triangle draw order

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#494]
Reproduce using the project found here: http://esotericsoftware.com/files/issues/494-weightsTriangleRenderOrder.zip
1. Select the mesh and in the `Weights` view drag `tentacle19` and `tentacle20` to the bottom of the list. 
The triangles affected by those bones should now be drawn behind the rest of the mesh. Before this action was taken, they were drawn in front of the rest of the mesh.

2. Undo the two drag actions so `tentacle19-20` are shown at the top of the list again. 
The affected triangles should again be drawn in front of the rest of the mesh, but are drawn behind, as if the undo never took place.

**Comment by NathanSweet** [comment]
3.8.73
