### ISSUE TITLE
Overlapping pies crash

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#497]
Steps:
1. open repro project from mail FMfcgxwDrlZGdqJHJjGphwCZJTzDBgCR
2. select weights tool
3. press 1
4. click on the orange portion of this vertex here
5. press 2
6. click 2 times, even slow, to get Spine crash
http://prntscr.com/pki7t0

Repro video in mail

**Comment by NathanSweet** [comment]
3.8.76
