### ISSUE TITLE
MOV and GIF export freeze and fail

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#498]
Export gets stuck at 11% - 12% when attempting to export the repro project as a mov with png encoding and a transparent background or a gif.

**Repro steps**
1. Open mix-and-match example project
2. Export MOV with encoding PNG, transparent, everything else default.
3. Open the export preview
4. Export
> bug
If point 3 isn't performed, the export reaches the end.

**Reference thread and project:**
http://esotericsoftware.com/forum/Export-MOV-stuck-at-12-12678

**A second related mail:**
FMfcgxwDrvCSTFqWtNQCjqJFBhqtMLrN

**Comment by NathanSweet** [comment]
3.8.76
