### ISSUE TITLE
Setting to recalculate path segment lengths

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#499]
http://esotericsoftware.com/forum/Questions-about-path-lengths-12931

**Comment by Shiu** [comment]
You can use this project when looking into this:
http://esotericsoftware.com/files/issues/499-recalculatePathLength.zip

**Comment by NathanSweet** [comment]
We already recalculate the path length when constant speed is checked, so a setting to do that is not necessary. The problem is actually caused by this commit: e4839352ecae73221f0ececd45beac67312ab12e

When the root bone is scaled, the path and constrained bones are scaled. Scaling the path is fine, even with a fixed position, but scaling the constrained bones makes them the wrong size for the fixed position.

That commit scales the fixed position by the difference between the path's setup pose length and the deformed length. That does indeed scale the fixed position when the root bone is scaled, so it matches the constrained bones, however it breaks the fixed position when the path is deformed and also when a parent bone of the path is scaled. This is wrong and not a good trade at all.

Removing the position adjustment added by the commit allows a parent bone of the path to be scaled correctly. Scaling the root bone (or any other parent bone of the constrained bones) will cause the bones to be the wrong size for the fixed position, but I believe this is expected behavior. The reason it looks "wrong" is that the constrained bones have been scaled to a different size and the fixed position along the path needs to be adjusted to match. I don't see any way we can adjust the fixed position automatically.
