### ISSUE TITLE
Type-to-filter for tree

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#5]
http://esotericsoftware.com/forum/How-to-search-skeleton-in-spine-project-6157

**Comment by erikari** [comment]
+1 and another +1 if it's with a RegEx option.

**Comment by erikari** [comment]
Other suggestion:
a "Has children" option, expecially useful to check if a skin placeholder has attachments inside in a certain skin.

**Comment by erikari** [comment]
http://esotericsoftware.com/forum/Questions-and-requests-9786 they would benefit this too, lots of scrolling in the tree!

**Comment by erikari** [comment]
http://esotericsoftware.com/forum/How-to-search-skeleton-in-spine-project-6157 More people requesting this!

**Comment by NathanSweet** [comment]
3.7.69-beta
