### ISSUE TITLE
Root bone offset is applied to the dragged assets

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#500]
**Repro steps:**
1. open spineboy, and delete hips bone
2. offset the root to 50,50 translation
3. drag several images in the editor

**Actual result:**
![](http://esotericsoftware.com/forum/download/file.php?id=6282)

**Reference topic:**
http://esotericsoftware.com/forum/Root-bone-offset-is-applied-to-the-dragged-assets-12941

**Comment by NathanSweet** [comment]
3.8.76
