### ISSUE TITLE
Opt-in setting to get a warning when opening a project with an older version than the current editor version

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-editor#505]
As per the title. When a project saved in an older Spine major version is opened by an editor version with a higher major version, a warning dialog should be displayed informing the user of their impending doom.

This setting should be opt-in and not on by default.

**Comment by NathanSweet** [comment]
We warn when saving an older project with a newer one. It's similar, though it means the user doesn't know until they try to save. Still, I think that achieves the goal? If not we can reopen.
