### ISSUE TITLE
PhotoshopToSpine script not scaling layer styles when exporting

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#506]
Layer styles on aren't exported at the correct size unless they're in a group with the `[merge]` tag, or you export at 100% scale.

Reproduction:
1. On a layer, apply the `Stroke` effect and set the width to 10px. 
2. Export using the script, and set scale to 50%.
The exported width of the stroke should be 5px now, but is still 10px. 

Placing the layer in a group with the `[merge]` tag will scale the stroke effect correctly when exporting.

To fix this the script needs to rasterize the layer style before export.

**Comment by NathanSweet** [comment]
PS script is not so straightforward as being able to allow rasterizing layer styles. Instead, I changed how scaling is done. Please verify the fix with a variety of input.

**Comment by NathanSweet** [comment]
Went back to old scaling, added explicit rasterize layer styles.
