### ISSUE TITLE
Color of alpha selector is not updated in Color picker

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#507]
When a color is picked in the `Set slot color` window, the color of the alpha selector is not changed dynamically.
![](http://esotericsoftware.com/forum/download/file.php?id=6355)

But if the color is applied by clicking the `Ok` button and then reopening the window, the selector will be in the right color.
![](http://esotericsoftware.com/forum/download/file.php?id=6356)

**As described in forum post:**
http://esotericsoftware.com/forum/Color-of-alpha-selector-is-not-updated-in-Color-picker-13059

**Comment by NathanSweet** [comment]
3.8.77
