### ISSUE TITLE
Outline view displays shear incorrectly

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#508]
**See repro mail and project:** 
FMfcgxwGBmttzFSPjwBnqXQZVQRSRJGW
http://esotericsoftware.com/forum/Shearing-is-breaking-mesh-13072

**Repro steps:**
Open the repro project, switch to animate mode and look at the Outline view. The forearm looks differently from the one in the viewport.

**Comment by NathanSweet** [comment]
I am not able to repro with 3.8.76. Are there missing steps?

**Comment by NathanSweet** [comment]
Oops, outline view, not preview view! Fixed in 3.8.77.
