### ISSUE TITLE
Spine project with separate files for each skeleton in project

### ISSUE THREAD

**Issue by knifhen** [EsotericSoftware/spine-editor#509]
Hi,
One issue that we have in our team is big spine projects with many skeletons and people working on the different skeletons at the same time.

I would like to propose a change to the spine project structure, where instead of one file for the whole project, each skeleton would get it's own file. This would make it much easier to avoid conflicts when to people edit different skeletons in the same project. While at the same time still allowing for the benefits of having said skeletons in the same project, seeing their animations play together.

Best Regards Andreas Knifh

**Comment by NathanSweet** [comment]
It's an interesting idea, but a big change in how things work. You can already have one skeleton per file, so I would suggest doing that and importing other skeletons as needed for visualization. It is common for big teams to work on separate project files, then have one person who manages a "master" project containing many or all the skeletons.
