### ISSUE TITLE
Photoshop to Spine script should not require a name for layers with the [ignore] tag

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#512]
**Actual behavior:**
If a layer is only named `[ignore]` the script will stop and give an error.

**Expected behavior:**
Since the layer has to be ignored anyway, the name shouldn't need to be specified.

**Reference thread:**
http://esotericsoftware.com/forum/photoshopToSpine-v3-ignore-13110

**Comment by NathanSweet** [comment]
I see a layer named `[ignore]` working fine, so this must have been fixed at some point.
