### ISSUE TITLE
Polygon packing null pointer exception

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#513]
Exporting with the polygon packing setting from the Spine editor v3.8.76 results in an error and no atlas and png files output.

Log and repro projects can be found in the forum thread.

**Repro steps**

1. Download and open repro project
2. Press `Ctrl+E` and export with the last used settings which should include polygon packing after specifying a new export path
> error

**Forum thread:**
http://esotericsoftware.com/forum/Polygon-packing-NULL-pointer-error-13137

**Comment by NathanSweet** [comment]
3.8.77
