### ISSUE TITLE
Skin bones are not removed from deleted skins

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#516]
When deleting a skin, skin bones in the deleted skin will not be removed.

**Reproduction:**
1. Create a skin. 
2. Add a bone to the skin. 
3. Hover the cursor over the skin icon next to the bone to see which skin the bone is placed in.
4. Delete the skin.
5. Hover the cursor over the skin icon again and it will still show the bone being placed in a skin which is no longer there.

**Comment by NathanSweet** [comment]
3.8.79
