### ISSUE TITLE
Export to PSD doesn't export a slot if set to multiply

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#518]
**Repro steps:**
if in Spine a slot has a blending mode set to multiply, exporting the current pose as a PSD will not export the slot.  (the others are exported as normal layers without a blending setting)

**Expected result:** 
A layer should be exported in the PSD for the slot and the correct blending mode should be applied to it.

**Repro steps:**
1. open spineboy in Spine 3.8.79
2. change the head slot to multiply blending mode (optionally choose other parts to test other blending modes as well)
3. Ctrl+E, choose PSD export, choose current pose, export
4. once opened in Photoshop, the head of Spineboy is missing from the file.

**Related forum thread:**
http://esotericsoftware.com/forum/psd-exporting-problem-13223

**Comment by NathanSweet** [comment]
3.8.80 renders the attachment without the blend mode and sets it on the layer.

Note this is expected for other formats, eg PNG: when exporting using a transparent background, a multiple blend mode will multiple by the background (zero) and so no pixels will show. Nothing can be done there.
