### ISSUE TITLE
Add a hotkey that selects the keyframes of the currently active timelines at the current frame

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#519]
As per title, if one had a hotkey that selects the keyframes of the currently active timelines at the current frame, it would be easier to run little scripts or do some hotkeyoperations a bit faster, maybe even just customizable in the hotkey file.

Reference thread:
http://esotericsoftware.com/forum/x-13169

**Comment by NathanSweet** [comment]
3.8.80, new hotkey is `Select Keys` and is not bound by default.
