### ISSUE TITLE
Linked mesh child doesn't pack as polygon

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#521]
**Expected:**
Linked mesh image should use polygons when packing with the polygons setting.

**Actual:**
The black wing packs as a square.
![repro](https://www.erikari.it/uploads/719-powerup-pro.png)

**Steps:**
1. Open the repro project, look at the image `wing-black`, which is the child of a linked mesh.
2. JSON Export packing the images as polygons.

**Repro project:**
https://www.erikari.it/uploads/720-powerup.zip

**Thread:**
http://esotericsoftware.com/forum/Linked-meshes-do-not-pack-as-polygons-13291

**Comment by NathanSweet** [comment]
3.8.80
