### ISSUE TITLE
Skin constraints applied incorrectly on png export

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#522]
**Description of the problem:**
When exporting in PNG, following these settings: (saved in the file)
![export settings](https://user-images.githubusercontent.com/29667068/72267590-9da65b00-3620-11ea-9877-8afd8e108da4.png)

The resulting images display an error in positioning the eyes (the eyes position changes depending on the skin thanks to skin constraints)

Resulting in skins such as:
![Character-Bear-Bear-yellow](https://user-images.githubusercontent.com/29667068/72267699-d1818080-3620-11ea-82d6-f243733ff087.png)

Instead of:
![Character-Bear-Bear-yellow](https://user-images.githubusercontent.com/29667068/72267922-2ae9af80-3621-11ea-8f0c-5a815a9de347.png)

Regardless if a skin is pinned or active.

The expected result is that each skin should show the correct eyes placement instead.

**Steps:**
1. Open project in mail
2. Export with PNG settings as per screenshot above

**Repro mail and project:**
FMfcgxwGCkkDXJTBxmSRdlMWFXNHCwxF

**Comment by NathanSweet** [comment]
3.8.80

**Comment by erikari** [comment]
The problem persists on several skins: http://prntscr.com/r5kuio
Using the same repro steps listed above (open, export with export settings saved withing the file).

The skins are displayed correctly when activated in the Spine editor, but several exported skins show misplaced eyes (which are controlled by transform constraints) on png export.

**Comment by NathanSweet** [comment]
Got it, was an obscure problem with how constraint order is calculated. Fixed in 3.8.85!
