### ISSUE TITLE
Attachments in skins lose keys when keying an attachment in another skin

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#523]
Spine appears to forget the keys set for a skin when an attachment in a different skin is keyed.

**Repro steps and project in mail:**
FMfcgxwGCkmXKfZqRwNmCWmSmnNHcTlV

**Related forum thread:**
http://esotericsoftware.com/forum/Found-a-bug-with-skins-13323

**Comment by NathanSweet** [comment]
3.8.80
