### ISSUE TITLE
Packing overlaps different textures

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#525]
Polygonal packing seems to fail when combined with several settings. Padding may be a culprit, as well as strip whitespace.

**Repro steps:**
1. download project from email (if the download has expired, ask for the folder "Spine-pack-bug")
2. Export with these settings: [download settings](https://www.erikari.it/uploads/736-pack-penguins.pack.json)
![](https://www.erikari.it/uploads/735-Screen-Shot-2020-01-21-at-14.14.19.png)
3. `Penguins4.png` will display this overlap on an arm:
![](https://www.erikari.it/uploads/737-8Tyr.png)

**Reference email:**
FMfcgxwGCtGfSsgRtBqqNMMhFGQvQNWS

**Comment by NathanSweet** [comment]
Fixed in 3.8.80. This seemed to be a very unlucky problem with numerical precision. We improved a number of things and it is fixed for these particular images, but we should be on the lookout in case the problem surfaces with different images.
