### ISSUE TITLE
 When navigating with hotkeys, folders should be taken into account

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#526]
**Current:**
Navigating animations using `y` and `t` when there are folders in the list doesn't follow the visual order of animations in the hierarchy.

**Expected:**
Navigating using hotkeys should take into account the presence of folders and move to the next item visually in the list.

The same applies to skins (`,` and `.` hotkeys)

**Related thread:**
http://esotericsoftware.com/forum/Changing-the-animation-selection-with-hotkeys-13355

**Comment by NathanSweet** [comment]
3.8.80
