### ISSUE TITLE
Ensure wide color gamut monitors correctly display sRGB input images

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-editor#537]
Reported via email: FMfcgxwGDNQfKSvtGwcpKNsWXCtCPvrV

Solutions could be:
1) Simple solution: use [`ARB_framebuffer_sRGB` extensions](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_framebuffer_sRGB.txt), as mentioned [here](https://stackoverflow.com/posts/6397924/revisions).
2) Make the application fully color managed / monitor color profile aware.

Userful references:
https://stackoverflow.com/posts/6397924/revisions
https://developer.apple.com/library/archive/technotes/tn2313/_index.html
https://opencolorio.org/
Testing wide color gamut:
https://cameratico.com/tools/web-browser-color-management-test/
https://chromachecker.com/info/en/page/webbrowser

- [x] Create minimal OpenGL test application to find best solution.
- [ ] Integrate solution in Spine.

Related issue: Alpha blending behaves as if it were blended in Gamma-space:
http://esotericsoftware.com/forum/The-blend-effect-in-spine-different-from-unity-13248
When adjusting image loading and framebuffer code, it shall be investigated along the way why this is happening, when image loading is already expected to have performed the sRGB to Linear conversion.

**Comment by Huatimes** [comment]
If you have a plan to support it in spine please contact me, thank you very much.

**Comment by HaraldCsaszar** [comment]
@Huatimes we have a plan to support it, otherwise we would not have created a ticket. It is already in progress as you can see.

**Comment by Huatimes** [comment]
> @Huatimes we have a plan to support it, otherwise we would not have created a ticket. It is already in progress as you can see.

That's just great. Thank you for your efforts.

**Comment by HaraldCsaszar** [comment]
Test application resides at `files/spine-color-testing/SpineColors-1.0.zip`
Readme.md file with all necessary information contained in zip package at top directory.

**Comment by Huatimes** [comment]
Hi, where can i find spine-color-testing/SpineColors-1.2.zip, why didn't i find it.

**Comment by Huatimes** [comment]
Shall I download the latest version of the spine editor?

**Comment by HaraldCsaszar** [comment]
@Huatimes The `SpineColors` test application is of no benefit for the end user, this information is intended for Nate or the person who will integrate the solution into the Spine editor.

If you take a look above, it is only the first part of the task:
done: Create minimal OpenGL test application to find best solution.
todo: Integrate solution in Spine.

**Comment by Huatimes** [comment]
Ok i see thank you

**Comment by Huatimes** [comment]
Looking forward to this feature

**Comment by NathanSweet** [comment]
@badlogic Can you handle the Mac side? Harald's ZIP has ObjC for what is needed. There are JNI methods in the spine-editor lib for Windows, currently empty for Mac. Alternatively it could be done in the Mac launcher.

@HaraldCsaszar I guess your ObjC uses the default monitor? We'll need to get the monitor that has the Spine window. FWIW, on Windows we pass Spine's HWND to JNI so it knows which monitor to query.

**Comment by NathanSweet** [comment]
4.0.00-beta

**Comment by NathanSweet** [comment]
Ah, closed a bit prematurely. Windows and editor changes are done, just need Mac support.

**Comment by huatime** [comment]
Hi, Is this feature already supported in spine editor?

**Comment by NathanSweet** [comment]
@huatime Yes, but only in v4. We plan to start the v4 beta soon, then you can try it out.

**Comment by huatime** [comment]
Great. Thank you.

**Comment by NathanSweet** [comment]
4.0.00-beta
