### ISSUE TITLE
Provide world 0,0 offset for exported frames

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#539]
It's currently not possible to know how to position exported PNG frames at runtime. The best that can currently be done is to export with `Maximum bounds`, then determine the offset manually for each skeleton. We should probably expand the atlas format to have X and Y for a reference point, which would correspond to world 0,0 in Spine.

**Comment by dongyiqi** [comment]
Hope this issuse could be fixed ASAP

**Comment by NathanSweet** [comment]
Done in 4.0.46-beta, available now.

How it works is described here:
http://esotericsoftware.com/forum/Pivot-data-for-exported-frame-sequence-13566?p=66561#p66561
