### ISSUE TITLE
Show favorite directories before file chooser

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#54]
Show most recent and most chosen directories before opening the usual file dialog, similar to MS Word.

**Comment by NathanSweet** [comment]
For choosing a file, it would look something like this:
![](http://n4te.com/x/860-kXbO.jpg)
This dialog does not appear when there are no recent files or folders. Clicking a file chooses that file. Click a folder opens the OS file dialog at that folder. Clicking browse is the same as clicking the topmost folder.

For choosing a folder rather than a file the same dialog is shown, but without the recent files section.

My screenshot looks bad of course. Dialog title graphics are maybe a bit simple and are not differentiated from the dialog's content. This also happens for export, settings, etc:
![](http://n4te.com/x/862-BPyW.jpg)
![](http://n4te.com/x/861-zHQN.png)
@shiu, maybe we need new graphics for dialog backgrounds? Want to mock up a better looking open dialog?

**Comment by NathanSweet** [comment]
Need design image for how this file open dialog should work.

**Comment by NathanSweet** [comment]
![](http://i.imgur.com/APxWC6S.png)

Spacing too large. Needs browser and cancel buttons.  Dialog shows X recent files and folders. Star pins items to top of list on next dialog open. Items have hover bg highlight.

Add favorite folder button? May want to favorite a folder that is one level higher than all the projects.

Icons:
icon-favorite
icon-project
icon-folder

**Comment by NathanSweet** [comment]
WIP:
![](http://n4te.com/x/102-CLgM.png)

Showing the full directories wastes vertical space. This is importantbecause users with many projects benefit the most from this dialog. We can use a unique prefix of parent directories if multiple items have the same name, as we currently do on the recent files submenu.

**Comment by NathanSweet** [comment]
@Shiu since this dialog is used every time a file is chosen, we need icons for every file type that can be opened:
- [x] project file
- [ ] export settings file
- [ ] data file
- [ ] media file
- [ ] atlas data file

**Comment by Shiu** [comment]
Committed preliminary icons for the dialog

**Comment by NathanSweet** [comment]
3.6.15-beta
