### ISSUE TITLE
Active filter inconsistency on point attachment creation

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#543]
When creating a point attachment with a filter active in the tree preventing the point from being selected, the point attachment appears selected in the ui.

**Expected:**
The point attachment should move (instead of the bone) or be deselected.

**Actual:**
Current behavior displays the point attachment selected but the parent bone moving.

Reference thread with gif:
http://esotericsoftware.com/forum/minor-UI-bug-13632

**Comment by NathanSweet** [comment]
3.8.87
