### ISSUE TITLE
AnimationState, setup pose attachment shown when mixing out higher track

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#545]
Setup pose appears to be dipping (showing up briefly) when deselecting an animation despite having several tracks active with a keyed attachment in the preview view.

**Reference thread with repro gif and project:**
http://esotericsoftware.com/forum/Issue-when-mixing-out-animation-clips-13636

**Comment by NathanSweet** [comment]
Related to:
https://github.com/EsotericSoftware/spine-runtimes/issues/1352#issuecomment-492306414

**Comment by NathanSweet** [comment]
So this issue is caused by EsotericSoftware/spine-runtimes#1352 which was to fix a problem caused by EsotericSoftware/spine-runtimes#1292. It may be we need to solve 1292 in a better way.

**Comment by NathanSweet** [comment]
We've done a new fix for EsotericSoftware/spine-runtimes#1292 that also fixes EsotericSoftware/spine-runtimes#1352 and this issue (#545). The idea is to apply attachment timelines for animations that are mixing out when subsequent animations key the same slot attachment, allowing subsequent animations to see any deforms (1292), but still show the setup attachment when necessary (1352) and don't mess up layering attachment timelines (545).

For the future, here are repro projects for the 3 bugs:
http://n4te.com/x/8060-animstate-projects.zip
