### ISSUE TITLE
Slots dopesheet rows aren't shown after selecting a slot with a mesh

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#546]
Minor bug.
If a slot containing a mesh is selected first, the slots selected after it won't show up in the dopesheet if they contain image attachments instead of meshes. Selecting the same set of slots starting with the ones containing the attachment doesn't show this behavior.

**Repro steps:**
1. Open Spineboy-pro
2. Switch to Animate mode, make sure to have no filters active in the dopesheet or the tree.
3. In the tree, select the following slots in the order they are written by ctrl+clicking on the slot names: `front-bracer`, `front-upper-arm`, `torso`.
**Result:** All the 3 corresponding bones are showing in the dopesheet. 
This is expected and good.

4. Clear the selection by pressing the spacebar
5. Repeat step 3, following this order instead: `torso`, `front-upper-arm`, `front-bracer`.
**Result:** Only the `torso` bone shows up in the dopesheet.
It should show all 3 slots again, but it shows only the first slot instead.
This appears to be caused if the content of the first slot that is selected is a mesh, followed by selecting an image attachment.

**Comment by NathanSweet** [comment]
The dopesheet contents has been based on the viewport selection. It now also considers the tree selection in 3.8.87.
