### ISSUE TITLE
Constraints update bones even at 0% mix

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#549]
The current way the skeleton update cache is applied, constraints that don't need to make changes to the bones (eg because their mix is 0) must still update the bones. This can result in the loss of changes other constraints made.

Eg, if two IK constraints control the same bones with different targets, even with mix=0, one of the constraints cannot be applied. Repro project:
http://n4te.com/x/8071-hands-on-two-weapons.spine

**Comment by erikari** [comment]
Possibly relevant: 
http://esotericsoftware.com/forum/IK-Constraint-Mixing-Bug-14033?p=61906#p61906

**Comment by NathanSweet** [comment]
Simple problematic use cases (can be imported/dropped on Spine 3.8 or 3.9):

- http://n4te.com/x/1013-ik-constraint.json
With this moving `target1` doesn't result in a valid IK solution. The IK constraint `ik2` updates `bone2`, resetting it to the setup pose, leaving `bone1` with the rotation from `ik1`.

- http://n4te.com/x/1014-transform-constraint.json
The problem with this is less apparent, but `bone` is not updated at all. The update cache assumes it will be updated by the constraints, but both constraints have 0 mixes.

**Comment by NathanSweet** [comment]
The update cache uses an optimization where it does a partial update of bones in the `updateCacheReset` list under certain conditions. This works when the assumption is that constraints will always update the constrained bones. If a constraint does not, the bone will not be updated.

The easiest solution is to remove the optimization. This ensures bones are updated before a constraint is applied. If a constraint does nothing to constrained bones, subsequent update cache entries will still see bones that have been updated.

Another part to this is that constraints should do nothing when they are effectively turned off by setting mixes to zero. They should not update the bones, which would either waste effort or undo the changes made by other constraints.

**Comment by NathanSweet** [comment]
Closed by:
https://github.com/EsotericSoftware/spine-runtimes/commit/4e34c0bae169f838005469f7e8b24e583694c4ef
