### ISSUE TITLE
Compensate affects children bones that don't inherit rotation

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#553]
Repro steps:
1. open Spineboy
2. select a bone such as "hair3"  and disable its rotation in the properties
3. rotate the parent bone ("head" in this case)
> the bone with disabled rotation rotates in the opposite direction.
A similar effect also happens when scaling uniformly the parent bone of a bone with inherit scale disabled.

Related forum topic:
http://esotericsoftware.com/forum/Compensate-on-bone-not-inherit-rotation-13800

**Comment by NathanSweet** [comment]
Fixed in 3.9.00-beta. Also fixed for disabling inherit scale.
