### ISSUE TITLE
Can not find a setting file

### ISSUE THREAD

**Issue by CodeMasterYi** [EsotericSoftware/spine-editor#556]
As the title, where is the export settings JSON file?

**Comment by NathanSweet** [comment]
The `Save` button on the export dialog will save the export settings JSON:
http://esotericsoftware.com/spine-export#Project-export

Please note this is an issue tracker, for filing problems with how the Spine editor functions. It is better to use the Spine forums to ask general questions:
http://esotericsoftware.com/forum/
