### ISSUE TITLE
Crash on offset

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#557]
**Repro steps:**
1. open project in mail FMfcgxwHNVtlNzwgdPjsLTsfXrrQZVCT
2. switch to animate mode (the animation "walk w" should already be selected, if not, select it)
3. select the offset tool
4. click and drag the keyframe in the first row and column
> Spine 3.8.95 crashes

**Log and forum thread:** http://esotericsoftware.com/forum/error-after-shifting-frames-13988

**Comment by NathanSweet** [comment]
3.8.96
