### ISSUE TITLE
Bulk bind/unbind bones to meshes

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#565]
As per title, enable selecting multiple meshes and binding one or more bones to all of them at the same time.
This can help greatly speed up the process of binding alternative poses to the root, or a bunch of simple meshes to the same two bones.

**Comment by NathanSweet** [comment]
4.0.20-beta:

- Adds hotkeys for Weights functions, including `Bind`.
- After selecting a bone and clicking `Bind`, can hold `ctrl` when clicking a mesh so subsequent meshes can be clicked.
- `Bind` is active when multiple meshes are selected, so they can all be bound to the same bone with one click.
