### ISSUE TITLE
Bone length tool to also translate children bones

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#566]
As per title, add the option to the bone length tool to also automatically translate the child bones to always be at the tip.

Problem it solves:
This would allow us to resize skeletons, preserve naming, hierarchy, and get through the initial rigging process very quickly as well as introduce new animators without extensive oversight and revisions.

Refernce thread:
http://esotericsoftware.com/forum/Feature-request-Tip-to-tail-bone-length-change-14181

**Comment by NathanSweet** [comment]
Done in 4.0 by holding `alt`.
