### ISSUE TITLE
Duplicating a skeleton loses information

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#567]
**Reference topic:** 
http://esotericsoftware.com/forum/x-14221

**Expected:** 
Duplicate skeleton to be the same as original.

**Actual:** 
Duplicate skeleton loses path color and bone properties.

**Steps:**
1. open the Vine example project
2. select the vine path and change the color (e.g. to blue)
3. select a bone such as "vine-control1" and uncheck "select" and check "name"
4. duplicate the skeleton "vine pro"
> result: the vine path is back to orange instead of blue, the properties for the bone "vine-control1" are reset to "select" checked and "name" unchecked

![](http://esotericsoftware.com/forum/download/file.php?id=7368)

**Comment by NathanSweet** [comment]
4.0.00-beta
