### ISSUE TITLE
Add toast when no bone is selected in the weights view

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#568]
We could add a toast that says "no bone is selected." when one tries to use the add weights brush from the weights panel and no bone is selected. this way it doesn't seem broken and unresponsive.

**Comment by NathanSweet** [comment]
We have this toast:
![](http://n4te.com/x/1912-ixdH.png)
@erikari Please reopen if that is insufficient or doesn't appear when it should.
