### ISSUE TITLE
Constraints in skins are not included in the skin of a duplicated skeleton - [3.8.99 - 4.0.x] 

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#574]
When duplicating a skeleton, skin constraints are not included in the new skeleton.

Reproduction:
1. Create a transform constraint.
2. Place the constraint in a skin.
3. Duplicate the skeleton.
The transform constraint will not be included in the skin of the duplicated skeleton.

Link to original thread.
http://esotericsoftware.com/forum/3-8-99-Skin-constraints-missing-after-skeleton-dup-import-14714

**Comment by NathanSweet** [comment]
4.0.09-beta
