### ISSUE TITLE
Color Profiles gives unwanted results when using Export > Preview

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#575]
**Reproduction steps:**
1. Make sure that Spine is color managed. Blending type doesn't matter, can be either `Linear` or `Gamma`
2. Open `Windmill-ess`
3. Go to Export
4. Select `GIF`
5. Click `Defaults`
6. Click `Preview`
7. Now move the `Size` slider to around `150`, it's possible a little nudging up and down with the slider is required, but generally the higher the size, the easier the bug is to reproduce.

Note: When spine is not color managed, the error does not occur. The bug is also visible in exports.

**Expected reproduction result:**
![](https://i.imgur.com/REjozOg.png)

**Comment by NathanSweet** [comment]
4.0.37-beta
