### ISSUE TITLE
Pose tool does not create translate keys with Auto Key active

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#579]
As title says, Pose tool will not create translate keys with Auto Key active. Keys are only created when bones are rotated by the pose tool.

**Reproduction:**

1. Create a bone
2. Enable `Auto Key`
3. Drag the root of the bone, to translate, using the Pose tool - Note: no key is created.
4. Drag the tip of the bone, to rotate, using the Pose tool - Note: both translate and rotate keys are created now.

**Comment by NathanSweet** [comment]
4.0.28-beta
