### ISSUE TITLE
Antialiasing for image and video export

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#58]
http://esotericsoftware.com/forum/Anti-Aliasing-for-gif-avi-export-6465

Use [GL_EXT_framebuffer_multisample](https://www.opengl.org/wiki/GL_EXT_framebuffer_multisample) extension when available. LWJGL is [here](http://legacy.lwjgl.org/javadoc/org/lwjgl/opengl/EXTFramebufferMultisample.html), JGLFW has `GL#glRenderbufferStorageMultisample`.

**Comment by Bloodwork** [comment]
Yes please!

**Comment by NathanSweet** [comment]
All exports have had AA for some time now. Eg:
![](http://n4te.com/x/5400-aa.gif)

**Comment by NathanSweet** [comment]
Note that AA only makes a difference at the hard edges of region or mesh attachments. If images have whitespace at their edges, the aliasing will be avoided without needing multisample anti-aliasing.

**Comment by NathanSweet** [comment]
In 3.7.62-beta!
