### ISSUE TITLE
Importing data does not correctly scale region attachments if scale is not equal to 1

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#583]
When using `Import Data` and setting `Scale` to something other than `1` region attachments are not scaled with the skeleton.

Reproduction with Spineboy-pro
1. Export Spineboy-pro as JSON
2. Import the exported data using `Scale` = `2`.

Note that meshes have been scaled correctly but region attachments are too small.

**Comment by NathanSweet** [comment]
Spine uses the size from the actual image files for region attachments. It is not possible to specify the size of a region attachment in Spine. A region attachment can be scaled but the size at scale 1,1 is still based on that size of the image. If you import data with scaling you should provide images at the appropriate size.
