### ISSUE TITLE
Photoshop to Spine script creates "undefined" image when using [merge] tag.

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#585]
Exporting using the [merge] tag creates a single PNG file called "undefined" for the merged group.

Reproduction:
1. Create two layers and put them in a group.
2. Add the [merge] tag to the group.
3. Export using export script default settings.

The group using the [merge] tag will be exported as undefined.png

**Comment by Shiu** [comment]
This might also be affecting skins export, more information here: http://esotericsoftware.com/forum/PhotoshopToSpine-ProblemsTryingToMakeSkins-15311

**Comment by NathanSweet** [comment]
Fixed in latest script (version 5.8).
