### ISSUE TITLE
Unwanted keys are added on color timelines when alpha is keyed

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#586]
**Reproduction:**

1. In an empty project create a bone and parent a single attachment to the bone.
2. Go to `Animate` mode and key the `Slot` Color Alpha on Frame 0. Note that `Alpha` should NOT be separated.
3. Now key translation of the bone on frame 30. Note that a color key is now also keyed on frame 30. This does not happen if Alpha is not keyed.

**Comment by NathanSweet** [comment]
Unable to repro in 4.0.57-beta. Please reopen if you can repro!
