### ISSUE TITLE
Letting Spine create a slot for an attachment makes the draw order keyframes incorrect

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#588]
**The problem:**
Letting spine create the slot for you messes with the existing draworder keys, unlike manually duplicating or creating a slot.

**A try that works as intended: (expected result)**

1. open Spine in the latest beta, open Spineboy project
2. In animate mode, select the walk animation. in the walk animation key the draworder on frame 10 by moving the eye slot to be above the goggles slot then pressing the key next to the draw order node
3. In setup mode, duplicate the mouth slot
> the draw order in the walk still places the eye above the goggles
4. Delete the mouth2 slot
> the draw order in the walk still places the eye above the goggles

**Actual repro steps:**
open Spine in the latest beta, open Spineboy project
1. In animate mode, select the walk animation. in the walk animation key the draworder on frame 10 by moving the eye slot to be above the goggles slot then pressing the key next to the draw order node
2. In setup mode, expand the mouth slot, and **move the mouth-smile attachment  to be under the head slot.**
3. **Let spine automatically create mouth-smile slot**
> the draw order in the walk places the eye under the goggles, so it's incorrect
 5. Delete the mouth-smile slot
> the draw order in the walk places the eye under the goggles, so it's incorrect

**Comment by NathanSweet** [comment]
Fixed in 4.0.65-beta. Great find, that was tricky!
