### ISSUE TITLE
TexturePacker incorrect Aliasing

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#589]
TexturePacker incorrectly aliased mirrored images.

https://esotericsoftware.com/files/issues/589-TexturePackerAliasIssue.zip

**Reproduction:**
With the supplied project.
1. Export and pack with `Alias` enabled.
2. Open in SkeletonViewer and note the right hand side images have been flipped.
![](https://i.imgur.com/Wnb3rVj.png)

3. Export and pack with `Alias` disabled.
4. Open in SkeletonViewer and note that now the right hand side images are shown correctly.
![](https://i.imgur.com/My8bNHg.png)

**Comment by NathanSweet** [comment]
4.0.77-beta
