### ISSUE TITLE
Missing MeshAttachment in atlas with `Polygon` packing in 4.0.76

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-editor#594]
Reported on this forum thread, reproduction project included in first posting:
http://esotericsoftware.com/forum/Attachment-missing-in-Unity-15910?p=69635#p69635

The MeshAttachment image of the red axe is not included when the atlas is packed using `Polygon` packing mode.
It is correctly included when using packing mode `Regions`.

**Comment by NathanSweet** [comment]
4.0.77-beta
