### ISSUE TITLE
 Duplicating a bone that has a mesh with deform keys results in orange keys

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#595]
Duplicating a bone that has a child mesh with direct deformations results in orange keys: http://prntscr.com/13mkxhh
Moving the parent bone makes the keys be lost. 
It seems to me like the intended result after pressing "do you want to duplicate the keys .-> yes" would be to also create keys for this, so this makes it look like a bug.

Bug found in version: v3.8.99, v4+

Reference topic with repro video: http://esotericsoftware.com/forum/Mesh-deform-duplicate-keyframes-issue-15897

**Comment by NathanSweet** [comment]
When a bone is duplicated, any deform keys for any mesh would remained under the old bone, which is invalid. Fixed in 4.0.77-beta!
