### ISSUE TITLE
Bezier curve exported as `stepped`

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-editor#596]
Reported on the forum:
http://esotericsoftware.com/forum/4-0-78-Unity-Bone-translation-lost-in-Unity-runtime-15969
Reproduction asset received via email:
FMfcgzGkXmkFfhZssgJVctcmTQCBHrZC

Problematic animation is `Walk_1`, bone `Hip`:
Hip should be moving in an up and down motion, keyframes are all on same height but curve handles are used to create a sine-like shape. After export (both `.json` and binary) the Hip curve seems to be serialized as `stepped` instead of `bezier`. In Spine Editor everything is played back correctly, Graph Editor shows bezier curves and keyframe curve type. In spine-unity and SkeletonViewer the curve motion is missing.

```
animations ..
"Walk_1": {
    "Hip": {
        "translate": [
            {
                "y": 18.38,
                "curve": "stepped"
            },
            {
                "time": 0.6,
                "y": 18.38,
                "curve": "stepped"
            },
            {
                "time": 1.2,
                "y": 18.38
            }
        ]
    },
```

**Comment by NathanSweet** [comment]
4.0.79-beta
