### ISSUE TITLE
Import Data incorrectly imports all bones using the same root position, if no bone of the same name exists

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#598]
Reproduction

Using the attached projects:
1. Open tree.spine
2. `Import Data` > `File = branch.json` > `Import into an existing skeleton` > `Replace or ignore` > `Import`
The imported bones both have their root in the same position.

1. Open tree2.spine
2. `Import Data` > `File = branch.json` > `Import into an existing skeleton` > `Replace` > `Import`
Since tree2.spine has a bone called `branch1` the imported bones now have the correct positioning.

 [Reproduction assets](http://www.esotericsoftware.com/files/issues/598-importBug.zip)

**Comment by NathanSweet** [comment]
4.0.05
