### ISSUE TITLE
CTRL+SHIFT+S doesn't save the project with a new name

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#599]
Version: 4.0.17
pressing CTRL+SHIFT+S and choosing a new name and location doesn't save a new file. It instead keeps the old name and location and no new file is created.

Attempting to do the same from the Spine menu>Save project as... works as expected instead, so this problem is limited to the shortcut.

The problem is not present in v3.8.99

**Comment by NathanSweet** [comment]
4.0.18
