### ISSUE TITLE
Error on startup when restarting after change to QWERTZ

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-editor#6]
![http://libgdx.badlogicgames.com/uploads/Screen%20Shot%202016-05-23%20at%2019.18.00-CpMFqtJCBv.png](http://libgdx.badlogicgames.com/uploads/Screen%20Shot%202016-05-23%20at%2019.18.00-CpMFqtJCBv.png)

Changed to QWERTZ in last session, never touched `hotkeys.txt` as i don't know where that file is located. Got this error message after restart. Error persists on subsequent restarts.

Changing back to QWERTY fixes the issue.

**Comment by NathanSweet** [comment]
3.5.33
