### ISSUE TITLE
Export skeletons "Separate" does not ignore hidden skeletons.

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#601]
Problem: when exporting images or video using `Separate` only visible skeletons should be exported, but hidden skeletons are also exported.

Reproduction:
1. In a project with 2 or more skeletons hide one of the skeletons.
2. Go to `Export` choose `GIF` export. Then check `Separate`.
3. Now Export.

Tooltip for `Separate` says `Render each visible skeleton separately`.

**Comment by NathanSweet** [comment]
Fixed for both separate and together, 4.0.21.
