### ISSUE TITLE
Incorrect path replacement for "rename attachments" when dplicating a skin

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#605]
**Steps:**

- Open mix and match project, sleect full-skins/girl in the skins node and duplicate it.
- In the toast check "rename attachments" and name the skin "girl-alt" 
![](https://www.erikari.it/uploads/1116-G4A5.png)

**Actual result:**
- The names of the new skin are path + skin placeholder name 
![](https://www.erikari.it/uploads/1117-eR2v.png)
This causes errors if the skin placeholders were renamed, or the actual attachments.

**Expected:**
- The name grabbed should take the actual attachment path, and change the folder path to the new path.
(this can be done using find and replace, as in the example image)
![](https://www.erikari.it/uploads/1118-NSXk.png)

**Comment by NathanSweet** [comment]
@erikari Are you sure we want to use the attachment name, strip off any folders, and prepend the skin name? For example:

**Placeholder:** `eye-back-white`
**Attachment before:** `girl/eye-white-back`

After duplicating the `girl` skin to `girl-alt`:

**Attachment after:** `girl-alt/eye-white-back` (previously this was the placeholder name: `girl-alt/eye-back-white`)

That seems OK, but what about a few different situations:

**Attachment before:** `girl/eye/white-back`
**Attachment before:** `eyes/girl/white-back`

After duplicating, what should the new attachment names be? If we strip all folders, we get:

**Attachment after:** `girl-alt/white-back`
**Attachment after:** `girl-alt/white-back`

We could instead search for the old skin name `girl` and replace it (smartly, so it isn't matched in the middle of other words). Then we'd get:

**Attachment after:** `girl-alt/eye/white-back`
**Attachment after:** `eyes/girl-alt/white-back`

That seems best. However, what do we do if the old skin name cannot be found? For example, before duplicating:

**Attachment before:** `eyes/white-back`

I think in that case we can just keep it all and prepend the skin name:

**Attachment after:** `girl-alt/eyes/white-back`

@erikari All this sound good?

**Comment by NathanSweet** [comment]
One last thing: we do the above, using the old attachment name, and we ignore any path the attachment has set. After setting the new name, we clear the path.

An attachment under a skin placeholder has no name uniqueness restrictions, so it's not very useful to use a path there. Using the name is a bit better, as it's easier to see. In the case that a path is set for some godawful reason, what should we do? We could apply the same replacements to the path that we do to the name.

**Comment by NathanSweet** [comment]
4.0.38
