### ISSUE TITLE
Can't drag attachment on to slot

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#607]
**Repro steps:**

- open the project mix and match in the latest beta
- select the girl/scarf mesh
- click and hold to see where you can release it

Expected: slot "scarf" should be a drop target
Actual: slot "scarf" is disabled so I have to release it on the slot neck and back in the scarf slot to be able to place it there.

**Reference topic:**
http://esotericsoftware.com/forum/4-1-Beta-Can-t-drag-attachment-on-to-slot-16557

Afftected version: 4.1 beta. 
4.0> doesn't show this behavior.

**Comment by NathanSweet** [comment]
4.1.05-beta
