### ISSUE TITLE
[4.1.04-beta] Bug : All mesh attachment keys will be removed even if you reset only a single mesh

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#609]
4.1.04-beta has a bug that all mesh attachment keys will be removed even if you reset only a single mesh. Here is the repro video

https://user-images.githubusercontent.com/85478846/138810057-0cc1e8d7-bbeb-47a2-a5dc-e8ac54ce1730.mov

This bug was reported in this post: [http://esotericsoftware.com/forum/4-1-04-FFD-keys-breaking-glitch-16597](http://esotericsoftware.com/forum/4-1-04-FFD-keys-breaking-glitch-16597)
:

**Comment by NathanSweet** [comment]
4.1.04-beta
