### ISSUE TITLE
[PhotoshopToSpine] v7.09 does not apply adjustment layers

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#610]
PhotoshopToSpine v7.09 and a version from 22nd September 2021 do not correctly apply adjustment layers.

This problem was reported here:
http://esotericsoftware.com/forum/PhotoshopToSpine-script-does-not-apply-adjustment-layers-16606

**Comment by NathanSweet** [comment]
In 7.12 we don't delete adjustment layers and we hide layers instead of deleting them. If we were to delete a layer, any clipped adjustment layers would be applied to the next layer, so we hide instead.
