### ISSUE TITLE
Deleting skin with only bones in it prevents the project from saving

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#612]
**Repro steps:**
1. open the project:
2. delete the skin Outfit/RiniSma
3. press ctrl+s to attempt to save the file
>result: a toast appears saying that an error has occurred and the file is not saved.

>ERROR: Unable to save project: Nera_Spine 03-11-2021 14.00.spine
>Errors prevent the project from being saved.
>Please tell us what actions you've taken since the last save: contact@esotericsoftware.com

The error does not appear if the one bone inside the skin is removed from the skin before deleting it.

**Reference email and project:**
FMfcgzGlkjZKBLzbhXcrzgFqMtxGqlkC

**Comment by NathanSweet** [comment]
4.0.46
