### ISSUE TITLE
The size of the region in the exported texture may change depending on whether the resample setting is set to bilinear or bicubic.

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#614]
In Spine editor v4.0.49, the size of the regions in the exported texture may change depending on whether the resample setting is set to bilinear or bicubic, even though the same scale value is set.

A user has provided the repro project for this problem:
[blue mountain 10.zip](https://github.com/EsotericSoftware/spine-editor/files/7585304/blue.mountain.10.zip)
[http://esotericsoftware.com/forum/Issue-with-bilinear-filtration-in-Spine-4-0-16708](http://esotericsoftware.com/forum/Issue-with-bilinear-filtration-in-Spine-4-0-16708)

In this reproduction project, the problem always occurs when the scale is 0.48. However, changing the value of the scale may or may not cause problems. I tried the following scale values:
Scale 0.47 : OK
Scale 0.48 : The size difference occurs.
Scale 0.49 : The size difference occurs.
Scale 0.5 : OK

**Comment by NathanSweet** [comment]
4.0.51
