### ISSUE TITLE
Export+pack for 3.8 using Spine 4 to bypass memory limits

### ISSUE THREAD

**Issue by cloutsocks** [EsotericSoftware/spine-editor#617]
Continuing from #616 since I can't re-open an issue closed by a collaborator

Is there a way to pack with 4.0 for 3.8 (bypassing the memory error) using the spine file? Rather than a specific folder of images.

Like can I simply do a 4.0 binary export with legacy output on the packer setting and then do a 3.8 binary output overwriting the .skel.bytes and it works?

**Comment by NathanSweet** [comment]
If you need to reopen an issue, you can just comment on the issue and we will see it and respond or reopen as needed. However, let's please move questions to the Spine forum, reserving the issue tracker only for bugs.
