### ISSUE TITLE
[PhotoshopToSpine] v7.15 shows an error asking layers in groups using [folder] tag to use [skin] tag even if you don’t want to apply them to any skin.

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#619]
In specific cases, v7.15 shows an error asking layers in groups using [folder] tag to use [skin] tag even if you don’t want to apply them to any skin.

This error is reported in this post:
http://esotericsoftware.com/forum/photoshop-to-spine-16819

Here is a PSD to reproduce the error.
[reproPSD_skinTagError_v7-15.zip](https://github.com/EsotericSoftware/spine-editor/files/7731946/reproPSD_skinTagError_v7-15.zip)

**Comment by NathanSweet** [comment]
7.16
