### ISSUE TITLE
"Animation clean up" may change the interpolation between keys which have the same value depends on the curve.

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#620]
Even if the keys on a timeline have the same value, "Animation clean up" may delete the necessary key to keep the curve's  shape, then the interpolation will be changed when the previous or the later key is Bezier and separated.

You can reproduce this issue with the following steps:
1. Key the rotation value of a bone on frame 0, 10, 20, 30, 40, and 50. (These keys' values are the same)
2. Change the value of the key on frame 10 and 50.
3. In the Graph view, change the curve type of the key on frame 20 and 40 as `Sepatated`.
4. Use the `Clean Up` button on the Tree view for the animation, then you can see the key on frame 30 is deleted and the interpolation between the keys on frame 20 and 40 is changed.

This issue is reported in this forum post:
http://esotericsoftware.com/forum/viewtopic.php?f=9&t=16828

Here is the repro project:
[reproProject_animation-clean-up.zip](https://github.com/EsotericSoftware/spine-editor/files/7743690/reproProject_animation-clean-up.zip)

**Comment by NathanSweet** [comment]
4.0.56
