### ISSUE TITLE
Path constraint sliding bar cannot be dragged if the numeric entry is in focus

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#621]
In Spine 4.1 Beta, if you move the sliding bar when entering the position value of a path constraint, the sliding bar does not move. You have to click to make it move.

![](https://www.erikari.it/uploads/1145-sliding-bar-bug-path.gif)

Related thread:
http://esotericsoftware.com/forum/4-1-path-constraint-bug-16844

**Comment by NathanSweet** [comment]
4.1.10-beta
