### ISSUE TITLE
Event duplication in Animate mode causes rename bug

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#623]
If `Ctrl+D` is pressed on an event in animate mode, duplicating said even in setup mode causes the original to be renamed alongside the copy using the same name.

It can be reproduced on any example project too. Or also simply performed on the Spineboy Footstep event.

**Steps:**
1. **Open a project and switch to Animate mode**
2. Select the Events node in the tree, choose New>Event and call the new event `test1`
3. **Select `test1` and press `Ctrl+D`** (nothing happens)
4. Go back to Setup mode and press `Ctrl+D` (a copy is made)
5. Rename the copy and also the original event is renamed.

Note: if the lines in bold are not performed, the bug does not happen, so the key is to try to duplicate while in Animate mode.

**Repro video and reference topic:**
http://esotericsoftware.com/forum/Editor-Event-duplication-rename-bug-16864

**Comment by NathanSweet** [comment]
4.1.10-beta
