### ISSUE TITLE
[4.0.57] Binding a mesh to a bone which is not its parent will make unintentional translation and rotation.

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#624]
In 4.0.57, when a mesh is bound to a bone other than its parent, it has a strange effect on the rotation and translation of the bound mesh. 

Here are the reproduction steps:
1. Put an image under the `root` bone and turn it to a mesh attachment. (You don't need to edit the mesh vertices.)
2. Create a bone under the `root` bone.
3. Bind the mesh to the bone, then you will see the mesh will be translated or rotated.

This issue is reported on the following posts:
http://esotericsoftware.com/forum/viewtopic.php?f=17&t=16944
http://esotericsoftware.com/forum/viewtopic.php?f=9&t=16946

Here is the repro project:
[MeshBindingIssue_4-0-57.zip](https://github.com/EsotericSoftware/spine-editor/files/7887385/MeshBindingIssue_4-0-57.zip)

**Comment by NathanSweet** [comment]
4.0.58
