### ISSUE TITLE
can will add differents interpolation of curve ?

### ISSUE THREAD

**Issue by manuelsongokuh** [EsotericSoftware/spine-editor#625]
hi

i see maybe missing is add curve for interpolation: bounce, elastic, shake, pluse random, electric, etc in curve/interpolation generator?

see example by blender:
![4hY3p](https://user-images.githubusercontent.com/12126929/150004067-d60c80ed-6821-433d-abb1-71f91b7468da.png)

**Comment by manuelsongokuh** [comment]
https://www.youtube.com/watch?v=yrwL0l3S11U

**Comment by NathanSweet** [comment]
We don't have plans for other interpolation types. All of those can be created using Bezier.

Please note this issue track is for problems with the Spine editor. Please you use the Spine forum for general discussion.
