### ISSUE TITLE
[4.1.14-beta]Pinned skins are not displayed correctly on the Preview view in a specific case

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#627]
In a specific case, pinned skins are not displayed correctly on the Preview view when the Setup mode is selected. This problem does not occur if you do not use the Skins view to pin, but simply activate that skin. Also, using pins is no problem in the Preview view if ANIMATE mode is selected. 

The reproduction project and the recording of the bug are shared on Slack due to confidentiality.

This problem is reported in this post:
http://esotericsoftware.com/forum/4-1-14-beta-16984

**Comment by NathanSweet** [comment]
4.1.16-beta
