### ISSUE TITLE
[4.0.59/ 4.1.16-beta] IK Compress is not being applied in specific cases

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#628]
If you export using the JSON format, IK Compress is not being applied when you set the Mix of the IK constraint to zero in Setup mode and then increase the Mix in animations. (Even in that case, the behavior of pointing to the target bone works.)
It is confirmed that the same results were reproduced when the JSON files exported from 4.0.59/ 4.1.16-beta were viewed in Skeleton Viewer. 

The Spine project and exported files for reproduction are here:
[IK-Compress.zip](https://github.com/EsotericSoftware/spine-editor/files/7982829/IK-Compress.zip)

This problem is reported in this topic:
http://esotericsoftware.com/forum/Unity-IK-17018

**Comment by NathanSweet** [comment]
4.0.60
