### ISSUE TITLE
Exporting multiple skeletons using the same images to a single atlas results in duplicate images

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#630]
**Description:**
If multiple skeletons within the same project use the same images from the same images folder and the option "pack image folders to single atlas" is chosen, duplicates are created.

**Expected:**
The images should be packed once as when texture packer is run.

**Repro project:**
Choose the BG-duplicator.spine project in the zip from mail FMfcgxwBVWQNQRkGqdBLCDfxdjkzQdnL

**Steps:**
1. Open the BG-duplicator.spine project
2. Spine>Export>Binary> option pack "image folders" to "single atlas" and export
> Duplicates images are present 
Use Spine>Texture Packer instead to see the correct and expected behavior on export.

**Version where this was tested and the bug is found:**
v 3.8.99, v 4.0.59.

**Comment by NathanSweet** [comment]
4.0.60
