### ISSUE TITLE
If transform constraints have Offset-ShearY to -180 or 180, increasing shear Mix rotates the attachments.

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#631]
**Description:**  
If you add a transform constraint and the difference between the rotation of the constrained bone and the target bone is more than 90 degrees, the Match button sets the offset of the Shear Y to -180. In that case, increasing the Mix of the shear rotates the attachments. 

**Expected:**  
If the offsets are set using Match, increasing the Mix will not move the bones or attachments.
Or, Shear Y keeps 0 when the target bone is not sheared and the Match button is used.

**Repro project:**  
[Shear-Offset-makes-rotation.zip](https://github.com/EsotericSoftware/spine-editor/files/8013060/Shear-Offset-makes-rotation.zip)

**Steps:**
1. Open the repro project and select the "transform-constraint" in 4.0.60 or 4.1.17-beta.
2. Dragging the Mix slider of the Shear Y, and you can see the attachment is rotated.

Here is a video that captures the problem:
https://drive.google.com/file/d/19lbNExFU7VImTF-9Hxqb1BJEX2boSQKI/view?usp=sharing

**Version where this was tested and the bug is found:**  
v3.8.99, v 4.0.60, v 4.1.17-beta

**Comment by NathanSweet** [comment]
4.0.62
