### ISSUE TITLE
Improve the bone selecting order after splitting a bone

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#632]
After splitting a bone using the `Split` button, the bones are selected including the new bones, but the last one generated will come first in the selection order, e.g. 1, 4, 3, 2.
This is not a problem in most cases, but if you bind with a path constraint immediately after splitting the bones, the order in constraint will be wrong.
![Screen Shot 2022-02-09 at 10 52 48](https://user-images.githubusercontent.com/85478846/153106817-15cde75e-2e11-46c8-935e-5d5957e39301.png)
Therefore, the order of selection should be correct, like 1, 2, 3, 4.

**A video recording of this issue**
https://youtu.be/y61QDkwAt8o

This issue was reported on the forum:
http://esotericsoftware.com/forum/path-constrain-bug-17050

**Comment by NathanSweet** [comment]
In 4.1.21-beta I see the constrained bones as 4,3,2,1. That's OK, but 1,2,3,4 seems better. I've made that change.
