### ISSUE TITLE
Deleting an animation by Undo is not immediately reflected in the list in Preview view

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#633]
**Description:**
If you delete an animation by Undo, it will be reflected immediately in the Tree view and Animations view, but not in the animation list in the Preview view. The animation that was supposed to be deleted by Undo will remain until any existing animations are deleted or renamed.

**Expected:**
When an animation is deleted by Undo, the list in the Preview view will be updated at the same time as the Tree view and Animations view.

**Steps:**
1. Open the Preview view. 
2. Create a new animation.
3. Press the Undo button.
4. You can see that the list of animations is updated in the Tree view, but not in the Preview view.

**Version where this was tested and the bug is found:**
v 4.0.61, v 4.1.20-beta

**Comment by NathanSweet** [comment]
4.0.62

Good find, this is likely the cause of some mystery crashes!
