### ISSUE TITLE
Folders for draw order

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#635]
Add folders to make Draw order more manageable.

Related forum posts:
http://esotericsoftware.com/forum/Folder-to-draw-order-13396
http://esotericsoftware.com/forum/Suggestion-Draw-Order-Groups-Folders-for-independent-keys-17172

**Comment by WArmanW** [comment]
+1

**Comment by FabianoIlCapo** [comment]
Would be great!
+1

**Comment by NathanSweet** [comment]
I agree, it is a good suggestion that goes beyond simple grouping with folders. It's complex, but we'll do it in time.

**Comment by misaki-eymard** [comment]
+1 here: http://esotericsoftware.com/forum/x-17407

**Comment by bencresty** [comment]
+1
Please also add folders to constraints. Working on a project now with lots of different characters in the same scene, each having their own list of constraints. We only animate one character with its constraints at a time, so we'd like to hide the constraints of other characters in the tree. If each character would have its own folder inside constraints we could collapse the folders we're not using at the moment.

**Comment by NathanSweet** [comment]
We finally have folders for both draw order and constraints in 4.2!
