### ISSUE TITLE
Add an option to replace existing animations on Import Animation

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#636]
Currently, if animations that have the same names with the existing animations when importing them via `Import Project...` in the Spine menu, they will be automatically renamed. However, this behavior is troublesome if you want to replace rather than add animations. Adding a `Replace` option on the Import Animation window should make it easier.

Related post:
http://esotericsoftware.com/forum/Import-project-animations-17182

**Comment by NathanSweet** [comment]
4.1.22-beta
