### ISSUE TITLE
Shear handles can't be grabbed correctly in a specific case

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#637]
**Description:**
If a bone is constrained by transform constraints, the bone’s shear handle will only be able to grab one side of the bone.

**Expected:**
Can grab both shear X/Y handles even when the bone is constrained by transform constraints.

**The project for reproducing the bug and the screen recording**
[Shear-handles-can't-be-grabbed-correctly.zip](https://github.com/EsotericSoftware/spine-editor/files/8194303/Shear-handles-can.t-be-grabbed-correctly.zip)

**Steps:**
1. Open the attached project above.
2. Select the shear tool, and try to change the shear X/Y of the bone "bone". Then, you will see you can only grab the one side of the shear handles.

Also, you can see that removing the transform constraint allows you to grab the handles correctly.

**Version where this was tested and the bug is found:**
v 4.0.61, v 4.1.20-beta

**Comment by NathanSweet** [comment]
4.0.62
