### ISSUE TITLE
Duplicate Korean language characters are generated in the Spine Editor dialog boxes

### ISSUE THREAD

**Issue by lukeeingram** [EsotericSoftware/spine-editor#639]
A user has posted in the forum that the Spine Editor will generate duplicate characters multiple times when Spine's language is set to Korean, while their input language is also Korean. I was able to reproduce the bug by utilizing the following steps:

1. Verified that I was on the most up-to-date Spine Launcher (4.1.04) and the latest stable version of the Spine Editor (4.0.62).
2. Opened Spine and tested inputting characters in English into Spine's dialog boxes, specifically the Open Project dialog box.
3. Opened the Windows 10 Settings menu and changed my computer's input language to Korean.
4. Opened Spine again, changed the language to Korean, and then restarted Spine.
5. Opened the Open Project prompt, and typed Korean characters into the "Filter" field.

Link to the user's post: http://esotericsoftware.com/forum/Problems-entering-text-17259?p=75722#p75722

**Comment by lukeeingram** [comment]
Another customer has demonstrated this issue when attempting to input Hangul into Spine.
http://esotericsoftware.com/forum/x-17498?p=76775#p76775

Furthermore, they also have also stated that the same field also contains an issue where the same field does not register any input whatsoever.

**Comment by NathanSweet** [comment]
Fixed in 4.1.27-beta via #654.
