### ISSUE TITLE
Preview multiple tracks for animation playback

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#64]
If the editor showed animations mixed and layered it would be easier to adjust them for how they will be rendered at runtime.

**Comment by Xelnath** [comment]
Upvoting! This would make a huge difference for my animator.

**Comment by mishaelfedorov** [comment]
Up!

**Comment by Bloodwork** [comment]
If it allows to layer 2 or more animations together and then export as a GIF then I severely need this.

**Comment by NathanSweet** [comment]
3.6.22-beta
