### ISSUE TITLE
CLI project import clears image files path

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-editor#640]
Reported on the forum:
http://esotericsoftware.com/forum/Reduce-drawcalls-for-separate-spine-projects-17266

The following line imports the project, but the `Image Files` `Path` is empty in the imported project.
```"$SPINE_EXE" -u 4.1.22-beta -i spineboy/spineboy-pro.spine -o combined/combined.spine -r```
Occurs with 4.1-beta and 4.0.

**Comment by NathanSweet** [comment]
4.1.10
