### ISSUE TITLE
The UI of 4.1.23-beta is displayed double overlapping in some languages

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#641]
The UI of 4.1.23-beta is displayed double overlapping in some languages like the following images.
Chinese:
![Chinese UI in 4 1 23-beta](https://user-images.githubusercontent.com/85478846/160322918-d7975ff4-fa7d-4715-b169-10fecfc14f88.png)
Korean:
![Korean UI in 4 1 23-beta](https://user-images.githubusercontent.com/85478846/160322317-95dc69ab-6a4e-40ff-b9cb-a8bb8e85fc35.png)
Japanese:
![Japanese UI in 4 1 23-beta](https://user-images.githubusercontent.com/85478846/160322330-f4ec200f-549d-46a1-998e-973ce370e8eb.png)

This bug is reported here:
http://esotericsoftware.com/forum/UI-17304

**Comment by badlogic** [comment]
Fixed in latest libGDX commits. Need to release a new editor build with the update libGDX native libs.

**Comment by NathanSweet** [comment]
4.1.24-beta
