### ISSUE TITLE
Texture Packer creates a smear when the atlas is packed

### ISSUE THREAD

**Issue by lukeeingram** [EsotericSoftware/spine-editor#644]
A user has sent us their Spine project file, and written a forum post in regards to this issue. When they pack their texture atlas, their helmet asset is smeared. 
I was able to reproduce this issue in the Spine Editor, versions 4.0.51, 4.0.63, and 4.1.25-beta.

Link to the forum post: http://esotericsoftware.com/forum/Bug-with-sprites-exported-since-4-0-51-16810

**Comment by NathanSweet** [comment]
4.1.03
