### ISSUE TITLE
Exporting multiple projects in parallel via CLI requests activation code

### ISSUE THREAD

**Issue by lukeeingram** [EsotericSoftware/spine-editor#645]
A user has posted in our forums stating that they are unable to export multiple projects in parallel as Spine is requesting an activation code if they are running multiple commands for Spine to export via CLI. They have referenced an older thread where a very similar issue occurred and was resolved.

Link to the user's post: http://esotericsoftware.com/forum/Spine-17362?p=76197#p76197
Link to post where issue was resolved: http://ja.esotericsoftware.com/forum/Spine-requests-reactivation-16171

**Comment by lukeeingram** [comment]
Their Spine log can be found in their post, linked above.

**Comment by NathanSweet** [comment]
Fixed in launcher 4.1.07!
