### ISSUE TITLE
Adjusting curve handles of keys on the end frame may cause crashes

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#648]
Description:
After certain steps, Spine crashes when you try to adjust the curve handles of keys on the end frame.

Here is the project for reproducing the bug and the screen recording:
[Adjusting_curve-handles_on_the_end_frame_may_cause_crashes.zip](https://github.com/EsotericSoftware/spine-editor/files/8596663/Adjusting_curve-handles_on_the_end_frame_may_cause_crashes.zip)

Steps:
1. Open the attached project above.
2. Select all rotate keys on both of the "bone1" and "bone2". (It is probably essential to select two or more bones' keys at the same time; I could not reproduce the crash with just one.)
3. Click the `Automatic` button many times on the Graph view. (About 30 - 40 clicks are needed.)
4. Adjust the curve handles of keys for both bones on the end frame. 
5. It should crash when you finish adjusting one bone and try to adjust the other. If it does not crash, try adjusting the handle again after clicking the `Automatic` button two or more times.

Version where this was tested and the bug is found:
v 4.1.26-beta

**Comment by NathanSweet** [comment]
After a looot of searching, I found an easier repro:

- Select the topmost handle past the animation duration.
- Mouse over the handle just below that one and drag. The drag must happen very soon after moving the mouse over the bottom handle.
- Crash!

**Comment by NathanSweet** [comment]
After a looot of searching, I found a 100% repro:

- Click to select the top handle after frame 45.
- Mouse over the bottom key on frame 45, placing the mouse still over but just below the key.
- Slowly move the mouse right until the handle after frame 45 for the bottom key turns white.
- Move the mouse left 1 pixel so the key is hovered again.
- Press and hold the mouse. It should look like:
![](http://n4te.com/x/4969-76s1.png)
- Drag the mouse: Crash!

**Comment by NathanSweet** [comment]
4.1.27-beta
