### ISSUE TITLE
Displaying brush circle remains after using “Brush Decrease” hotkey

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#650]
Description:
Pressing the “;” key shows a circle which indicates the current brush size of the mesh tool, but it remains in the viewport even if you perform another operation.
<img width="974" alt="Brush-circle-remains" src="https://user-images.githubusercontent.com/85478846/168190886-c71c08ec-473d-4e53-906a-c1953587d451.png">

Steps:
Press the ";" key immediately after starting Spine.

Workaround:
The circle display disappears when open the Mesh Tools view. However, if the ";" key is pressed again after closing the Mesh Tools view, this issue recurs.

Version where this was tested and the bug is found:
v 4.1.26-beta

This issue was reported in this forum post:
http://esotericsoftware.com/forum/spien-a-circle-appears-in-the-center-of-spine-17463

**Comment by NathanSweet** [comment]
4.1.27-beta
