### ISSUE TITLE
Export fails when there is no display

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#652]
**Description:**
If you attempt to perform data export or texture packing via the CLI when there is no display, the export may fail.

**Expected result:**
Data export and texture packing can be done without a display connection.

**Version where the issue was found:**
v 3.8.99

**Related post:**
http://esotericsoftware.com/forum/MacMini-V3-8-CLI-17534?sid=c89340cb5c32f5de596f10ba4856c5ba

**Comment by NathanSweet** [comment]
Does this occur in 4.1? What is the `spine.log` when running with `--trace`?

**Comment by misaki-eymard** [comment]
No, this error does not occur in 4.0 and 4.1. However, the user who reported this issue wants to export using 3.8.99. I have tested this using the shell script provided by the user, and if my MacBook goes to sleep or something while the export is running, I get the following logs.
[spine.log](https://github.com/EsotericSoftware/spine-editor/files/8887762/spine.log)
[hs_err_pid47906.log](https://github.com/EsotericSoftware/spine-editor/files/8887763/hs_err_pid47906.log)

In 4.0 and 4.1, if the PC goes into sleep mode during the export process, the export will stop, but it will not cause any error, and the export will resume after a restart and export correctly.

**Comment by NathanSweet** [comment]
If the problem is occurring in the part of the software that the launcher controls then we'd have a chance at fixing it, but the problem is in the 3.8 code itself and would require a new 3.8 release. Since we don't do any more 3.8 updates, unfortunately we aren't able to fix this.
