### ISSUE TITLE
Chinese Pinyin input repeats the last character 

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#654]
**Description:**
If you try to enter the name of any tree items using Chinese Pinyin input, the last character is repeated, e.g. 文字字字字字字字字字字字字.
![chinese-input-bug](https://user-images.githubusercontent.com/85478846/172971299-131678ea-8173-4cfe-bb72-23dad7d93ae4.gif)

**Expected result:**
Only the characters entered on the keyboard are entered on Spine; the last character is never repeated.

**Steps to reproduce:**
Note that this problem has so far only been reproduced on Windows PC.
1. If Chinese has not been added to your keyboard settings, please add it. (Chinese Simplified)
2. Switch the input method to Chinese. 
3. Try to rename any tree items, then you can see the last character repeats after pressing the Enter key. 
(Although the input method must be Chinese, this problem occurs even if English characters are entered.)

**Version where this was tested and the bug was found:**
v 4.0.64 / v 4.1.26-beta

This problem was reported in this post:
http://esotericsoftware.com/forum/Spine-currently-has-a-bug-about-naming-In-chinese-17588

**Comment by NathanSweet** [comment]
4.1.27-beta

**Comment by Paperman3334** [comment]
Although this issue was fixed in version 4.1.27, many projects are still using the version with this issue. It is very difficult for a project to change the spine version, so this issue has not been solved at all.

**Comment by NathanSweet** [comment]
Unfortunately it is not easy to go back to older versions and make changes/fixes. Doing that risks something breaking and that can disrupt both users and our development team. Generally once we move development to a newer version, we don't make changes to older versions.

Updating the Spine version is easy if you setup scripts to export your projects, which has other benefits. We provide scripts to help:
https://esotericsoftware.com/blog/New-export-shell-scripts

**Comment by Paperman3334** [comment]
Replacing the spine version is very difficult, not just replace the spine file, but also need to replace a lot of plug-ins and program code related to the program, and, a lot of plug-ins, etc. and spine related programs, do not support the new spine version, this is a very large project, and it is not something I can decide as an animator.

**Comment by NathanSweet** [comment]
I appreciate the difficulty of changing an existing project. It is possible and newer versions bring many benefits -- thousands of improvements beyond just the IME fix. Still, I'm afraid we can't risk updates to older versions.
