### ISSUE TITLE
Add an override option to IK constraints

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#659]
Decreasing IK Mix to 0 during animation corrects the bone's rotation according to its original rotation value, which may be convenient, but in some cases not. For example, if you want to create a movement that raises the arm after placing the hand on the desk, you would use IK while the hand is on the desk, but when the arm is raised, you would disable IK by setting its Mix to 0. However, when the IK Mix is decreased, the angle of the arm will not be appropriate as the midpoint of the animation, and it may be difficult to make a smooth movement. It would be useful to add an override option whereby the IK will also override the original bone rotation values.
![IK-override](https://user-images.githubusercontent.com/85478846/176803275-46259645-a77f-432c-a747-84c3ddf1fc69.gif)

Related post:
http://esotericsoftware.com/forum/viewtopic.php?f=11&t=17668

**Comment by NathanSweet** [comment]
I'm not sure I understand. An IK constraint already overrides the unconstrained bone rotation. It wouldn't make sense for the IK constraint to continue to affect the unconstrained rotation when the IK constraint mix is 0. The mix controls whether you get the unconstrained rotation (0), the IK constrained rotation (100), or somewhere between (0-100).

To do what you want, you would key the bone rotation to match the rotation given by the IK constraint, then set the IK constraint mix to 0 (or < 100). You can key the unconstrained rotation to match the IK constrained rotation by keying the bone rotation when the IK constraint mix is at 100.

**Comment by misaki-eymard** [comment]
> You can key the unconstrained rotation to match the IK constrained rotation by keying the bone rotation when the IK constraint mix is at 100.

Oh, sorry I didn't know that! So, this function is not necessary.

**Comment by NathanSweet** [comment]
Yep! It can be pretty useful. You can even use it to "bake" a constraint into keys by applying a constraint, then setting a key every frame, or every few frames. You could then delete the constraint and achieve similar results using the keys.
