### ISSUE TITLE
Spine doesn't start without internet, so we cannot work

### ISSUE THREAD

**Issue by bencresty** [EsotericSoftware/spine-editor#660]
Spine loader 4.1.05 doesn't start Spine 4.1 when there is no internet connection.

When either having issues with internet, we are working on places where there is no internet or for whatever other reason we cannot use internet (for example when we're on the road), Spine should also be able to work offline.
The only reason IMO to need internet is to check for updates. But it can do that enough times when there is an internet connection.

A license check shouldn't be needed either as that's already done when it was installed and only should check it if necesary when upgrading.

If I'm not mistaken internet connection wasn't required to start Spine in earlier versions.

Please make Spine be able to work offline (again?)!!! It's too critical now we cannot continue to work here, just because we don't have an internet connection that we shouldn't need to run local software.

Thanks in advance!!

![Screenshot 2022-07-05 195438](https://user-images.githubusercontent.com/69322733/177388250-f0cf8028-4b85-4d8c-ae5e-24d3ae27cfb2.jpg)

**Comment by NathanSweet** [comment]
Spine can start without an internet connection, but only if it has previously downloaded an update file and you are not running Spine inside a VM. That should be true for all Spine launcher versions.

Please make sure that you see an update file there for the version you are attempting to run. When Spine doesn't find the update file, it tries to download it and will give an error message similar to what you've shown. You can view your update files in the `updates` folder here:
http://esotericsoftware.com/spine-troubleshooting#User-files

**Comment by bencresty** [comment]
> Spine can start without an internet connection, but only if it has previously downloaded an update file and you are not running Spine inside a VM. That should be true for all Spine launcher versions.
> 
> Please make sure that you see an update file there for the version you are attempting to run. When Spine doesn't find the update file, it tries to download it and will give an error message similar to what you've shown. You can view your update files in the `updates` folder here: http://esotericsoftware.com/spine-troubleshooting#User-files

Looking in the updates-folder in the folder you gave there are lots of update files, all the previous versions of v4 and also the new 4.1 versions (including the betas). I also had already downloaded the latest update file AND am running the latest loader if it didn't change last night. 

I was working in Spine all day without issue, but after a restart of the PC and so a restarted Spine the internet connection was gone (probably due to an update the cable guys are doing today), which shouldn't be an issue for Spine, but then it wouldn't load because of this lack of connection.

Now that the internet connection is back it's working again. But it didn't install a newer version, so according to what you write it should've worked when the internet connection was offline too. But it didn't. So I guess there's something not quite right there?




I'm not running Spine from within a VM. I'm running it directly in Windows 10.

**Comment by NathanSweet** [comment]
Yes, it does sound like something is not right. Can you please post your [spine.log file](http://esotericsoftware.com/spine-troubleshooting#spine.log)? When posting the file here, please first delete your name and email address from the text file. When posting on the forum that is done automatically, but not on GitHub.

**Comment by bencresty** [comment]
> Yes, it does sound like something is not right. Can you please post your [spine.log file](http://esotericsoftware.com/spine-troubleshooting#spine.log)? When posting the file here, please first delete your name and email address from the text file. When posting on the forum that is done automatically, but not on GitHub.

There's nothing in the log other than system information, like processor type (which on this computer is AMD64), that I'm using an Nvidea, OpenAl 1.1 and a default audio card and the fact that I'm running spine 4.1.1 (now 4.1.2) with loader 4.1.05. Nothing more. No errors, no warnings or whatever.

**Comment by NathanSweet** [comment]
We'd still like to see your `spine.log` file to be 100% sure. You can email it, if that is easier: contact@esotericsoftware.com

**Comment by NathanSweet** [comment]
By chance one of my colleagues suddenly had this exact problem today. We dug into it and it was quite the rabbit hole. Something is causing Windows to start all processes in [Hyper-V isolation](https://azure.github.io/AppService/2020/09/29/Security-for-Windows-containers-using-Hyper-V-Isolation.html) mode. That is done for security reasons but may have performance implications and it causes Spine to fail to run if there is no internet connection.

The user had recently installed some games: Squad and Battlefield 4. Why did they install games on a work computer? Great question! Anyway, Squad uses Easy Anti Cheat and BF4 uses PunkBuster. It's not clear if these anti-cheat programs caused the problem, but it's suspect that the problem began after installing them. Unfortunately uninstalling them did not fix the problem.

We haven't been able to identify what was changed in Windows to cause all processes to run in that mode. Windows has some related settings, but they don't stop all processes from being run in a VM. So far the only fix we have found is to disable Hyper-V entirely by going to "Uninstall a program", "Turn Windows features on or off", and then unchecking "Hyper-V":
![](http://n4te.com/x/5078-rE7Z.png)
Here is an article with more in depth instructions:
https://support.bluestacks.com/hc/en-us/articles/115004254383
It shows a few other items that may also need to be unchecked (they were not checked on our computer).

If you have [Cygwin](https://www.cygwin.com/), you can run `cpuid` from the command line:
```
>cpuid -1 | grep "hypervisor guest"
      hypervisor guest status                 = false
```
If that says `hypervisor guest status                 = true` then you are running under Hyper-V.

Now that the problem has been identified, we can look into allowing Spine to run in this mode without an internet connection. Until then, hopefully you can use the workaround above.

**Comment by bencresty** [comment]
@NathanSweet wow, that looks like crazy foor to debug. Great work. And good that you saw the issue there.

For what it's worth I can give you this:

- I'm no gamer, I never game and nobody ever installed nor played games on this system, so it's definitely not game related here
- Looking here Hyper V is not installed/turned on, so it's not possible to turn that off to fix it and should therefor be something else on this system being the cause

Hope this helps in some way

**Comment by bencresty** [comment]
@NathanSweet  It happened here again today when the internet was gone.

Hereby the spine.log
[spine.log](https://github.com/EsotericSoftware/spine-editor/files/9127746/spine.log)

**Comment by bencresty** [comment]
Having this issue here today again because I'm working in a spot without internet. FYI It seems to be pretty consistent: always when there's no internet Spine won't start.

**Comment by NathanSweet** [comment]
It still looks like Spine is running through some virtualization mode, Windows' Hyper-V isolation or something else. That's the best theory we have and we've exhausted further investigation. Unless we can see it happening firsthand, I don't know how we could fix it. If Hyper-V isn't installed, maybe there are some other settings that affect this. You might try disabling VT-x in the BIOS, though I don't know for sure if that would help.

**Comment by bencresty** [comment]
@NathanSweet  I understand by your reactions you have an issue in debugging things outside of Spine, but it's not clear to me why you would even want to go this far.

To my best understanding I would think it goes something like this:

- Spine is clearly able to detect that there's not internet, otherwise it wouldn't throw this message to the user. So it's only up to what choice it should make now now this info is known, right?

- So I would say after Check if there's an internet connection, it goes probably something like this:
    - YES there is a connection; try updating Spine
    - NO there is no connection: don't update Spine and stay offline
    
So I don't understand the reasoning about looking on anything besides Spine. Isn't this just a matter of internally disable looking at internet and just continue with the currently installed version?

What am I missing about your reasoning so I could understand better why you would even look further?

**Comment by NathanSweet** [comment]
To fix any problem we need to see the problem, make changes, and test to see if the changes are fixed. Making changes when we do not see the problem is a shot in the dark and means we cannot know that we've actually fixed it.

Spine requires an internet connection when run in a virtualized environment. Unfortunately we must do this to avoid piracy. It is very rare for it to be an inconvenience to users, as nearly all users have an internet connection and very few run Spine in a VM. The problem you are having is that either Spine thinks it's in a VM when it is not, or you are running Spine virtualized without realizing it. The latter happened to us when Windows Hyper-V isolation got turned on without us even knowing what that is.

**Comment by bencresty** [comment]
Again I am NOT running on some VM or special environment. Just Windows 10.

**Comment by NathanSweet** [comment]
I understand, but unfortunately that doesn't bring us any closer to fixing the problem.

I believe I answered all your questions. We won't change Spine to run in a virtualized environment without an internet connection. If there is a bug in Spine that causes this to happen when not in a virtualized environment, then we will need to reproduce the problem so we can fix it. We cannot reproduce your problem, except by enabling Hyper-V. Since we cannot reproduce the problem and have never seen it happen on our many computers, there must be something with your OS or other software configuration or other software applications that either cause this to happen due to interaction with a bug in Spine or cause Spine to be run in a virtualized mode. We would love to fix the problem if it is in Spine or identify the cause of the problem if it is outside of Spine, but I really don't know what else we can try.

**Comment by bencresty** [comment]
Alright, I get it now and of course I completely understand that you want to prevent piracy. That makes sense.

It's unfortunate it is this way now tho. I hope you can come up with something later.

**Comment by bencresty** [comment]
@NathanSweet  Alright, I get it now and of course I completely understand that you want to prevent piracy. That makes sense.

It's unfortunate it is this way now tho. I hope you can come up with something later. And when I can think of something I would obviously let you know too.

One thing I can think of at the moment: did you actually tried it on Windows 10 without internet connection? Or are you perhaps running Linux or Mac?

**Comment by NathanSweet** [comment]
Thanks for understanding. It bothers me a lot that this is happening. We've combed through the code many times hoping to spot something amiss. The Hyper-V problem we ran into seemed like such a good match, I was hoping that was it.

Yes, we've tried Windows 10, Mac, and Linux without an internet connection. It works as expected in our testing: the launcher is unable to reach the server but the editor is allowed to run using a previously downloaded update file.

**Comment by NathanSweet** [comment]
If you can, please try unzipping [this ZIP file](http://n4te.com/x/5252-vm-test.zip) to a folder and running `run.bat`. That will create a file `output.txt`. Please then email us that file: contact@esotericsoftware.com

**Comment by bencresty** [comment]
@NathanSweet  it's in your email

**Comment by bencresty** [comment]
@NathanSweet  BTW Thanks a lot for diving into this. I completely understand you don't like this issue either and definitely understand these kind of things aren't the most fun things to investigate and you have more stuff to do. I'll do what I can on my side and if I found something I'll let you know.

**Comment by bencresty** [comment]
@NathanSweet BTW Thanks a lot for diving into this. I completely understand you don't like this issue either and definitely understand these kind of things aren't the most fun things to investigate and you have more stuff to do. I'll see what I can do here. And if it cannot be solved, even after that report, than I must just accept I can't run Spine without internet connection.

**Comment by bencresty** [comment]
@NathanSweet  Closing this now as solved (see email).

FYI and future reference and perhaps to help others just in case:
- 'Hyper-V', 'Windows Hypervisor Platform' and 'Windows Sandbox' were not enabled here (that's why I didn't know there was Hyper-V / virtual env. active).
- 'Virtual Machine Platform' was enabled. Probably this was automatically enabled by installing 'Windows Subsystem for Linux', which intentially was enabled here for using Docker within Linux in the future.

Also here; thanks for your help @NathanSweet  and sorry for the misunderstanding from my side / me not knowing about the fact that obviously 'Windows Subsystem for Linux' seems to 'mess up' ALL windows applications without even using it or turned on virtual stuff that does.

**Comment by NathanSweet** [comment]
Thanks for checking that out! With confirmation that Windows virtualization was indeed the problem, we've done more testing around that. Apparently a number of Windows features can cause Windows to run apps in its virtualization mode. For example, enabling WSL will do it, even without enabling Hyper-V and with [core isolation](http://n4te.com/x/5253-BI2I.png) off.

It seems the Windows feature doing that is called "virtualization based security" (VBS). VBS can be disabled like this:

1) Run: Start > Run > `gpedit.msc`
2) Expand: Local Computer Policy > Administrative Templates > System > Device Guard
3) Double click: Turn On Virtualization Based Security
4) Set it to `Disabled` and click OK.
5) Reboot.

If you are running Windows 10 Home, you won't have `gpedit.msc`, which is the Group Policy Editor. There are some hacks to enable `gpedit.msc`, or you can do this:

1) Run: Start > Run > `regedit`
2) Expand: HKEY_LOCAL_MACHINE > SYSTEM > CurrentControlSet > Control > DeviceGuard
3) On the right side: right click > New > DWORD (32-bit) Value
4) Name it `EnableVirtualizationBasedSecurity` with a value of 0.
5) Expand: HKEY_LOCAL_MACHINE > SYSTEM > CurrentControlSet > Control > Lsa
6) On the right side: right click > New > DWORD (32-bit) Value
7) Name it `LsaCfgFlags` with a value of 0.
8) Reboot.

We did these steps on a computer that had WSL enabled and afterward Spine ran offline just fine. Hopefully this can be the fix in all situations, so you don't have to sacrifice WSL or other Windows features. It is unfortunate that VBS is enabled silently by enabling WSL and other features. It can even be turned on by other software, such as games that have anti-cheat mechanisms like Squad or Battlefield. Suddenly ALL processes are being run through a VM layer -- yikes!

Thanks for your patience and assistance in getting this figured out!

**Comment by bencresty** [comment]
Hi @NathanSweet , I'm surprised to see I didn't react to your last comment. I've read it at the time, but seem to have forgotten to react. Hereby: thanks for all the work to provide all this info!

**Comment by NathanSweet** [comment]
Recently AMD Zen 5 CPUs run poorly when Windows Virtualization Based Security (VBS) is on, and apparently it's on by default now in some cases (new Windows 11 installs maybe?). Not too surprising performance is affected and even if it wasn't I don't personally want my software running on more layers in the name of unnecessary "security". Anyway, it's seeing more attention lately and it turns out the best way to disable VBS is to turn off "SVM" in BIOS. Example:
![](http://n4te.com/x/481-wBh1.jpg)
