### ISSUE TITLE
Path drawing concerns; please make the 'pen tool' for paths working the same as other tools!

### ISSUE THREAD

**Issue by bencresty** [EsotericSoftware/spine-editor#661]
At the moment I'm creating lots of paths in an animation and I see myself correcting each first vertex as it's always rotated away from the second vertex. I can't think of a situation where having the first vertex rotated 180 degrees, like it's doing now, would be useful.
Every time we draw paths we now need to correct the first vertex, while that shouldn't be nesesary.

While drawing the path the most logical default direction of the first vertex would be to let it look at the second vertex. That way there's no need to correct the vertex every time and that would make drawing paths way less time consuming and limits actions.

This change would be highly appreciated!!

**Comment by NathanSweet** [comment]
What version of Spine are you using? In 4.1 the first vertex always points at the second when clicking to make the second vertex. If dragging to make the second vertex it adjusts handles of both, maybe that can be improved.

**Comment by bencresty** [comment]
@NathanSweet  Thanks for your quick reply. I'm using the latest 4.1 version (4.1.06), but it's only looking in the direction of the next vertex when the second vertex is clicked without dragging out the handles, so only if we draw a straight line.

But most of the time (at least in my case) the second vertex got handles by dragging them out directly after clicking and then the first vertex get this weird direction of its handles making the first vertex not facing the second one. 

To illustrate this I created a screenrecording:

https://user-images.githubusercontent.com/69322733/179374977-cca40d8c-5743-4174-a6a8-1a69b1534aca.mp4

**Comment by bencresty** [comment]
The difference between Spine and the other tools is that Spine, when clicking the first time, always starts the curve with a vertex with handles. This isn't the case in other vertex tools.

Other vertex tools make a distinction for the first vertex between a click and a click-and-drag on the first vertex. Just like Spine does with vertex number 2 and up. So if Spine would make the distinction between just-a-click and click-and-drag for the first vertex too it would be working as expected and just like other software I assume.

**Comment by bencresty** [comment]
Uh... that doesn't fix all as it seems and now I understand why the Spine path 'pen tool' doesn't feel intuitive; all the other tools (Affinity Photo, Photoshop, Illustrator, Affinity Designer, Affinity Publisher, Cavalry etc.) all work practically the same, but Spine is doing not only the first vertex differently (as described above), but also the other points, as it seems;

To add to the above in previous posts;

when clicking on continuation points (so points after the first vertex) when doing just a click we expect the vertex to be without handles (so draw a 'straight' vertex, no handles). But Spine is still adding handles when just clicking.

Now I finally understand why the pen tool in Spine is not intuitive to me; all other tools I use work the same and do it differently. Both vector and raster editors as well as video and VFX/motion graphics tools.

The rules in the other software are like:

1) When just clicking on the canvas we get a point without handles. That goes for the first vertex, but also with each following vertex.
2) When clicking and dragging while holding the pointer, we get a point WITH handles and are able to define the curve while dragging. That goes for the first vertex, but also with each following vertex.

So if Spine would do the same as the other tools it would not only solve the issue of not being able to start with a 'straight node' and making it easier to draw straight zigzag lines, it would also make the path pen tool intuitive to work with for all illustrators and motion graphics users out there (like me), as we're all used to using the same method in all these programs. It's second nature after working with it for a long time.

Hope this all make sense and you guys will consider changing this!

**Comment by NathanSweet** [comment]
We don't generally make decisions solely because other tools work a certain way, though I do agree there is some value to what users are used to and/or expect. Spine doesn't necessarily need to work like other tools, unless that happens to make sense as the best solution. All path vertices in Spine have handles and can't work exactly like in your video. It could be similar, though I think paths in Spine are usually smooth. I'm not sure how often a zigzag is needed and if it's worth a shortcut.

The first vertex doesn't show its handles until the second vertex is created. If you click to create a second vertex, you get a straight line. If you drag instead, the behavior is currently odd. We should improve that to provide more reasonable handles for the first vertex.

**Comment by bencresty** [comment]
@NathanSweet mmm, sounds like you'd rather like reinvent the wheel than to go with and accept a standard milions of creatives are using everyday for a reason and they can literally read and write with and have the behaviour completely in their systems so they don't need to think about it (like a language or other every day use products we are all familiar with) and can create everything with it from scratch in no time. 

It's completely up to you and I don't want to be pedant, but I don't get that decision and hope you'll decide otherwise and understand that some things are a result after years of trial and error of features by a lot of people and companies that didn't make it in the end, because that was subpar to the final method. And because now everybody is familiar with it it's like a language; you don't need to think about it anymore and know that whatever software you use you might expect this to work the same way.

And yes, I use zigzag way more often than I'd like to have a path tool automatically change the way I was actually drawing the path. I want to work precisely and create the exact path I'd like directly in one go and don't like a workflow when I draw a path, the path tool does all kinds of unwanted automatic things and suddenly now I need to adjust all vertices after drawing the path. Things that I don't need to do in other software as it's done in one take. Exactly as I drew it.

In the meantime I'll enjoy that...
- when I buy a bike the steering wheel is in the front and when pushing the pedals to the front I move forward
- when buying a new car the steering wheel is on the left when driving in a right driving side country
- when buying a pc the keyboards all use querty layout in the country I live in
- when mixing audio when faders move up the sound volume rises
- when using windows software copy'n'paste always works with ctrl-C and ctrl-V
- when connecting internet or usb all cables we buy use the same plug everywhere around the world

**Comment by a690089735** [comment]
I think this problem should be relatively easy to fix, just when there is no specified Bezier handler(P1P2), so that the starting point handle automatically points to the next point(P4) of the Bezier handler(P3) can be

**Comment by NathanSweet** [comment]
In 4.1.18 we've improved the first curve segment when dragging the second point. I think the rest of the path tool behavior is similar enough to other tools. As mentioned, unlike other software, Spine paths always have handles, so doing a zigzig path will require manually pointing the handles.
