### ISSUE TITLE
Please reset output filename for render when starting new project

### ISSUE THREAD

**Issue by bencresty** [EsotericSoftware/spine-editor#663]
When a new project is started we expect the output render filename(s) to be cleared.
Other software we're used to render with always ask for where to save a file and shows a confirmation dialog when overwriting files, but Spine doesn't seem to do that. This caused issues here before as when you hit the 'Export' button on the new project, suddenly it overwrites all the work we did for another project. Because the file dialog is still showing the same path and filename(s).

This could be solved by:
- Always resetting the output filename textfield when starting a new project
- Ask for confirmation to the user if files already exist when starting a render.

Spine 4.1.06

**Comment by NathanSweet** [comment]
I find it useful quite often to have the last used path populated. I agree overwriting without prompt makes this dangerous. Let's track that with #673.
