### ISSUE TITLE
Spine crashing regularly while editing keyframes

### ISSUE THREAD

**Issue by bencresty** [EsotericSoftware/spine-editor#664]
Today I had several Spine crashes where the program just quits/crashes while doing nothing special. Last time it was while selecting or dragging keyframe(s).

The log says that an animation key cannot be found:
[spine.log](https://github.com/EsotericSoftware/spine-editor/files/9127995/spine.log)

Spine version: 4.1.06

**Comment by bencresty** [comment]
It looks like crashes appear especially in this situation:

- turn on 'offset'
- box select keyframes
- move the box selection to move the keyframes
---> crash

BTW It also happens a lot that it doesn't crash, but suddenly removes the box select and starts to move a 'random' keyframe within that box instead of moving all keyframes (while the cursor clearly indicated that there's a MOVE going on.

So looks like the combination of using box select, offset and dragging keyframes aren't a very successful combination at the time

**Comment by bencresty** [comment]
https://user-images.githubusercontent.com/69322733/180620989-8beae326-662f-455d-8fa2-9ddc4154237a.mp4

**Comment by bencresty** [comment]
BTW, love that error message "An UNEXPECTED ERROR has occurred".

Hopefully there are no EXPECTED ERRORS in the software, haha ;)

**Comment by bencresty** [comment]
@NathanSweet  After having the same sequence over and over where Spine constantly crashed at the same spot and I couldn't get through it, I now tried it by turning off the 'Auto' mode to auto scale the view in the Graph viewport. And bamm... no more crash for this particular edit and I could finally get past this crashing thing.

BTW apart from this particular instance where it kept on crashing while doing the same things, it feels completely random when it crashes with the exact same routine as described above. Sometimes it just works moving the selected box of keyframes, sometimes it just crashes with the same actions.

**Comment by bencresty** [comment]
FYI I didn't have the crash anymore since I turned off the AUTO mode yesterday, so it definitely has something to do with that

**Comment by bencresty** [comment]
Next to believing the AUTO frame mode in the Graph Editor is strongly related to being the cause of these crashes, I also believe that this issue is related to using box select and dragging that box, instead of using ctrl + a (windows) to select all vertices and drag from one vertex instead to move them all. I didn't pay too close attention lately, because I have AUTO turned off now to prevent the crashes to happen, but using box select and drag the box is causing all kinds of issues and I wouldn't be surprised if that's also part of the cause for these crashes.

**Comment by NathanSweet** [comment]
This bug is number 1 on our most wanted list. I have the Graph's `Auto` on all the time and I don't see this happening.

It's amazing you see it happen so often, and even caught it on video! Can you please post or email (contact@esotericsoftware.com) a project where you see it happening regularly? It may be something about your project file.

FWIW, you can just drag any key with `Offset` active, no need to box select.

**Comment by bencresty** [comment]
Hi Nathan, can't send you projects and also started a new one where I don't use box-select anymore, but can tell you that I believe it's this combination that is the problem:

- Use box select
- Have AUTO viewport enabled
- Try to drag the box-select-box when NOT dragging from a keyframe under the cursor
- I'm pretty sure this crash only happens when 'Offset' is turned on
- There is something happening to the box select when drawing causing the box select to dissapear/end. This seems to not only cause this crash, but also sometimes results in some 'random' handle of some keyframe within the box select to go completely nuts (rotating and scaling in a (to me) completely random and understandable way. Than the only way to restore that is to do UNDO. So this might be a different bug, but might as well be related; bottom line: I think the issue might be related to a box select suddenly stop being a selection (the blue thing dissapears, indicating the selection is gone, while just dragging)

Lately I stopped using box select and now use ctrl+a (windows) to select the keyframes. I don't think I ever saw that crash again. Which could prove the fact that it has something to do with box-select-drag with given properties as above.

But tbh I don't like that workflow as it's easy to accidentally hit ctrl-A twice (just to be sure everything is selected), just to find out now suddenly EVERYTHING in the whole world (exageration ;) ) is selected... Not my cup of tea. So hopefully box select will start working again soon!

Thanks for working on this! Would be great if we could trust this again! Got a little scared of box-select ;)

**Comment by NathanSweet** [comment]
I've tried box selecting with `Auto` and `Offset` enabled, doing all kinds of dragging. Unfortunately I don't see it happening. We'll keep an eye out, but this particular crash has been elusive so far.

To be clear, if you are offsetting, you don't need box select or `ctrl+A`. You can drag any key and it will start offsetting that timeline.

**Comment by NathanSweet** [comment]
We found a crash related to box selection and fixed it in 4.1.08. It's not clear if it fixes both crashes we've seen in this area.

**Comment by bencresty** [comment]
Good to read you found a crash and applied a (hopefully) fix. I'll keep an eye on it. If I know more I'll let you know.

**Comment by NathanSweet** [comment]
Hopefully that fix was it. We'll keep an eye out, as always.
