### ISSUE TITLE
[issue] Last path vertex gets deleted unwanted while not selected with box select when hitting delete

### ISSUE THREAD

**Issue by bencresty** [EsotericSoftware/spine-editor#671]
When box selecting the middle vertices on a path, the last vertex gets removed (while not selected). It seems to only work without deleting the last vertex unwanted when deleting them one by one with clicks.
Please see **complete** video demo below

https://user-images.githubusercontent.com/69322733/180243735-0586580b-b08b-4234-aeb7-2d012910ebb7.mp4

Spine 4.1.05

**Comment by NathanSweet** [comment]
4.1.07

**Comment by bencresty** [comment]
@NathanSweet  Nice! Thanks
