### ISSUE TITLE
Add option to pad image sequence file numbers

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-editor#68]
Currently image sequence exports are numbered like `image_1.png`, `image_2.png`, ... `image_100.png`.

Adding an option to automatically pad those image sequence names ala `image_001.png`, `image_002.png`, etc. would make it easier to import these image sequences in 3rd party tools.

**Comment by NathanSweet** [comment]
This is mentioned in #11

**Comment by NathanSweet** [comment]
3.7.17-beta
