### ISSUE TITLE
The output type of the PSD export may show incorrect options

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#680]
**Description:**
In Spine 4.1.06, the PSD export may show options that should not be available in the `Output type` section: `Single file`, `File per animation`,`File per frame`
<img width="467" alt="Screen Shot 2022-08-01 at 9 46 30" src="https://user-images.githubusercontent.com/85478846/182052962-b34268fe-6b7d-4c25-a27a-b8cba67ae9ec.png">

**Expected behavior:**
When PSD export is selected, the following is displayed in Output type: `Layers`, `Frame`
<img width="467" alt="Screen Shot 2022-08-01 at 9 47 27" src="https://user-images.githubusercontent.com/85478846/182052993-d2e9db66-e072-4d25-a2ba-127818f56380.png">

**Steps to reproduce this problem:**
1.Download and unzip the following .zip file:
[Bug-in-OutputType-of-PSD-export-4.1.06.zip](https://github.com/EsotericSoftware/spine-editor/files/9230075/Bug-in-OutputType-of-PSD-export-4.1.06.zip)
2.Open the spine project in the folder using Spine v4.1.06
3.Press Ctrl + E, and you can see the `Output type` section shows incorrect options: `Single file`, `File per animation` ,`File per frame`

Also, you can see if you deleted `anim1` or `anim2` in the Animations section of the Tree view, the `Outyput type` section will show correct options :`Layers`,`Frame`

**Version in which this problem was found:**
Spine editor v4.1.06

**This problem is reported in the following forum post:**
http://esotericsoftware.com/forum/export-PSD-with-layers-not-working-correctly-17802

**Comment by NathanSweet** [comment]
4.1.07
