### ISSUE TITLE
Undoing translation of an IK constraint while having the constraint selected in the tree gives incorrect undo results

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#681]
**Reproduction steps:**
1. In a new project, create a bone.
2. Create a single bone IK constraint.
3. Go to Animate mode.
4. Select the IK target in the viewport.
5. Select the constraint (under the Constraints node) in the tree.
6. Translate the IK target bone.
7. Undo.

When undoing, the IK target bone will not go back to it's original position. Instead the IK target will slowly move towards the original position each time you undo.

**Comment by NathanSweet** [comment]
4.1.07
