### ISSUE TITLE
Selected vertices are ignored for linked meshes smoothing

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#684]
Reproduced in Spine 4.1.08

Steps:
• open the spineboy project
• select the torso mesh and create a new linked mesh
• activate the child linked mesh
• select only half of the vertices of the mesh and press the smooth button

Expected: smooth should only be applied to the selected vertices
Actual: smooth is applied on all the mesh vertices

**Comment by NathanSweet** [comment]
Good find! Also affects `Prune` and `Swap`. Fixed in 4.1.09!
