### ISSUE TITLE
[request] Ctrl + Drag box selection edge in Graph panel to scale box selection with keyframes from its center (mirrored moving box selection edge)

### ISSUE THREAD

**Issue by bencresty** [EsotericSoftware/spine-editor#685]
It's great we can scale a range of keyframes in Spine Graph to scale the timing (x-axis) or lower or higher the range of values (y-axis). I use this all the time to resize the effect of, let's say, a with keyframes created sine wave or other animation moving back and forth or left and right.

But when doing scaling with a box select in the Graph panel we can currently aren't able to scale from the center of the box selection, while this sometimes is what we're after (for instance scaling a sine wave amplitude to make the effect stronger or less strong). So we now need to first move the top edge of the box selection and than move the bottom edge up. But it's difficult to let the middle stay exactly the same, so often we need to correct things by moving the box up or down as a third action.

Al this would be a lot simpler if we would have a shortcut key, like CTRL (WIndows) to be able to do a 'mirrored scaling' from the center. In Affinity Designer we can do this with holding Ctrl and it's very convenient and used a lot.
If we'd like to scale a box selection vertically with all keyframes in it, we'd then use ctrl + drag top edge down, or ctrl + drag bottom edge up, and the other edge would move the same amount, but in the opposite direction and thus making the box smaller or larger in vertical direction while maintaining its center at all time. 
The same thing with horizontal scaling: when holding ctrl + left edge drag, the right edge automatically moves the same amount, but in the opposite direction making the box selection with its containing keyframes scale to become wider or smaller, but maintaining its center on the same spot.

This is especially needed when we have an animation channel where we start and end with the middle keyframe and animated in between the same amount up as down in the graph view (this situation happens a lot here with pulsing and mirrored repeating pingpong motion).  If we could keep its center by scaling vertical we wouldn't have the issue that the middle position (the first and last keyframes) would be moved to a wrong position.
But even if the amount of movement up and down in the graph isn't equal this feature would still make it very useful and way faster to adjust things, as we first scale vertically or horizontally by holding Ctrl and than move the whole box to whereever we want if needed. Which feels more intuitive than to move the top edge and than move the bottom edge and than move the whole box, to find out the scaling wasn't done well, so to tweak the top edge, tweak the bottom edg etc. That's a lot of tweaking for something that we want to have precise and where the thing we want is to only keep it's center and scale the box. Hope this makes sense.

I think this would also be a feature that is extremely powerful, while probably and hopefully, not difficult or time consuming to implement. It would definitely help a lot in having a faster work flow for lots of use cases!

Example
As you can see in the video below, scaling from center is way faster and only requires a single action in lots of use cases, while the workflow as it is now requires 3 or more actions to get the same result and it's hard to get it exactly right most of the time
(don't mind the lag, normally scaling works instant, but this laptop is extremely slow at the moment for some weird reason):

https://user-images.githubusercontent.com/69322733/183611683-9f2dd0f6-7cdd-4faf-9105-1571a606b470.mp4

**Comment by NathanSweet** [comment]
4.1.20

**Comment by NathanSweet** [comment]
Thanks for the write up. Sorry for the delay. We used `alt` + drag box selection edge, as `ctrl` is used for selection and `shift` for snapping.

**Comment by NathanSweet** [comment]
Ah, `alt` turns on key shift. We can actually use `ctrl` when dragging a selection box edge. Normally `ctrl`+drag would give you a box selection, but in this case you already have one.

**Comment by bencresty** [comment]
@NathanSweet Nice! Thanks

**Comment by bencresty** [comment]
@NathanSweet  Works sweet like this! Thanks a lot for this change. Definitely going to use this a lot!
