### ISSUE TITLE
[request] Please keep slot with mesh connected to the first bone in hierarchy

### ISSUE THREAD

**Issue by bencresty** [EsotericSoftware/spine-editor#687]
When using the Create-workflow to add bones to a mesh the mesh is getting connected to the last bone applied, which normally is the bone which is most deep in the hierarcy in the situation where bones are nested because they all relate.

To me that's not ideal as we always need to go through the hierarchy tree to reach the mesh. So I see myself moving the slot with the mesh up in hierarchy to be connected to the first bone, so topmost in the hierarchy.
Next to this making it easier to reach the mesh without the need to use filters, to me it also feels more structured as all nested bone use that same mesh so to me that makes more sense then to have the mesh connected to the last bone in the nesting hierarchy.

It would be nice if Spine could do this automatically; so that it will not move the mesh down the hierarchy when attaching nested bones to it. Spine knows these bones are nested, so should be able to keep the mesh connected to the upmost bone in the hierarchy.

--

To illustrate, this is how it is now:
![image](https://user-images.githubusercontent.com/69322733/184534736-b1e3630c-35de-4a3b-a11a-24926e464efa.png)

This is what I would like to see instead and find more logical:
![image](https://user-images.githubusercontent.com/69322733/184534753-14c37832-64e8-4381-9d6b-644cba13813e.png)

**Comment by NathanSweet** [comment]
We need reproduction steps to know how you are getting this result.

**Comment by NathanSweet** [comment]
From the video in #688, I'm guessing you are selecting the attachment by holding `ctrl` before each bone you create. Why? Only select an attachment before drawing the bone if you want the attachment (and slot) to be a child of the new bone. That is the only purpose of selecting an attachment with the `Create` tool.

**Comment by bencresty** [comment]
@NathanSweet Ah, that makes sense. I thought it was required when working with the Create tool to always connect bones to meshes by first selecting the mesh and then draw the bone for it. I didn't know it wasn't required when using the same mesh by different bones to deform the mesh. When thinking about it it makes sense that it's not necesary as we need to add bones with the Weights tool/mode to set weights on the mesh for those bones anyway.

Alright, when doing it now without ctrl-selecting the image again after adding the first bone (so now only drawing bones after the first bone) everything works as expected and the image stays with the first bone. 

The auto numbering (#688) now works okay too (so the issue of auto numbering only seems to happen when doing ctrl-select image -> draw bone -> ctrl-select image again -> draw new bone -> repeat.
