### ISSUE TITLE
[issue] All bones get wrong number when using Create Mode and nest bones

### ISSUE THREAD

**Issue by bencresty** [EsotericSoftware/spine-editor#688]
I see myself renaming bones after using the Create-method a lot because for some reason numbering is wrong everytime. So I just did a quick and simple test to see what's going on and found out that numbering of ALL the bones is wrong already when assigning numbers to them while drawing bones [see video below].

**This is what I do:**
- Select Create-tool
- Select Parent-bone (in this test case the root bone)
- Select the slot with Ctrl-click (on Windows)
- Draw the first bone

- Keep this latest drawn bone selected
- Select the slot with Ctrl-click
- Draw the new bone
- Repeat this for all bones

**This is what I see happening (see video):**
- First bone gets the name of the slot without number
- Second bone gets number 3 (!!! this is obviously wrong !!)
- Third bone gets number 2  (!!! this is obviously wrong !!)
- Fourth bone gets number 5 (!!! this is obviously wrong !!)
- Fith bone gets number 4 (!!! this is obviously wrong !!)
- Sixth bone gets number 7 (!!! this is obviously wrong !!)
- Seventh bone gets number 6 (!!! this is obviously wrong !!)

**difference between expectation and result**
expectation - result
obj    --> obj
obj2  --> obj3
obj3  --> obj2
obj4  --> obj5
obj5  --> obj4
obj6  --> obj7
obj7  --> obj6

As you can see ALL bones except for the original first bone now have the wrong number while bones were perfectly added in order.

You can also see clearly in the video that the numbers of bones, which are assigned to when drawing, change after releasing the mouse to make the new bone permanent.

[spine version: 4.1.08]

https://user-images.githubusercontent.com/69322733/184536423-569efc9e-6903-4eed-a324-b5a779371b4f.mp4

**Comment by bencresty** [comment]
This issue seems to only happen when doing a different workflow for adding several bones to the same mesh using the Create tool:

This issue of auto numbering seems to happen when doing ctrl-select image/mesh -> draw bone -> ctrl-select same image/mesh again -> draw new bone -> repeat.

**Comment by NathanSweet** [comment]
Yep, confirmed the numbering gets really strange in that situation. Thanks for the report! We'll get to it soon.

**Comment by NathanSweet** [comment]
4.1.09

**Comment by bencresty** [comment]
@NathanSweet  Nice!
