### ISSUE TITLE
[request] open/collapse selected items

### ISSUE THREAD

**Issue by bencresty** [EsotericSoftware/spine-editor#689]
I see myself trying to open/collapse multiple items in the tree by selecting them and clicking open/collapse on one of them. I am familiar with this workflow in other programs. Would be nice if we could use the same method in Spine!

I would expect all selected items to either open or collapse when clicked the open/collapse button on one of them.

https://user-images.githubusercontent.com/69322733/184859265-cf961f69-8113-4d2b-996f-f8aa929e7895.mp4

**Comment by misaki-eymard** [comment]
Hi, you can expand or collapse tree items and all its children by right clicking. Here is the tip for this in the Spine Tips page:
http://esotericsoftware.com/spine-tips#collapse-expand-tree

**Comment by bencresty** [comment]
> Hi, you can expand or collapse tree items and all its children by right clicking. Here is the tip for this in the Spine Tips page: http://esotericsoftware.com/spine-tips#collapse-expand-tree

@misaki-eymard I know, but that's not what this feature request is about. This is about specifically and only opening/collapsing specifically selected items

**Comment by misaki-eymard** [comment]
Oh, sorry I missed that about multiple selections. However, even in that case, you can use the expand/collapse buttons in the Tree view:
http://esotericsoftware.com/spine-tree#Expand-and-collapse

This would allow you to use it if you want to expand all selected items or not.

**Comment by bencresty** [comment]
@misaki-eymard  I see that these UI buttons do what I am looking for; they open or collapse the selected items. I didn't know they were working with selections too, so that's great to know! I'll use that now and close this thread.

Just found out that there's an issue in their keyboard shortcuts tho; they don't work the same as the buttons and their tooltip state, so for future reference for anybody seeing this thread; I just opened an issue for it here:
https://github.com/EsotericSoftware/spine-editor/issues/699
