### ISSUE TITLE
[issue] locked bones can still be moved around in the viewport in pose mode

### ISSUE THREAD

**Issue by bencresty** [EsotericSoftware/spine-editor#695]
I like to lock bones in the viewport which may only be controlled by constraints. However, when unchecking the `Select` of these bones it's still possible to move them around in the viewport when in Pose mode (see video).

Spine 4.1.08

https://user-images.githubusercontent.com/69322733/185189206-61dc2eb6-dab1-413b-8e00-1184fca97f19.mp4

**Comment by NathanSweet** [comment]
4.1.10, cheers!

**Comment by bencresty** [comment]
I see you're working hard on fixing things! Thanks!
