### ISSUE TITLE
[issue] open/collapse keyboard shortcuts don't do what supposed to + Tooltip text is not complete

### ISSUE THREAD

**Issue by bencresty** [EsotericSoftware/spine-editor#699]
Looking in the interface the keyboard shortcut for opening or collapsing items in the tree should be ALT + LEFT / ALT + RIGHT. 
(the same is the case with ctrl + shift + ENTER)
That's also what's set in the keyboard shortcuts text file. However, this doesn't do the same.

When hitting the buttons on top of the tree panel all selected items open or collapse. But when hitting the keyboard shortcut only ONE of these items open or collapses. 

Of course we expect the keyboard shortcuts to do exactly the same as the UI buttons for it and open or collaps ALL selected items.

![image](https://user-images.githubusercontent.com/69322733/185378768-93c31fc5-eac6-4d00-b9a8-5cbb0e29f1ee.png)

![image](https://user-images.githubusercontent.com/69322733/185379518-3abaddb3-5f85-4f80-9807-16f0f4c0883a.png)
![image](https://user-images.githubusercontent.com/69322733/185379809-da369300-b57d-4732-b3cc-9a4da67ea506.png)

Also the tooltip text is not completely accurate either and that's why I opened a feature request about a way to open/collapse selected items; according to the tooltip it's only opening/collapsing a single NODE, but in reality by pressing one of these buttons ALL SELECTED NODES are opened or collapsed, which is great, but the tooltip should match the actual behaviour obviously

**Comment by NathanSweet** [comment]
4.1.10

**Comment by bencresty** [comment]
@NathanSweet  Yes! Thanks
