### ISSUE TITLE
Warning when whitespace stripping with meshes

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#7]

**Comment by pharan** [comment]
Relevant thread:
http://esotericsoftware.com/forum/Patch-for-trimmed-atlas-meshes-in-c-sharp-unity-4973

**Comment by pharan** [comment]
Putting old ideas here:
SHOW A WARNING
- Spine detects untrimmed images, regardless of them being used as meshes. Show a warning.
- Spine detects detect untrimmed images the moment they are used with meshes. Show a warning.
- Spine detects untrimmed images among used images when the project is loaded. Show a warning as a toast.
- The detection has a sensitivity. 40px default?

or?

SPINE GENERATES CROPPING RECTANGLES
- Spine generates cropping rectangles equivalent to where how the images would end up if whitespace-stripped.
- The cropping rectangles would take the mesh UVs into account and always keep the rectangles big enough so the UVs fit in them.
- Allow the Texture Packer to receive and use these cropping rectangles as information for it to pack the images as atlas regions.

**Comment by pharan** [comment]
http://esotericsoftware.com/forum/Texture-Packer-Settings-for-Spine-Unity-6047

**Comment by NathanSweet** [comment]
3.6.01-beta has a warning when using `Create atlas` with data export and the project has a mesh. Nothing can be done if running the texture packer on an arbitrary folder of images.

In the future we should allow polygons to be packed.
