### ISSUE TITLE
Animation cleanup may create unintended curves

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#700]
**Description:**
If the last key in the animation and the one before it have the same value, using animation cleanup may create curves with extreme shapes in between. This occurs only if the previous key's curve type is Bézier and the handle is horizontal.

![Animation-cleanup-may-create-unintended-curves](https://user-images.githubusercontent.com/85478846/187624210-3d29b14d-ed1a-4d65-88d6-ef3380a66fb7.gif)

**Expected behavior:**
Using cleanup does not add new curves between keys have the same value.

**Steps to reproduce:**
1. Open the repro project in this zip file: [Animation cleanup may create unintended curves.zip](https://github.com/EsotericSoftware/spine-editor/files/9459558/Animation.cleanup.may.create.unintended.curves.zip) 

2. Switch to Animate mode and press the `Clean Up` button. 

**Version where this was tested and the bug is found:**
v 4.1.08

This issue was reported in this post:
http://esotericsoftware.com/forum/Export-json-error-from-spine-to-unity-17902

**Comment by NathanSweet** [comment]
4.1.10
