### ISSUE TITLE
Add a hotkey to use a "Replace" button on the Find and Replace window

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#702]
Currently, pressing enter to complete input on the `Find and Replace` window is treated as pressing the `Select` button, and the `Replace` cannot be completed by key input. Therefore, it would be more convenient to add a hotkey that allows you to complete `Replace`.

Suggested in this forum thread:
http://esotericsoftware.com/forum/Find-and-Replace-dialogue-shortcut-for-the-Replace-button-17941

**Comment by NathanSweet** [comment]
4.1.10: `enter` replaces, `ctrl+enter` selects.
