### ISSUE TITLE
Add a browse button for each image file

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#703]
Currently, the folder set in the image path can be opened by pressing the `Browse` button. However, if you are managing a lot of images using many folders, it may be more efficient to have quick access to the location for each image. Therefore, adding a browse button for each image file would be useful.

This is suggested in this forum thread:
http://esotericsoftware.com/forum/Suggestion-Show-in-Explorer-at-image-location-17971

**Comment by NathanSweet** [comment]
4.1.10
