### ISSUE TITLE
Add a "Selected skeletons" option to the Scope field of the Find and Replace

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#704]
Currently, there is no option in the `Scope` field of the `Find and Replace` window to limit the search to a specific skeleton, so it is hard to narrow the search result in a Spine project with multiple skeletons that have tree items with the same name. Therefore, adding a "Selected skeletons" would be useful.

This is suggested in this forum thread:
http://esotericsoftware.com/forum/x-17982

**Comment by NathanSweet** [comment]
4.2.57-beta
