### ISSUE TITLE
Infinite warnings appear when a sequence attahcment with different sized images is turned mesh.

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#705]
**Description:**
If a sequence attachment does not use mesh, it does not matter if each image has a different size. However, if the mesh checkbox is enabled, "Images Resized" warnings appear when a frame using the different size image is displayed, and it occurs infinitely even if you confirm the warning with the all frames:
[youtube]https://youtu.be/r4HsO3eIYuA[/youtube]

**Expected behavior:**
Once an image has been confirmed to be resized, the warning will no longer appear when the image is displayed again.
Or, when a sequence with different size images is turned mesh, users should be warned that all images must match in size.
(Ideally, a sequence attachment with different sized images can use mesh without problems.)

**Steps to reproduce:**
1.Open the spineboy-pro.spine via the Examples on the welcome screen.
2.Select `muzzle01` in the `muzzle` slot and check `Sequence`.
3.Set Image path as `muzzle` and `Sequence` `start` to `01` and `end` to `02`.
4.Set `Frame` to `2` to show `Images Resized` dialog, press the OK button, then set `Frame` to `1`.
5.Set `Frame` to `2` again, and you can see the `Image Resized` dialog appear again.

**Version where this was tested and the bug is found:**
v 4.1.09

This issue was reported in this post:
http://esotericsoftware.com/forum/Spine-4-1-sequence-with-different-sized-images-17985?sid=ee10a69fa939c1bfb85c4022e31192d5

**Comment by NathanSweet** [comment]
Spine watches the size of the setup mode image, so when the setup mode frame is changed, it triggers the mesh size dialog. Users don't usually change the setup frame very often and it's not actually wrong, but could be annoying. We'll suppress the dialog in 4.1.10 when it would have been shown as a result of changing the sequence setup frame.

Regarding image sizes, sequence frames don't have to be the same size. For regions, the image sizes are used, centered at the region position. For meshes, the mesh vertices stay in the same positions so only the texture changes. A smaller or larger image is scaled across the mesh vertices. If either of those behaviors is undesired, users should use the same size images for their sequence.
