### ISSUE TITLE
[issue] Ctrl+Click to select vertices in Weights mode doesn't work most of the time when using a pen

### ISSUE THREAD

**Issue by bencresty** [EsotericSoftware/spine-editor#707]
When using a mouse this is no issue, but when using a Wacom pen around 80% of the time it's failing to add a vertex to the selection when holding `Ctrl` (on Windows) while clicking on the vertex when in Weights mode/tool.

I've checked all Wacom settings and I'm pretty much 100% certain it's not an issue with the Wacom software or configurations. Most importantly because Double click is turned off (and confirmed that it's not double clicking), both in the general Wacom settings as well as in the specific Wacom settings for the Spine application:
![wacom-settings](https://user-images.githubusercontent.com/69322733/192747118-835f9f75-76c1-439d-9d84-b4d04da12765.jpg)

For the record: of course I don't manually double click with the pen and the tablet is working fine and stable, never seen any glitches with it and all drivers are up to date.

Using Spine 4.1.11, so the latest.

In video below I select the first vertex and click with the pen while holding `Ctrl` to select the other vertices. As you can see sometimes it 'accidentally' adds the vertex to the selection, but more often it is not.

https://user-images.githubusercontent.com/69322733/192747981-d5bf29de-3fc9-48dd-ac60-a6115da1d8bd.mp4

**Comment by bencresty** [comment]
BTW also very important for you to know:

It's also confirmed that it cannot be an issue with Wacom/the pen, because when selecting a single vertex without holding `Ctrl` it always select that vertex without any issue. So it has something to do with the software mechanism to check for the `Ctrl` key while clicking with the pen. It looks like a 'timing' issue

**Comment by NathanSweet** [comment]
4.1.18
