### ISSUE TITLE
Missing animation events when exported with `Animation cleanup`

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-editor#708]
A user on the forum encountered missing animation events after exporting the project in 4.1 (reproduced in 4.1.11):
http://esotericsoftware.com/forum/Missing-animation-events-when-you-export-JSON-from-Spine-18029 (edited) 

Repro project sent via email:
FMfcgzGqQmQtrCdjXPNFsfdsvBtzmzdC
Upon `.json` export, events are not exported in the animation named `born` when `Animation cleanup` is enabled, but they are properly exported when `Animation cleanup` is disabled.

**Comment by lukeeingram** [comment]
Reported by another user here:
http://esotericsoftware.com/forum/4-1-clean-up-bug-18038?p=79291

**Comment by NathanSweet** [comment]
4.1.12
