### ISSUE TITLE
[issue] Filter on 'Sequence' doesn't filter on sequence

### ISSUE THREAD

**Issue by wigglepixel** [EsotericSoftware/spine-editor#709]
Hi,

This looks like an issue to me;

Please see video below. In the timeline I want to filter on images sequences (so don't show regions with single images). Luckily there is a 'sequence' filter. But this doesn't seem to work; it's not showing any sequence. While the 'Attach' filter DOES show all attachments, including the image sequences. To me this looks like the 'Sequence' filter not doing its job and there's no working filter on image sequences now. But please correct me if I'm wrong and missing something here.

Thanks in advance!

https://user-images.githubusercontent.com/7702506/193342895-d3ca3010-a1d4-4d44-824a-43b70000fc05.mp4

**Comment by NathanSweet** [comment]
I can't tell from the video if you have any sequence keys set (at the start of the video when all timelines are shown, no sequence timelines are visible). If you don't have sequence keys, there won't be any timelines to show.

It would help to post a `.spine` showing the issue. We don't need any images files to see this problem.

**Comment by wigglepixel** [comment]
@NathanSweet Are we talking about the same thing? AFAIK the only thing called 'sequence' in Spine is the relatively new built in feature to use 'image sequence's instead of single images inside a slot.

I'm using image sequences in all attachments here and you can see it in the video at 0:08 for example (the dotted lines are set on image sequences) to make sure they run all 160 frames

**Comment by wigglepixel** [comment]
Ah, my bad. I forgot I moved all image sequence timelines to a different animation to start it in parallel. Silly me. When looking in the right animation it shows as expected.  Sorry for this and for the confusion. And thanks for the quick response. Very appreciated. Closing this thread now.

**Comment by NathanSweet** [comment]
No worries, glad you got it worked out!
