### ISSUE TITLE
4.1.12 - Animations are slowed, stutter is present when viewing animations in editor

### ISSUE THREAD

**Issue by lukeeingram** [EsotericSoftware/spine-editor#710]
First reported by a user in the forums here:
http://esotericsoftware.com/forum/Frame-speed-inconsistent-in-Editor-4-1-12-18046?p=79301#p79301

I tested this against Spine Editor versions 4.1.09 and 4.1.11, with launcher 4.1.09, and can confirm differences between

**Comment by NathanSweet** [comment]
4.1.13
