### ISSUE TITLE
Offset cursor in Graph view not removed from view when selecting another object (bone) in the tree

### ISSUE THREAD

**Issue by wigglepixel** [EsotericSoftware/spine-editor#711]
Not really much of a problem here, but just so you guys know as it's probably not intended behaviour;

When, after offsetting an animation channel in the graph view, switching to another object in the tree, the offset pointer (the orange cursor with +4 in the video below) is not removed and stays visible while having no relation with the current bone:

[edit] At this moment after posting I'm even wondering if this offset cursor would have to be there after the offset being applied? Not sure if that's intentional.

(Spine 4.1.13)

https://user-images.githubusercontent.com/7702506/193453707-ee4fd343-2cfa-41a1-949d-de8b5ddc6d3e.mp4

**Comment by NathanSweet** [comment]
This isn't actually a bug, though I understand why it seems strange.

Spine remembers when you start offsetting until you select any key that was not offset. This allows you to offset multiple times without creating unwanted keys. Once you select other keys then Spine "forgets" and the orange markings on the timeline disappear. After that if you offset the same timeline again, you'll likely have an extra key that was created the first time you offset.

What makes it look like a bug is Spine remembers until you select any key that was not offset. Even if you select a different bone in the viewport, Spine continues to remember the last offset. That's not really a problem, though it may look strange.

We highlight the `Offset` button while Spine is remembering the last offset. I know this is not obvious, but I'm not sure what we could do to make it look less like a bug.

**Comment by wigglepixel** [comment]
Hi @NathanSweet, thanks for clearing that up. So if I understand correctly by your reply the way it works is that the offset is non-destructive while this orange timeline cursor is visible? And that the way it's built now the offset gets permanent (destructive) when selecting a key that's not having this previously non-destructive offset?

In that case I would think that switching to a bone that's not currently in the timeline view (graph) would be the same like selecting a keyframe without this offset. At least that's what I would expect as a user. I'm not 100% sure, but I don't think we lose features or use cases when this state releases (making the change permanent) when switching to a bone that's not currently in the timeline view.

I would even think that when switching to another bone, even when it's already in the graph view, could trigger a 'release' of this non-destructive state. But that's just me. I didn't even know about this non-destructive state, so perhaps other people that do have an issue with changing that? Not sure.

**Comment by NathanSweet** [comment]
Yep, that's correct.

It's true we could forget the state when a different bone is selected. Currently we keep the state as long as possible, which may actually be longer than a user expects/needs. We'll give a try and see how it goes!

**Comment by wigglepixel** [comment]
@NathanSweet  t.b.h. I didn't even consciously know about this non-destructive state, although intuitively I was pretty aware of it as I was using it. But there were other times I whished it was there because I found out I had double extra keyframes unwantedly.

I think this offset is mostly used for overlapping action (at least I use it for that reason all the time). So the way it's build now is great, but perhaps an additional non-destructive cycle offset value per animation channel could be a great fix to solve these kind of problems.

The way I personally like to work is animate all channels first without any offset, and than offset the animation channels for overlapping action. Than it would be nice if we could set a non-destructive offset per animation channel. That shouldn't result in much bigger files, as it's just one double value per channel in the json. But it would highly improve the workflow, because it's way easier to tweak offsets of our channels to make it beautiful in total.

Also I think that keepin this non-destructive up until the runtime even would have some great benefits: 
- especially that the curves always remain exactly as designed
- less errorprone when applying offsets over offsets 
- obviously less keyframes (so the extra offset value could even make the json/bin files smaller!) to worry about
- no more issues when offsetting an already offsetted shape (which happens everytime when we tweak our timing of multiple channels)
- have even more control in the runtimes, because we even know the offset value! (and if we don't want that we could still use the current destructive offset method, or perhaps even bake the offset)

I understand this is another thread and not this thing (I've seen it here on github somewhere), so not for this issue thread, but I tell this here, because perhaps that could make this non-destructive/destructive transition for this particular situation easier and would release the pressure on this workflow to keep things non-destructive. Because it wouldn't be as important to keep things non-destructive if we have a real and staying non-destructive state per channel. 

Hope this helps.

And have to say; really love Spine!

**Comment by NathanSweet** [comment]
Thanks for your feedback on non-destructive offset! I'll link to #153 so your notes will be seen when it comes time to solve that issue.

I think we'll keep the offset state for as long as possible, even if selecting another bone. It being destructive is a pretty big drawback, so keeping it may be important in some situations.
