### ISSUE TITLE
`Key shown` may affect to Deform keys of inactive skins’ attachments when "show all skin attahcments" is enabled

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#712]
**Description:**
`Key shown` may affect to Deform keys of inactive skins’ attachments when `show all skin attachments` is enabled in the Tree view options. 

**Expected behavior:**
`Key shown` does not key and affect inactive skins' attachments even if `show all skin attachments` is enabled. 

**Steps to reproduce:**
1. Open the repro project which is attached to this forum post: http://esotericsoftware.com/forum/Show-all-skin-attachments-option-all-key-issues-18060
2. Press the `Key shown` button or `Ctrl + Shift + L` in animate mode, and you can see a key added on the deform timeline of a mesh attachment in an inactive skin.

**Version where this was tested and the bug is found:**
v 4.1.13

This issue is reported in the following forum posts:
http://esotericsoftware.com/forum/Show-all-skin-attachments-option-all-key-issues-18060
http://esotericsoftware.com/forum/show-all-skin-attachments-18023

**Comment by NathanSweet** [comment]
Fixed in 4.2.00-beta, as the changes ended up being too risky for 4.1.
