### ISSUE TITLE
Better sorting of animations on import

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#714]
Currently, the way the animation list on [import animation](http://esotericsoftware.com/spine-import#Animation) shows a very long list that can be difficult to navigate.

![animation list](http://esotericsoftware.com/forum/download/file.php?id=11348)

Which may also appear like this, seemingly following a different sorting method:

![animation list](http://esotericsoftware.com/forum/download/file.php?id=11349)

It would be easier to navigate and pick the animations to import if one or more of these suggestions were applied:

- have collapsible nodes just as in the tree, and the ability to check a node to import all the animations in a folder
- add a search and filter bar
- add the possibility to sort alphabetically by animation name or by folder name

Original discussion thread:
http://esotericsoftware.com/forum/Ghosting-and-Importing-Request-18092?p=79512#p79512

**Comment by FabianoIlCapo** [comment]
If I can add another idea: having ✅ marks instead of simple selections, to avoid the stress of having to keep CTRL pressed.

**Comment by misaki-eymard** [comment]
+1: https://ja.esotericsoftware.com/forum/d/25593-%E3%82%A2%E3%83%8B%E3%83%A1%E3%82%A4%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%88%E3%81%AE%E8%A1%A8%E7%A4%BA%E9%A0%85%E7%9B%AE%E9%A0%86%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

**Comment by NathanSweet** [comment]
We have a tree in 4.2.40-beta. Clicking items toggles, ctrl/shift for multi-select, ctrl+A for select all, escape to clear the selection. The tree is sized better than it used to be and the dialog remembers the last selections.
