### ISSUE TITLE
【PhotoshopToSpine】The same name error is not displayed for layers under layer groups with [slot] tags

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#717]
**Description:**
If you create a layer under a layer group with a [slot] tag, you will not see any error even if the layer name is the same as another layer name in the same skin, but only one of them will be exported since the file with the same name will be overwritten during export.

**Expected behavior:**
If a layer with the same name as another layer in the same skin is exported, even if it is under a layer group with a [slot] tag, the following error will be displayed:
<img width="252" alt="Screen Shot 2022-11-01 at 14 10 54" src="https://user-images.githubusercontent.com/85478846/199163497-efc3292b-9ecc-4cac-afd0-39eadc85dfb0.png">

**Steps to reproduce:**
1. Download an attached .zip file here: 
[The same name error is not displayed for layers under layer groups with [slot] tags.psd.zip](https://github.com/EsotericSoftware/spine-editor/files/9907100/The.same.name.error.is.not.displayed.for.layers.under.layer.groups.with.slot.tags.psd.zip)

2. Unzip and open the psd file in it, export the layers using PhotoshopToSpine v7.31.
3. You can find no errors are displayed when exporting, however, when looking at the output folder, only the "A" layer is exported.

**The version of PhotoshopToSpine in which this error was found:**
PhotoshopToSpine v7.31

**This issue is reported in the following forum post:**
http://esotericsoftware.com/forum/Ps-Script-multiple-merge-layers-with-same-name-18199

**Comment by NathanSweet** [comment]
Attachments only require unique name when they are under the same slot. Attachments under different slots can have the same name. If we made it an error, it wouldn't be possible to export from PS where many attachments use the same image. Typically when you want this, you would make your layers identical. If they aren't then the last exported layer will overwrite the others.

While it would be nice if we could show an error if this was unwanted, I don't see a way to improve this automatically as we don't know if it is unwanted. I don't think it warrants a setting or tag, since the error should be caught when the wrong image is seen in PS.

**Comment by FabianoIlCapo** [comment]
Could the script at least show a warning of some kind when we're about to export many layers with the same name?
It could even show it after the export, I think the important thing here is to make the user aware of what's happening.
The duplicating action might also be part of the mirroring body parts process, and if the artist forgets to rename the layer it might take a while before someone realizes what happened.

**Comment by NathanSweet** [comment]
It's a valid action, so showing an warning could be annoying. Also the script doesn't currently have warnings, only errors.

The best we could do might be a setting to make duplicate attachment names an error. You'd uncheck that setting if you intentionally have duplicate attachment names. However, I'm undecided if we should do that. We try not to add settings if we can avoid them, as having many settings makes using the tools harder. Also I'm not sure it's worth trying to stop a user from making naming errors in their project. While we could catch this one, there's thousands of other ways they could mess up naming.
