### ISSUE TITLE
Key buttons are not shown for any mesh attachments even in the active skin when `Show all skin attachments` is disenabled

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#718]
**Description:**
In the 4.1.12 update, the key buttons for deform and sequences in other skin became hidden when `Show all skin attachments` is checked. However, if `Show all skin attachments` is unchecked, key buttons are not shown for any mesh attachments even in the active skin. Although keys can be added to animations using Auto key, keys cannot be recorded using the key buttons on the Tree view unless `Show all skin attachments` is enabled.

**Expected behavior:**
The key buttons for mesh attachments that belong to the active skin are always visible.

**Steps to reproduce:**
1. Open the `Mix-and-match` Spine project via the Examples list using Spine 4.1.13 or later versions. (4.1.12 has already been removed and not available.)
2. Uncheck `Show all skin attachments` in the Tree view settings.
3. Switch to animate mode.
4. Then, you can see the keys buttons are not shown on the Tree view.

**The versions of Spine in which this issue were found:**
Spine v4.1.13 to v4.1.17

**Comment by NathanSweet** [comment]
I'm not able to reproduce the problem. With `Show all skin attachments` unchecked and the `girl` skin active, I do see the key button for `girl/bag-base`:
![](http://n4te.com/x/5890-TUs5.png)

**Comment by misaki-eymard** [comment]
I have prepared a screen recording on this issue, so please download the zip file below and check the video file in it:
[Uploading Key buttons are not shown for any mesh attachments even in the active skin when Show all skin attachments is disabled.mp4.zip…]()

From your screenshot, you seem to have pinned some skins in the Skins view, and indeed the key buttons seem to appear for some reason when you do the pinning.

**Comment by NathanSweet** [comment]
4.1.18
