### ISSUE TITLE
AWEBP export does not allow exporting the file per animation

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#719]
**Description:**
In AWEBP export settings, even if you set the `Animations` property to `All` and the `Output type` property to `File per animation`, only a single file is exported, regardless of the number of animations that the skeleton has.

**Expected behavior:**
An AWEBP file is exported for each animation when `File per animation` is set in the `Output type` property.

**Steps to reproduce:**
1. Open the Mix-and-match Spine project via the Examples list using Spine 4.1.17.
2. Select `Export...` via the Spine menu, and select `AWEBP` on the side menu.
3. Set the following settings:
`Export type`: `Animation`
`Animations`: `All`
`Output type`: `File per animation`
<img width="628" alt="AWEBP-export-settings" src="https://user-images.githubusercontent.com/85478846/200773878-c6e1f786-3d6c-403d-95de-b833b1311096.png">

4. Export the skeleton, and you can see only a single file is created in the folder specified in the `Output folder` property.

**The version of Spine in which this issue was found:**
Spine v4.1.17

**This issue is reported in the following thread:**
http://esotericsoftware.com/forum/AWEBP-18251

**Comment by NathanSweet** [comment]
4.1.18
