### ISSUE TITLE
Hiding a slot and undoing it may add an attachment key unintentionally

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#722]
**Description:**
When `Auto Key` is enabled, hiding a slot is treated as hiding the attachment in the slot is performed after undoing, resulting in an attachment key being added to the animation unintentionally.

**Expected behavior:**
If you undo the operation that hides slots, it does not affect the visibility of attachments in the slot.

**Steps to reproduce:**
1.Enable `Auto Key`.
2.Hide any slot.
3.Transform any visible bone.
4.Press the `Undo` button or `Ctrl+Z`.
5.You can see the attachment in the hidden slot is hidden even though it was visible originally.
6.Transform any visible bone again.
7.Then, you can see an unnecessary attachment key has been added to the animation.

Here is the repro project (the .zip file includes a video recording of the reproduce steps):
[spineboy_AttachmentsKey.zip](https://github.com/EsotericSoftware/spine-editor/files/10120639/spineboy_AttachmentsKey.zip)

**The versions of Spine in which this issue were found:**
Spine v4.1.17

This issue is reported on this forum thread:
http://esotericsoftware.com/forum/x-18341

**Comment by NathanSweet** [comment]
4.1.18
