### ISSUE TITLE
The preview on the `Find and Replace` window disappears by clicking the `?` button

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#724]
Description:
The preview on the right of the `Find and Replace` window disappears by clicking the `?` button on the right of the "Regular expression" checkbox, and then clicking the `OK` button on the `Regular expressions` window. The preview will remain blank until reopening the `Find and Replace` window even if you enter anything on the `Find` field in this state.

Expected behavior:
The preview on the right of the `Find and Replace` window does not disappear if you click the `?` button.

Steps to reproduce:
1.Open the Find and Replace window and click on the “?” button.
2.Click the OK button on the Regular expressions window.
3.You can see the preview disappears.
![Find-and-replace-preview](https://user-images.githubusercontent.com/85478846/209489997-bc7ab9cc-c994-42f2-ac36-04760087ffe0.png)

The versions of Spine in which this issue were found:
Spine  v4.1.17

This bug was reported on this forum post:
http://esotericsoftware.com/forum/Pro-4-1-17-Find-and-Replace-Regular-Expression-Tool-Tip-Bug-18437

**Comment by NathanSweet** [comment]
4.1.18
