### ISSUE TITLE
`Animation clean up` and the `Clean up` button removes second and subsequent sequence keys

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#725]
Description:
If you enable `Animation clean up` in the export settings or select an animation and use the `Clean up` button, the second and subsequent sequence keys on the same timeline will be removed.

Expected behavior:
The second and subsequent sequence keys are retained even if `Animation clean up` is enabled or the `Clean up` button is used.

Steps to reproduce:
1.Download and unzip the attached zip file:
[`Animation clean up` and the `Clean up` button removes second and subsequent sequence keys.zip](https://github.com/EsotericSoftware/spine-editor/files/10323149/Animation.clean.up.and.the.Clean.up.button.removes.second.and.subsequent.sequence.keys.zip)
2.Open the Spine project in it, and make sure there are two sequence keys in the "knock2" animation.
![Screen Shot 2022-12-30 at 13 50 05](https://user-images.githubusercontent.com/85478846/210035644-d800d826-f27b-4e14-bb8a-ad1c8063f130.png)

3.Press the `Clean up` button on the Tree view, and you can see the second sequence key is removed.
![Screen-Shot-2022-12-30-at-13 50 07](https://user-images.githubusercontent.com/85478846/210035773-41af6ea2-ec7f-4b52-a2af-a6ebded56808.png)

The versions of Spine in which this issue were found:
Spine v4.1.17

This bug was reported on this forum post:
http://esotericsoftware.com/forum/unity-don-t-play-correctly-when-reuse-keyframe-sequence-18455

**Comment by NathanSweet** [comment]
4.1.18
