### ISSUE TITLE
Constrained bones do not rotate correctly when `Rotation` `Mix` in the Transform constraint is less than 100

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#729]
**Description:**
If the `Mix` value of `Rotation` is less than 100, the constrained bone will be flipped when the target bone of the transform constraint rotates more than 180 degrees. In other words, the rotation is interrupted as if it suddenly jumped.

**Expected behavior:**
Even if the target bone rotates more than 180 degrees, the constrained bone is affected according to the percentage of the Mix value for the value of the target bone rotation.

**Steps to reproduce:**
1.Download and unzip the following zip file:
[Constrained bones do not rotate correctly when `Rotation` `Mix` is less than 100.zip](https://github.com/EsotericSoftware/spine-editor/files/10563716/Constrained.bones.do.not.rotate.correctly.when.Rotation.Mix.is.less.than.100.zip)

2.Open the Spine project in it using Spine v4.1.19, and play the animation.

3.You can see the bone with a transform constraint `Rotation` `Mix` value of 100 follow the target bone's rotation perfectly, but the bone with a `Mix` value of 70 can be seen to flip with respect to the X axis when the target bone rotates more than 180 degrees.

**The versions of Spine in which this issue were found:**
Spine v4.1.19

**This bug was reported on the following forum post:**
http://esotericsoftware.com/forum/Rotation-Transform-Bug-18602

**Comment by NathanSweet** [comment]
Unfortunately this is how rotation mixing must work. I [explained it here](https://github.com/EsotericSoftware/spine-editor/issues/456#issuecomment-485151318). It would be good to include this information in the user guide, if it's not already there.

**Comment by JQSpin** [comment]
> Unfortunately this is how rotation mixing must work. I [explained it here](https://github.com/EsotericSoftware/spine-editor/issues/456#issuecomment-485151318). It would be good to include this information in the user guide, if it's not already there.

Please provide an alternative roation mode/version where it's a percentage of the total rotation it's reading from. It could be a check box like how, Local or Relative area vailable for some tranforms if legacy behavior need to be supported. It already difficult to set up certain mechanics as it is in Spine withouth this weird roation behavior. Version 3 wad the vorst rotaionale behavior I've seen in any 3D or 2D software to date, requiting you to use 3 keys for one 360 degree rotation. And now you are saying we can't have another bone rotate, eg 10% of source bones 720 deg = 72 deg without it jumping arround. That is just plain non user/creative friendly, it makes certain setups impossible.

**Comment by NathanSweet** [comment]
When `Local` is unchecked, it needs to work like it does. "World rotation" means the direction a bone is pointing, and a bone's world rotation is always in the range of 0-360 degrees. Taking a percentage of a bone's world rotation results in a jump when the bone rotates in a circle. There is no such thing as eg 720 degrees of world rotation.

You can already check `Local` and `Relative` to add any percentage of another bone's local rotation without a jump, as @JQSpin described.

When `Local` is checked and `Relative` is unchecked, currently we wrap 0-360 degrees. This is a holdover from how rotation worked < 4.0. I don't think there is any longer a good reason to wrap. Removing wrapping changes the constraint behavior, but the jumping is not typically useful so I doubt that anyone is relying on that behavior.

**Comment by NathanSweet** [comment]
4.2.60-beta

**Comment by NathanSweet** [comment]
Note in setup mode the rotation is always wrapped, so to see the non-wrapping behavior you need to be in animate mode.

**Comment by NathanSweet** [comment]
There is discussion on how to adjust projects affected by this change here:
https://esotericsoftware.com/forum/d/25981-spine-4263-position-and-rotation-of-some-of-the-bones-being-incorrect
