### ISSUE TITLE
Select skeleton, skin and animation for PNG export from CLI or in config

### ISSUE THREAD

**Issue by Hinidu** [EsotericSoftware/spine-editor#73]
Hi! In our project we have quiet big number of spine projects and we want to export all of them to images to use them in our custom game content editor. But png export now renders the project in the state it was left by the artist which can be pretty random :wink:
Could you please extend PNG export from CLI with these options? It looks like pretty common use case. But maybe it doesn't worth to complicate Spine editor export and it would be better to create separate generic program to render these things using exported from Spine json? (maybe it already exists or I will create it myself sometime...).
PS: Also I made a request for the optional [ignoring of missing atlases on export](http://esotericsoftware.com/forum/Ignore-missing-images-on-export-4915) and I still want this feature too.
PPS: Another our use case was described [here](http://esotericsoftware.com/forum/Custom-png-exporter-5018).
Thank you in advance!

**Comment by NathanSweet** [comment]
Related: http://esotericsoftware.com/forum/Can-I-choose-skeleton-when-export-6746

**Comment by NathanSweet** [comment]
3.7.20-beta
