### ISSUE TITLE
Animations may not be exported correctly when negative scale and IK constraint are used at the same time

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#730]
**Description:**
Animations have a mesh that has weights for a bone constrained by an IK constraint and scaled in the negative direction may be exported as 1 * 1 px images when you export it as PNG format. However, this is also related to the FPS on the export settings or key timing. If you change them, the animation may be exported correctly even if the negative scale and IK are used.

**Expected behavior:**
A mesh that has weights for a bone constrained by an IK constraint can be shown in the exported animation as seen in the Spine editor's viewport. 

Steps to reproduce:
1. Download and unzip the following zip file:
[Negative-scale-and-IK-constraint.zip](https://github.com/EsotericSoftware/spine-editor/files/10565769/Negative-scale-and-IK-constraint.zip)

2. Open the Spine project in it using Spine v4.1.19, and press `Ctrl + E` to open the Export window.

3. Export the animations with the settings shown in the following screenshot (Default settings except that `Animations` is set to `All` and `FPS` is set to `30`.):
![Screen Shot 2023-02-02 at 15 34 46](https://user-images.githubusercontent.com/85478846/216249821-ec3e4383-dd2c-4906-8ab8-a26062eab68e.png)

4. When you check the Output folder, the "Animation-can-be-exported-correctly" is exported correctly, and the "Animation-has-the-problem" is exported as 1*1px images.

The only difference between the two animations is whether the Mix of the IK constraint is set to 100 or 0. However, if you set the `FPS` to `20` in the export settings, both can be exported correctly. Also, if you move the scale key at frame 10 in "Animation-has-the-problem" to frame 15, it can be exported correctly as well.

**The versions of Spine in which this issue were found:**
Spine v4.1.19

**This bug was reported on the following forum post:**
http://esotericsoftware.com/forum/png-export-bug-automatically1x1-18604

**Comment by NathanSweet** [comment]
The problem comes from the frame where the bone is scaled to zero. Fixed in 4.1.20 and our 4.1 runtimes.
