### ISSUE TITLE
Parent slot is not selected when the Slots filter is turned on in the Tree view

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#731]
**Description:**
In 4.1.19, when the "Slots" filter is turned on in the Tree view, the parent slot of the selected attachment is no longer automatically selected. The behavior before 4.1.19 was more convenient and needs to be fixed.

**Expected behavior:**
If you turn on the "Slots" filter in the Tree view with selecting an image attachment, the parent slot of the selected attachment will be selected.

**Steps to reproduce:**
1. Open any Spine project which has slots and image attachments.
2. Select an image attachment on the viewport with no filters applied in the Tree view.
3. Turn on the “Slots” filter in the Tree view.
4. You can see the selection did not change to the parent slot, so nothing is highlighted in the Tree view. 

**The version of Spine in which this issue was found:**
Spine v4.1.19

**This issue was reported on the following forum post:**
https://esotericsoftware.com/forum/d/23830-move-drawoder-after-image-selection/3

**Comment by NathanSweet** [comment]
4.1.20
