### ISSUE TITLE
[PhotoshopToSpine] Cannot use "~/" in output path in v7.17 and later versions

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#732]
**Description:**
When you specify a path using "~/" for the output path in PhotoshopToSpine v7.17 or later versions, you get an error or the path is saved to a different location than I specified. This problem is currently reproduced only in masOS.

**Expected behavior:**
If you specify a path using "\~/" for the output path, e.g. \"~\/Desktop", the layers will be output in the specified hierarchy without error.

**Steps to reproduce:**
1. Open any .psd file and run PhotoshopToSpine v7.17 or later version.
2. Enter "~/Desktop" in `Output Paths > Images`.
<img width="388" alt="Screen Shot 2023-02-24 at 9 56 57" src="https://user-images.githubusercontent.com/85478846/221065703-84843ba8-dc00-49fd-9c3b-2b58698694bc.png">
3. Then, when you press the `OK` button, you will either see an error in the following image or the output will not be as per the path you specified.
<img width="260" alt="Screen Shot 2023-02-24 at 9 57 21" src="https://user-images.githubusercontent.com/85478846/221065850-bfe37224-aa52-432e-b27b-ec7f4db1fb3f.png">

**The version of Spine in which this issue was found:**
PhotoshopToSpine v7.17 to v7.31

**This issue was reported on the following forum post:**
https://esotericsoftware.com/forum/d/23850-photoshoptospine-script

**Comment by NathanSweet** [comment]
7.35
