### ISSUE TITLE
`Images Resized` dialog appears indefinitely when a sequence animation with different sized images is played on `Preview`

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#734]
**Description:**
When a sequence animation with different sized images is played on the `Preview` view in the `Setup` mode, the `Images Resized` dialog appears indefinitely even if you press the `OK` button.

A screen recording video reproducing the problem: 
https://youtu.be/idIjRh4jLTc

**Expected behavior:**
Even if a sequence animation with different sized images is played on the `Preview` view in the `Setup` mode, `Images Resized` dialog does not appear.

**Steps to reproduce:**
1. Download the attached .zip file: [Images-Resized-dialog-appears-indefinitely.zip](https://github.com/EsotericSoftware/spine-editor/files/10952676/Images-Resized-dialog-appears-indefinitely.zip)
2. Open the Spine project with Spine 4.1.19, and open the `Preview` view.
3. Play `animation`, then the `Images Resized` dialog should appear.
4. Press the `OK` button, and you can see the `Images Resized` dialog appears again and you cannot close the dialog.

**Version where this was tested and the bug is found:**
v 4.1.19

**This issue was reported in the following post:**
https://esotericsoftware.com/forum/d/23946-images-resized

**Comment by NathanSweet** [comment]
4.1.20
