### ISSUE TITLE
Specifying `json+pack` or `binary+pack` when exporting using Spine 3.8.99 via CLI does not work

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#735]
**Description:**
When exporting via CLI, you can specify `-e json`, `-e binary`, `-e json+pack`, or `-e binary+pack` to export with default export or pack settings, but for some reason this is not possible with Spine 3.8.99. Trying it outputs the following error:

```
ERROR: Error running legacy Spine launcher:
ERROR: Export settings JSON file does not exist:
<Path>/json+pack
```
This problem can be reproduced both using Terminal on macOS and Command Prompt on Windows.

**Expected behavior:**
You can specify `-e json`, `-e binary`, `-e json+pack`, or `-e binary+pack` to export with default export or pack settings with 3.8.99.

**Workwround:**
Exporting via CLI itself can be done as long as the path to the export settings JSON file is specified to `-e`.

**Steps to reproduce:**
Run the following command with any Spine project:

> Windows:
> `Spine --update 3.8.99 \Path\SpineProject.spine --output \Path\Exported --export binary+pack`
> 
> macOS:
> `/Applications/Spine.app/Contents/MacOS/Spine --update 3.8.99 --input /Path/SpineProject.spine --output /Path/Exported --export binary+pack`
> 

**Version where this was tested and the bug is found:**
Launcher v4.1.11

**This issue was reported in the following post:**
https://esotericsoftware.com/forum/d/23848-%E6%89%93%E5%8C%85%E5%9B%BE%E9%9B%86%E7%9A%84%E5%8F%82%E6%95%B0%E7%96%91%E9%97%AE

**Comment by NathanSweet** [comment]
The `json`, `json+pack`, `json+atlas`, `binary`, `binary+pack`, and `binary+atlas` shortcuts are an editor feature added in v4.0.66-beta, so I'm afraid they won't work in 3.8.99.
