### ISSUE TITLE
export multi resolution missing undefined case.

### ISSUE THREAD

**Issue by djmisterjon** [EsotericSoftware/spine-editor#738]
i have a issue, i need export my file in multiple resolution.
So i have 
undefined: max (100%)
-med: medium size (-50%)
-low: for mobile (-80%)

when i fill the setup, the software seem missing one texture package ! 
it produce [1,2] but missing index 0 ! 
if i add suffix to index 0 it work but i dont want suffix for my max resolution ! 
how can i fix this issue ? 

see the empty affix.
![image](https://user-images.githubusercontent.com/24865815/233579147-4ed0195b-590f-41e9-9ede-2efcef713dd6.png)

see the missing texture pack ! 
![image](https://user-images.githubusercontent.com/24865815/233579352-9c516c5d-9d4a-4515-8014-8d425c313fd5.png)

this will produce error with my loader because default atlas missing !:
![image](https://user-images.githubusercontent.com/24865815/233589009-f6625b13-36c0-4504-a083-af170534927e.png)

https://github.com/pixijs/spine/blob/8c9778b631f86686b6e10eb3c415f5424da9b6a1/packages/loader-base/src/loaders.ts#L72

thanks 

ps: i cant log to your forum , your server say error ! so i post here sry .

**Comment by misaki-eymard** [comment]
> ps: i cant log to your forum , your server say error ! so i post here sry .

Could you please contact us via email so we can check the status of your forum account so that you can log in to the forum again?: contact@esotericsoftware.com

**Comment by djmisterjon** [comment]
> > ps: i cant log to your forum , your server say error ! so i post here sry .
> 
> Could you please contact us via email so we can check the status of your forum account so that you can log in to the forum again?: [contact@esotericsoftware.com](mailto:contact@esotericsoftware.com)

send done.
otherwise my theory is that when you iterate on those data.
You probably ignore if the entry is empty but with the wrong index ?
something like ? 
```ts
type entries = [scale: number, suffix: string, filter: number][]; //2d matrix
const entry = entries[0];
if(entry[1]) continue; // ignore if 0 (scale) is empty instead of 1 (suffix)
```

hard to say without source code !

**Comment by NathanSweet** [comment]
Specifying the scale number is enough. When you leave the suffix blank, the atlas is still output, but it is placed in a subfolder named after the scale. This prevents collisions if multiple were left blank. We could avoid the subfolder if only one is blank.

**Comment by NathanSweet** [comment]
4.2.00-beta

**Comment by djmisterjon** [comment]
> We could avoid the subfolder if only one is blank.

yes thanks, it save lot of step after export
