### ISSUE TITLE
Setting `Timeline FPS` to 24 may cause to leave afterimages in exported animated GIFs

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#739]
**Description:**
If you select the GIF format and export your animation with the `Timeline FPS` set to 24 in the `Playback` view, the exported GIF may has afterimages in some frames like the following image:
![24FPS](https://user-images.githubusercontent.com/85478846/235853177-d4ab15b6-e5f3-430d-aea8-8f61cb619b7b.gif)

**Expected behavior:**
Exported GIFs will not have any afterimages just as it is displayed in the viewport of Spine.

**Workaround:**
Change `Timeline FPS` to 30 in the `Playback` view or set `FPS` to 20 or 30 in the export settings.

**Steps to reproduce:**
1. Download the attached .zip file: 
[24FPS.zip](https://github.com/EsotericSoftware/spine-editor/files/11380304/24FPS.zip)
2. Open the Spine project in it and open the export window. 
3. Select the GIF format, load `GIF.export.json` in the folder, then export the skeleton.
4. Check the exported animated GIF. You should be able to see that some frames have afterimages.

**Version where the bug is found:**
Spine v4.1.21

**This issue was reported in the following post:**
https://esotericsoftware.com/forum/d/24188-weird-extra-stuff-on-gif-export

**Comment by NathanSweet** [comment]
Fixed in 4.1.22. Unfortunately fixing this makes our GIFs a little larger. We had optimizations that don't work in all situations that had to be removed. The GIF format is just terrible.
