### ISSUE TITLE
Alternate viewport/tree icons

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#74]
_From @Shiu on May 16, 2016 17:37_

A selection of icons for both the viewport and tree.
We could have primitive shapes like square/circle/triangle etc and maybe other meaningful icons for use as handles/control bones or even specific usage like feet, hands.

http://esotericsoftware.com/forum/it-would-be-nice-if-6347

_Copied from original issue: badlogic/spine-internal#59_

**Comment by NathanSweet** [comment]
Nate: ik target is kinda like that circle but with a more defined border and more indicators. I guess ik target should be an option, so people can change it
Nate: doing them in the style of ik target is good I guess
Nate: not sure when I'll get to the code to have a list of icons so you can easily add many
Nate: I guess setting an icon will change length to 0. changing length > 0 will change to default bone icon
Nate: re are icons scalable, I think just like the ik target. we need multiple sizes for LOD but user can't resize

**Comment by NathanSweet** [comment]
Need `icon-boneIcon.png` for button in bone properties:
![](http://n4te.com/x/801-sj3x.png)

Then need 3 images per bone icon type eg `skin/icon-circle.png`, `skin/icon-circle-34.png`, `skin/icon-circle-67.png`.

**Comment by NathanSweet** [comment]
Need `skin/icon-ik.png` to match images in `skin/editor`.

**Comment by NathanSweet** [comment]
Using this issue to also remember: unpack, plus disabled icons for pack, export, save, unpack.

**Comment by Shiu** [comment]
Also needed are loading and loading-disabled icons

**Comment by NathanSweet** [comment]
Is this issue complete?
