### ISSUE TITLE
 Reversing the order of the keys resets curve handles

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#743]
**Description:**
If you try to reverse the order of the keys by box selection and scaling, the angle and length of the curve handles for each key will be reset as if you had pressed the `Bezier` button.

**Expected behavior:**
When the order of the keys is reversed, the length of the curve handles keep the same but the handle angle is reversed.

**Steps to reproduce:**
1. Open any Spine example project using Spine 4.1.21.
2. Select two or more boxes of keys whose curve handle angles or lengths have been changed from the default ones and scale the boxes to reverse them.
3. You can see the curve handles are reset like in the following video:
https://youtu.be/6dhhohRP3fk

**The version of Spine in which this issue was found:**
Spine 4.1.21

**This issue was reported on the following forum post:**
https://esotericsoftware.com/forum/d/24272-reversing-animation-breaks-curve-handle-tangents

**Comment by FabianoIlCapo** [comment]
+1 from me!

**Comment by samlletas** [comment]
Can confirm too, duplicated a run animation and reversed it to create a backwards run and ran into this issue.

**Comment by NathanSweet** [comment]
4.1.22

**Comment by samlletas** [comment]
Looks like the editor crashes when reversing some animations, for example in the attached project file I have 3 animations, "Hover" animation reverses fine, but reversing the other two animations crashes the editor, log file shows the following:

> Spine Launcher 4.1.10
Esoteric Software LLC (C) 2013-2022 | http://esotericsoftware.com
Windows 10 Home amd64 10.0
NVIDIA Corporation, NVIDIA GeForce GTX 1070/PCIe/SSE2, 4.6.0 NVIDIA 535.98
Starting: Spine 4.1.22 Professional
Spine 4.1.22 Professional
Licensed to: ***************************************************
Started.
OpenAL 1.1, Default audio device
ERROR: An unexpected error has occurred:
[ioob] index can't be >= size: 1 >= 1
   at s.fOV._(_:155)
   at s.ASK._(_:910)
   at s.lVI.L(_:271)
   at s.iGj._(_:226)
   at s.Brp._(_:74)
   at s.TJc._(_:318)
   at s.dmc._(_:146)
   at s.jEU._(_:110)
   at s.nGV._(_:50)
   at s.jEU._(_:35)
   at s.HGJ.run(_:259)
   <events>


[Test.zip](https://github.com/EsotericSoftware/spine-editor/files/11715757/Test.zip)

**Comment by NathanSweet** [comment]
Yep, the crash is also fixed in 4.1.22, thanks!

**Comment by NathanSweet** [comment]
Ah, a different crash was fixed. Still need to fix samlletas's crash.

**Comment by NathanSweet** [comment]
4.1.23
