### ISSUE TITLE
[Bug] 中文文件名导入显示为问号"?"

### ISSUE THREAD

**Issue by MXXXXXS** [EsotericSoftware/spine-editor#744]
![Spine_LkcJYNnwpy](https://github.com/EsotericSoftware/spine-editor/assets/28096993/6d15f5ad-e9af-42d8-b9b7-ad8eeca78fec)
![rNIJ1COuMf](https://github.com/EsotericSoftware/spine-editor/assets/28096993/9f6977cc-cdc8-4c69-a04d-6801e725f9cf)

平台: 
![image](https://github.com/EsotericSoftware/spine-editor/assets/28096993/dceacb13-7de9-432f-9061-8b1bd809809d)

spine 版本
![image](https://github.com/EsotericSoftware/spine-editor/assets/28096993/d47b16d6-9aa2-4a87-9522-8e44150bd165)

af designer版本
![image](https://github.com/EsotericSoftware/spine-editor/assets/28096993/aabe43c7-b2a5-4feb-8c69-52ff156aed11)

**Comment by MXXXXXS** [comment]
Solved when setting ui language chinese
![image](https://github.com/EsotericSoftware/spine-editor/assets/28096993/da0dd22a-9a6f-45cf-9377-d635433caa28)

This problem happens when setting English and Unicode
![image](https://github.com/EsotericSoftware/spine-editor/assets/28096993/b718bb03-c451-4767-ba57-6af78935fe23)

**Comment by NathanSweet** [comment]
Yep, as you found, the Chinese font setting in Spine is required to correctly render Chinese characters. I'm glad it's working for you now!
