### ISSUE TITLE
Textures may be packed incorrect when resampled in `Bilinear` or `Nearest` with some scale values

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#745]
**Description:**
When packing textures, if `Bilinear` or `Nearest` is set in the `Resample` option, some scale values pack the images incorrectly. For example, if the scale value is set to `0.49`, the image will look as if part of the image is duplicated, as shown in the blue boxed area of the following image:

![spineboy-pro_Bilinear_Scale-049](https://github.com/EsotericSoftware/spine-editor/assets/85478846/939e3d81-100c-490c-a971-9d156a9550b0)

-----

**Expected behavior:**
It should correctly look like the following:

![spineboy-pro_Bilinear_Scale-050](https://github.com/EsotericSoftware/spine-editor/assets/85478846/030c43d5-8406-4dbe-8727-63e274478640)

-----

**Steps to reproduce:**
1. Open "spineboy-pro.spine".
2. Open the `Texture Packer` window, set `Input folder` to Spineboy's images folder, and click the `Pack Settings` button.
3. Set `Scale` to `0.49` and `Resample` to `Bilinear`.
4. Run the texture pack and check the texture atlas page in the output folder.

Also, if you try with a scale value of `0.5` or `0.48`, you can confirm that this problem does **not** occur.

-----

**The version of Spine in which this issue was found:**
Spine 4.1.21

**This issue was reported on the following forum post:**
https://esotericsoftware.com/forum/d/24284-41%E7%89%88%E6%9C%AC%E5%AF%BC%E5%87%BA%E9%97%AE%E9%A2%98

**Comment by NathanSweet** [comment]
4.1.22
