### ISSUE TITLE
[PhotoshopToSpine] Allow saving export settings

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#748]
PhotoshopToSpine's export settings will be kept as long as you keep Photoshop running, but once you close and restart Photoshop, the settings are reset to default. This can be a hassle or error-prone if you have customized many settings as you have to re-set them manually each time you restart Photoshop. Allowing saving export settings, e.g. allowing specify them by layer name tags would be helpful for such cases.

This was suggested in the following thread:
https://esotericsoftware.com/forum/d/24361-suggestion-photoshop-to-spine-script-tagstrim_mask-t_size100

**Comment by FabianoIlCapo** [comment]
Oh please yes!

**Comment by NathanSweet** [comment]
It was always supposed to save the settings. It's fixed in v7.31+.

**Comment by FabianoIlCapo** [comment]
I confirm it is solved indeed, thank you so much! Finally it remembers 🙌
