### ISSUE TITLE
Respect locked bones when performing automatic weights calculation.

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#751]
Currently, the automatic calculation for weights performed by pressing the `Auto` button in the Weights view ignores weights locking. It would be more efficient if the locked bones are taken into account during the automatic calculation, since there are cases when you want to use the `Auto` button while using weights locking, such as when you bind another bone after setting the weights.

See related forum post:
https://esotericsoftware.com/forum/d/24468-%E8%A6%81%E6%9C%9B%E3%82%A6%E3%82%A7%E3%82%A4%E3%83%88%E3%81%AE%E8%87%AA%E5%8B%95%E8%A8%88%E7%AE%97%E3%82%92%E8%A1%8C%E3%81%86%E9%9A%9B%E3%82%A6%E3%82%A7%E3%82%A4%E3%83%88%E3%83%AD%E3%83%83%E3%82%AF%E3%81%97%E3%81%9F%E3%83%9C%E3%83%BC%E3%83%B3%E3%81%AE%E5%80%A4%E3%82%92%E7%B6%AD%E6%8C%81%E3%81%99%E3%82%8B%E6%A9%9F%E8%83%BD%E3%81%8C%E3%81%BB%E3%81%97%E3%81%84%E3%81%A7%E3%81%99

**Comment by NathanSweet** [comment]
4.2.00-beta
