### ISSUE TITLE
IKConstraint stretch not applied in runtimes

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-editor#753]
Forum thread URL with reproduction project:
https://esotericsoftware.com/forum/d/24584-ik-constraint-stretch-not-applied
Reproduced with latest spine-unity runtime and SkeletonViewer 4.1.23.
Stretch appears not to be applied in runtimes, but applied in the Spine Editor, applies to both `.json` and binary loading paths.

(Re-export in both `.json` and binary format did not resolve the issue.)

**Comment by badlogic** [comment]
Huh, that's extremely weird as the editor uses the Java runtime itself with just a thin layer on top of it.

**Comment by sr4dev** [comment]
Forum link has broken🤔
This is a right link.
https://en.esotericsoftware.com/forum/d/24584-ik-constraint-stretch-not-applied

**Comment by HaraldCsaszar** [comment]
Thanks for reporting that the above forum URL did not work for you. The original URL works from my end, so it might be related to your language settings and server redirection. May I ask which language you normally use to view the Spine forum (what is the prefix before `.esotericsoftware.com`)?

**Comment by sr4dev** [comment]
![image](https://github.com/EsotericSoftware/spine-editor/assets/9159336/5672deb3-a217-4690-afed-be33c4e33cc8)

Sorry about that. I didn't realize the language setting was involved. 
My language setting is Japanese(https://ja.esotericsoftware.com/).

**Comment by NathanSweet** [comment]
@sr4dev It was a bug with our website, now fixed. Thanks for letting us know!

**Comment by NathanSweet** [comment]
Sorry it took so long to dig into this!

The bone `LegLower_R` has a scale of zero, or very near zero. This will interfere with a number of things in Spine, including IK. It's not advised to hide a bone that way.
