### ISSUE TITLE
Timeline bar jumps when Audio events are keyed 

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#754]
**Description:**
Adding an audio event key in an animation causes the timeline bar to jump and start playing from an unintended frame, even if playback begins at frame 0. The timeline bar will always jump to frame 60 if the animation duration is more than 60 frames.

**Expected behavior:**
Animation can be played back from frame 0 even if an audio event key is added. 

**Steps to reproduce:**
1. Open the `spineboy-pro` example project in Spine 4.1.23.
2. Select `footstep.mp3` in the `Audio` node in the Tree view, and click `New Event` button in the bottom of the view.
3. Create a new animation and add the audio event key at frame 0.
4. Add any bone transform key after frame 60, then play the animation.
5. Now you can see the timeline bar jumps to frame 60 even if you start the animation from frame 0.

**The version of Spine in which this issue was found:**
Spine 4.1.23

**This issue was reported on the following forum post:**
https://esotericsoftware.com/forum/d/24602-timeline-playback-skipping-with-audio-events-m1-mac-spine-40--41-

**Comment by misaki-eymard** [comment]
I forgot to add that this problem apparently only occurs on Mac PCs; both M1 Macs and Intel Macs have been reported to have this issue.

**Comment by NathanSweet** [comment]
We have fixed this in 4.2. Also the 4.2.04 launcher fixes the Mac audio problems for all 4.0 and 4.1 versions.
