### ISSUE TITLE
Setting a decimal point value for `Row height` prevents selecting the middle timeline by box selection.

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#755]
**Description:**
If you set the `User Interface - Row height` in the Spine Settings to a value that includes a decimal point, such as 23.5, it will not allow you to box-select only the middle timeline when multiple transform keys are set to a bone's timelines.
For example, if you try to box-select only keys on the Translate timeline, keys of the Rotation timeline will be selected unintentionally. 

**Expected behavior:**
Only keys on a specific timeline can be box-selected, even if `Row height` is set to a value containing a decimal point.

**Steps to reproduce:**

1. Open the Spine editor 4.1.23.
2. Open the Spine settings dialog.
3. Set `User Interface - Row height` to `23.5` and reopen the editor.
4. Open spineboy-pro.spine.
5. Select `head` bone, and try to box-select only keys on the Scale timeline. Then, you will see that the keys on the Rotation timeline are also selected.

**The version of Spine in which this issue was found:**
Spine 4.1.23

**This issue was reported on the following forum post:**
https://esotericsoftware.com/forum/d/24631-weird-selection-behavior

**Comment by NathanSweet** [comment]
4.2.45-beta
