### ISSUE TITLE
Keyed `Shear Y` mix value cannot be imported correctly via JSON data importing

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#757]
**Description:**
If you keyed the `Shear Y` mix value of a transform constraint in an animation then export the skeleton in JSON format and import the exported JSON, the `Shear Y` mix value will be 0 regardless of the keyed value.

**Expected behavior:**
Keyed `Shear Y` mix values are correctly imported via JSON data importing.

**Steps to reproduce:**

1. Open the Spine editor 4.1.23.
1. Open spineboy-pro.spine and create a new animation.
1. Select "aim-torso-transform" in the Constraints node of the Tree view, set a transform constraint key with the `Shear Y` mix: 100.
1. Export the skeleton in JSON format. Here is the export settings the bug was able to reproduce:
![Screenshot 2023-08-23 at 8 45 39](https://github.com/EsotericSoftware/spine-editor/assets/85478846/5fdc8a12-21cf-4c2c-a57d-d38a524ef999)
1. Import the exported JSON file via `Import Data...` in the Spine menu, then you can see the `Shear Y` mix value you keyed at step(3) is 0.

**The version of Spine in which this bug was found:**
Spine 4.1.23

**This bug was reported on the following forum post:**
https://esotericsoftware.com/forum/d/24667-json%E3%82%92%E3%82%A4%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%88%E3%81%97%E3%81%9F%E9%9A%9B%E3%81%AB%E3%82%B3%E3%83%B3%E3%82%B9%E3%83%88%E3%83%AC%E3%82%A4%E3%83%B3%E3%83%88%E3%81%AE%E3%82%B7%E3%82%A2%E3%83%BCy%E3%81%AE%E5%80%A4%E3%81%8C%E3%81%8A%E3%81%8B%E3%81%97%E3%81%8F%E3%81%AA%E3%82%8A%E3%81%BE%E3%81%99

**Comment by NathanSweet** [comment]
I was unable to repro with these steps. My 4.1.23 JSON is here:
http://n4te.com/x/8024-spineboy-pro.json
The animation data is:
```
	"asd": {
		"transform": {
			"aim-torso-transform": [
				{ "mixRotate": 0, "mixX": 0, "mixScaleX": 0 }
			]
		}
	},
```
That is correct, as values that are 1 are omitted. Also `mixY` and `mixScaleY` are omitted when the same as the X values.

To check: import into Spine, go to animate mode, make `asd` the active animation`, click the `Transform: aim-torso-transform` row in the dopesheet to select the constraint,  note the shear Y value is 100.

**Comment by misaki-eymard** [comment]
Sorry, the step(3) was incorrect: add a key with `Shear Y:0` at frame 0, then add a key with `Shear:Y 100` at another frame. Then do the steps from (4), you can see the `Shear Y` mix value of the second key is 0.

**Comment by NathanSweet** [comment]
This was fixed Oct 26, 2023. It will be in 4.1.25 if we do another 4.1 release, else it will be in 4.2.00-beta.
