### ISSUE TITLE
Weight locking is ignored in linked meshes

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#758]
**Description:**
When using linked meshes, weight locking is respected on the source mesh, but it is ignored on the target mesh. This may cause confusion so it should have the same behavior in weight locking as in the source mesh.

**Expected behavior:**
If there is a weight that is locked, the value of that weight cannot be changed, even if it is a linked mesh.

**Steps to reproduce:**

1. Open the Spine editor 4.1.23 and open "mix-and-match-pro.spine".

1. Select a mesh attachment `boy/arm-front` in the `full-skins/boy` skin and lock weights other than `arm-back-up-2`:
![Screenshot 2023-08-24 at 8 43 12](https://github.com/EsotericSoftware/spine-editor/assets/85478846/e99b3d81-9c84-44a2-8870-793612b1cc12)
Make sure that if you attempt to change the weights of this mesh in this state, you will not be able to change them at all.

1. Select a linked mesh attachment `girl/arm-front` in the `full-skins/girl` skin. If you attempt to change the weights of this mesh, the weight locking is ignored and you can change them.

**The version of Spine in which this bug was found:**
Spine 4.1.23

**This issue was reported on the following forum post:**
https://esotericsoftware.com/forum/d/24672-%E3%83%AA%E3%83%B3%E3%82%AF%E3%83%A1%E3%83%83%E3%82%B7%E3%83%A5%E5%85%88%E3%81%AB%E3%82%A6%E3%82%A7%E3%82%A4%E3%83%88%E3%83%AD%E3%83%83%E3%82%AF%E7%8A%B6%E6%85%8B%E3%81%8C%E5%8F%8D%E6%98%A0%E3%81%95%E3%82%8C%E3%81%AA%E3%81%84/

**Comment by NathanSweet** [comment]
4.2.00-beta
