### ISSUE TITLE
Sequence keys playback may not be correct when the keys' FPS and timeline FPS are the same

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#759]
**Description:**
If the FPS of a sequence key and the timeline FPS match, e.g.  the FPS of the sequence key is 60 and the timeline FPS is 60, keyed it may cause the frame to be skipped without correctly changing to the next one. This bug cannot be seen when the sequence key is keyed at the beginning of the animation, but it can be seen from frame 240 onward.

**Expected behavior:**
Every frame the next frame is displayed correctly.

**Steps to reproduce:**
1. Download the attached file in this forum post: https://esotericsoftware.com/forum/d/24758-png-sequence-bug-skips-frames-
1. Open the `png_sequence_bug.spine` and turn to animate mode.
2. Move the timeline bar to check the flame animation: the sequence animation from frame 100 to 133 correctly shows the next frame for each frame, but the sequence animation from frame 300 to 333 the image of the previous frame sometimes remains and the frames in between are skipped.

**The version of Spine in which this bug was found:**
Spine 4.1.23

**This issue was reported on the following forum post:**
https://esotericsoftware.com/forum/d/24758-png-sequence-bug-skips-frames-

**Comment by NathanSweet** [comment]
This project uses a 60fps timeline. The time in seconds for the key on the sequence timeline on frame 300 was calculated as `5.0000005`, so the actual key does not trigger until very slightly after frame 300. We need to round the time in seconds slightly to avoid this.

**Comment by NathanSweet** [comment]
4.2.00-beta
