### ISSUE TITLE
New...>Parent Bone option when Slot/Attachment is selected

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#76]
Currently, users can use the hidden feature of the `Create` tool:
- Select a parent bone.
- Hold `Ctrl`
- Select one or more attachments/images.
- Release `Ctrl`
- Create the new bone by clicking and dragging normally.

The end result is that it creates a new bone as a child of the first selected bone, and puts the selected slots as children of the new bone.
This is great for the initial rigging process.

Alternatively, it would be helpful if you could do this:
- Select a slot or attachment in the tree.
- Choose `New...` > `Bone`

![newparent](https://cloud.githubusercontent.com/assets/1911082/16879601/e2870b60-4ae3-11e6-93c1-04e057fd6d6e.png)

In the tree, it would create bone in between the slot and the slot's original parent bone.
This is great for when you need to branch certain parts out: For example, if you have mouth, eyes, and head slots under the head bone, and you realize you need to translate the mouth independently or scale the eyes independently.

The current thing I'm on the fence on is where the new bone should be positioned.
Seems like there are three options:
1. Zero local position and rotation and unit scale.
2. Put the bone on the center/centroid of the currently active attachment, with 0 world rotation and unit scale.
3. Temporarily act like the `Create` tool and let the user decide

**Comment by NathanSweet** [comment]
Went with creating the bone with 0,0 local position, 3.8.09-beta.
