### ISSUE TITLE
The output path is shortened by selecting `ALL` in the `Animations` section of the PNG export settings.

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#762]
**Description:**
When exporting animations to PNG format with `Export type` set to `Animation` and selecting `ALL` in the `Animations` section of the export settings, the last part of the output path will be removed more and more with each selection.

For example, if the original path was `Spine/Spineboy/PNG/walk.png`, if you select `ALL` first, Spine removes the `/walk.png` part and it becomes `Spine/Spineboy/PNG`.
Then, select `Current` and re-select `ALL`, Spine removes `/PNG` and it becomes `Spine/Spineboy`.
Selecting `Current` again and `ALL` again removes the `/Spineboy` and it becomes a `Spine`.

**Expected behavior:**
If you select `ALL`, the part with the extension such as `AnimationName.png` will be removed, but the folder path will not be affected.

**Steps to reproduce:**
1. Open a Spine project.
2. Open the Export window and select PNG from the side menu.
3. Set the PNG export settings as shown in the following image:
![Screenshot 2023-10-11 at 16 27 13](https://github.com/EsotericSoftware/spine-editor/assets/85478846/ae4bbe57-a91a-47ad-874a-4bb09164db3a)
4. Then select `ALL` in the `Animations` section. You will see that the output path is shortened.
5. Select `Current` and select `ALL` again. You will see that the output path is shortened more.

**The version of Spine in which this bug was found:**
Spine 4.1.23

**This issue was reported on the following forum post:**
https://ja.esotericsoftware.com/forum/d/18550-export-path-problem

**Comment by NathanSweet** [comment]
4.2.00-beta
