### ISSUE TITLE
`Strip whitespace X/Y` may strip opaque images

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#763]
**Description:**
Under certain limited conditions, `Strip whitespace X/Y` may remove opaque images. The conditions appear as follows:
- **Both or one of `Strip Whitespace X/Y` is enabled** in the texture packer settings. 
- The image is turned into a mesh attachment and is in a certain state. (The specific state is not clear yet, but it seems to require a certain number of vertices.)

**Expected behavior:**
`Strip whitspace X/Y` removes only the transparent areas, the opaque areas will be packed into the texture atlas page.

**Steps to reproduce:**
1. Download the attached zip file:
[Strip-whitespace-X:Y_may strip-opaque-images.zip](https://github.com/EsotericSoftware/spine-editor/files/12911148/Strip-whitespace-X.Y_may.strip-opaque-images.zip)

1. Export the skeleton with the following texture packer settings:
 ![Screenshot 2023-10-16 at 9 58 02](https://github.com/EsotericSoftware/spine-editor/assets/85478846/1eb8ab94-2b20-446d-a88b-445b72f329d2)

1. You will see the exported texture is blank. (The image should be 16 * 16 px as set in the `Min width/height`.)

If you disable both `Strip whitespace X/Y`, you should see the texture output as expected.
Also, even if you enable both or one of `Strip Whitespace X/Y`, you can see the correct texture output by removing a vertex of the `image` mesh attachment. It should not matter which vertex is deleted. Moving any vertex may also fix this issue. 

**The version of Spine in which this bug was found:**
Spine 4.1.23

**This issue was reported via email:**
FMfcgzGtxdbQMVhcdrhGFjCHGzVNRtlV

**Comment by NathanSweet** [comment]
4.2.00-beta
