### ISSUE TITLE
Undoing creation of physics contraint will also undo Split action

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#767]
In an empty project:
1. create a bone.
2. split the bone.
3. select the new bones created from the split action, and create a physics constraint.
4. undo.

When undoing, the physics constraint will be gone, but the split bones action will also be gone so you are left with a single bone. The expected behaviour is that when undoing the physics constraint, you should still be left with multiple bones.

**Comment by NathanSweet** [comment]
4.2.04-beta
