### ISSUE TITLE
Selecting a sequence key unintentionally selects the parent bone

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#772]
**Description:**
When you select a sequence key in the Dopesheet view, its parent bone is automatically selected. Normally, simply selecting a key does not select the bone that has that key, so it is possible to maintain the selection state and change the timing of the key, but when you select a sequence key, the selection state changes just by selecting the key. Also, for example, if you try to box-select keys in the Dopesheet view and the first selection is a sequence key, the box-selection is interrupted because it is determined as you change the selected bone.

**Expected behavior:**
Selecting a sequence key does not change the selection state.

**Steps to reproduce:**
1. Download the attached zip file: [Sequence-key-issue.zip](https://github.com/EsotericSoftware/spine-editor/files/13868859/Sequence-key-issue.zip)
2. Open the project and go into animate mode, select any sequence key on the `muzzle` bone timeline in the Dopesheet view.
3. Then you can see that the muzzle bone is selected, while you just selected the key.

**Workarounds:**
As for the issue mentioned in the description about the box selection being interrupted, it can be avoided by not selecting the sequence key first. In other words, if you enclose the rotation, translation, attachment, etc. keys to be selected first, you can select them successfully.

**The version of Spine in which this issue was found:**
Spine 4.1.24 / 4.2.09-beta

**This issue was reported via email:**
FMfcgzGwJcgmmQtlZMFsSCqhTFwvWsWP

**Comment by NathanSweet** [comment]
It's the correct behavior when the dopesheet/graph is locked, but should not change the viewport/tree selection when the dopesheet/graph is unlocked. Fixed in 4.2.10-beta!
