### ISSUE TITLE
Skeleton pose is different when animation is played and not played

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#773]
**Description:**
An issue has been identified in a particular project where the skeleton pose is different when the animation is playing and when it is not. When the animation is playing, the pose shown in the viewport or Preview view appears normal, but when you stop the animation and manually move the timeline bar in the Dopesheet or Graph view, the pose is different than when it was playing. Also, when exporting to GIF or PNG format, the output will be the same as when playing the animation. So only the poses while the animation is not playing are wrong.
The Spine project in which this problem was found was originally created in Spine 4.1.24 and the problem occurred when it was opened in Spine 4.2.09-beta.

**Expected behavior:**
The result is the same pose displayed in the viewport when the animation is not playing as the pose when the animation is playing.

**Steps to reproduce:**
1. Download a user-provided Spine project as an attachment to this email: FMfcgzGwJckGmWcqSvhJBcVfrLpLFPMS
1. Open the project and go into animate mode, play the animation named `LK_Sw_airAtk4_1` and make sure there is no pause breakdown during the animation. (This animation is quite short, so it will be easier to see if you slow down the playback speed in the Playback view.)
1. Stop playback and manually move the timeline bar in the Dopesheet or Graph view. You will see that the pose results are different than during the playback, such as the angle of the feet.

**The version of Spine in which this bug was found:**
Spine 4.2.09-beta

**This issue was reported on the following thread:**
https://esotericsoftware.com/forum/d/25407-upgrade-to-spine-4209-beta-cause-problem

**Comment by NathanSweet** [comment]
The link to the file in the email has expired. I requested they send it again. We'll reopen if so.
