### ISSUE TITLE
The position and rotation of hidden mesh attachments are shifted after the parent slot is moved continuously

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#774]
**Description:**
There is a bug that if a mesh attachment that is not yet bound to a bone is hidden and its parent slot is moved twice in a row in the Tree view to change the parent bone, the position and rotation of the mesh attachment will be incorrect.

**Expected behavior:**
If the parent bone of a slot is only changed, the transformations of the attachments contained in that slot are maintained.

**Steps to reproduce:**
1. Open the Spineboy example project.
2. Select the eye attachments (`eye-indifferent` and `eye-surprised`) and remove the bones which are bound them in the Weight view.
3. Select the `eye` slot and move it to under the `hair1` bone. <img width="1108" alt="Screenshot 2024-01-21 at 14 15 18" src="https://github.com/EsotericSoftware/spine-editor/assets/85478846/d189c53a-fd2a-469e-906f-df2d4703ddd6">
5. Select the `eye` slot and move it to under the `hair2` bone. <img width="1108" alt="Screenshot 2024-01-21 at 14 15 50" src="https://github.com/EsotericSoftware/spine-editor/assets/85478846/25144724-2522-4c7d-9826-6301b2f3cf3a">
7. Show the hidden eye attachment. You will see that the eye attachment has been moved to a position well away from the head, and the rotation has also been changed. <img width="1108" alt="Screenshot 2024-01-21 at 14 14 37" src="https://github.com/EsotericSoftware/spine-editor/assets/85478846/9f06777a-5ec5-4d1f-b89d-b3ceef20795e">

**The version of Spine in which this bug was found:**
Spine 4.1.24 and 4.2.09-beta

**This issue was reported on the following thread:**
https://esotericsoftware.com/forum/d/25457-hidden-attachments-in-slot-move-to-unintended-locations

**Comment by NathanSweet** [comment]
4.2.26-beta
