### ISSUE TITLE
Mesh vertices cannot be deformed directly if the parent slot's timeline has a slot attachment key in the animation

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#776]
**Description:**
In Spine 4.2.09-beta there is a bug that if there are mesh attachments in the same slot and the slot attachment key to switch to one of the mesh attachments is in the animation, the vertices of the other mesh attachment cannot be deformed directly. This does not mean that the deform keys cannot be added to the animation, but the vertex positions cannot be moved even if the deform key is added. The following video demonstrates this bug:
https://github.com/EsotericSoftware/spine-editor/assets/85478846/6f4c195b-f157-4f16-b819-2458fba978de

**Expected behavior:**
No matter what attachments are in the same slot, and even if the parent slot's timeline has a slot attachment key, the active mesh attachment can be deformed in animations.

**Steps to reproduce:**
1. Download the attached zip file: [Mesh-vertices-cannot-be deformed-directly.zip](https://github.com/EsotericSoftware/spine-editor/files/14095312/Mesh-vertices-cannot-be.deformed-directly.zip)
1. Open the Spine project in it and and switch to animate mode.
2. Try to deform the mesh attachment "A" that is displayed when the timeline bar is aligned with frame 0. You will see that any vertices cannot be moved.

If the timeline bar is set to frame 10 and mesh attachment "B" is displayed, you will see that "B" can be deformed.

If you delete the slot attachment key on frame 10, you will see that mesh attachment "A" is also deformable.

Alternatively, you can leave the slot attachment key in place and change the mesh attachment "B" back to a region attachment, and you will see that "A" is deformable.

**The version of Spine in which this bug was found:**
Spine 4.2.09-beta

**This bug was reported on the following thread:**
https://esotericsoftware.com/forum/d/25493-4209-beta-%E6%9C%89%E6%97%B6%E5%80%99%E6%97%A0%E6%B3%95%E8%BF%9B%E8%A1%8C%E7%BD%91%E6%A0%BC%E5%8F%98%E5%BD%A2

**Comment by NathanSweet** [comment]
4.2.10-beta
