### ISSUE TITLE
Linked meshes cause errors when importing exported JSON data into an existing skeleton

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#777]
**Description:**
If the skeleton has a linked mesh, any attempt to import the exported JSON data into an existing skeleton in the project will always result in an error.

**Expected behavior:**
Import completes normally with no errors.

**Steps to reproduce:**
1. Download the attached .zip file:
[Linked meshes cause errors when importing exported JSON data into an existing skeleton.zip](https://github.com/EsotericSoftware/spine-editor/files/14325230/Linked.meshes.cause.errors.when.importing.exported.JSON.data.into.an.existing.skeleton.zip)
2. Open the Spine project file in it, and export the skeleton as a JSON data file.
3. Import the exported JSON file via the Import Data dialog with the following settings:
- Uncheck `New project`
- Choose `Import into an existing skeleton:` and `Existing attachment: Ignore`
4. Then, you will see the following error:
![Screenshot 2024-02-19 at 9 28 28](https://github.com/EsotericSoftware/spine-editor/assets/85478846/634676e7-48e0-43b1-a7af-221ccb231b3d)
If you click the `Open Log` button, you will see the following error log:
```
ERROR: Error importing skeleton data file: /Linked meshes cause errors when importing exported JSON data into an existing skeleton/exported-JSON-4-2-beta/Linked-meshes-test.json
Please be sure to choose a valid skeleton JSON or binary file.
[error] Source mesh not found for linked mesh: [linked mesh: LinkedMesh, source: Source, slot: Image]
```

**Work around:**
This issue only occurs when importing into an existing skeleton, so if you import as a new skeleton, it will import correctly.

**Versions of Spine where this bug was found:**
Spine 4.1.24 and 4.2.09-beta

**This issue was reported on the following thread:**
https://esotericsoftware.com/forum/d/25590-%E3%83%87%E3%83%BC%E3%82%BF%E3%82%A4%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%88%E3%81%A7error-error-importing-skeleton-data-file-%E3%81%8C%E7%99%BA%E7%94%9F%E3%81%99%E3%82%8B

**Comment by davidetan** [comment]
Fixed in 4.2.10-beta (5d910be2)
