### ISSUE TITLE
Moving a draw order key deselects slots

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#781]
**Description:**
After changing the draw order in 4.2.44-beta, moving the added draw order key deselects the slot. This is different from the behavior up to 4.1.24 and seems to be a bug. See the video below for more information:
https://github.com/EsotericSoftware/spine-editor/assets/85478846/a2ff7952-7eea-4b1a-aaf0-85dd49844b45

**Expected behavior:**
As with behavior up to 4.1.24, moving a key does not affect selecting a slot.

**Steps to reproduce:**
1. Open any Spine project with 4.2.44-beta.
2. Select any slot in the `Draw Order` section of the tree view and drag to change the draw order.
3. Move the added draw order key in the dopesheet view.
4. The slot selected in step2 is deselected.

**The version of Spine in which this issue was found:**
Spine 4.2.44-beta

**This issue was reported on the following forum post:**
https://ja.esotericsoftware.com/forum/d/25743-%E3%83%90%E3%82%B0%E5%A0%B1%E5%91%8A42beta%E3%81%8B%E3%82%89%E8%A1%A8%E7%A4%BA%E9%A0%86%E3%81%AE%E9%81%B8%E6%8A%9E%E4%BF%9D%E6%8C%81%E3%81%8C%E5%A4%96%E3%82%8C%E3%82%8B

**Comment by NathanSweet** [comment]
4.2.48-beta
