### ISSUE TITLE
Importing exported skeleton data (JSON or binary format) results in wrong order of constraints

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#782]
**Description:**
If you export skeleton data in JSON or binary format and then import it, the order of the constraints is imported differently than the original order.

**Expected behavior:**
The order of the imported skeleton's constraints will be the same as the order of the constraints when the skeleton data is exported.

**Steps to reproduce:**
1. Open `mix-and-match-pro` with 4.2.46-beta.
2. Export the skeleton to JSON or binary format.
3. Import the exported `.json` or `.skel` file via `Spine menu -> Import Data...`. For easier comparison, uncheck `New project` and import under a different name as `Create a new skeleton`.
4. Then, you can see that the order of the constraints is different between the skeletons that was originally in the project and the imported skeleton.

**The version of Spine in which this issue was found:**
Spine 4.2.46-beta

**This issue was reported on the following forum post:**
https://ja.esotericsoftware.com/forum/d/25745-%E3%83%90%E3%82%B0%E5%A0%B1%E5%91%8Ajson%E6%9B%B8%E3%81%8D%E5%87%BA%E3%81%97%E3%81%A7ik%E3%82%84%E3%82%B3%E3%83%B3%E3%82%B9%E3%83%88%E3%83%AC%E3%82%A4%E3%83%B3%E3%83%88%E3%81%8C%E5%A3%8A%E3%82%8C%E3%82%8B

**Comment by NathanSweet** [comment]
4.2.48-beta
