### ISSUE TITLE
Attachments are not displayed in the tree view after playing an animation in the animate mode when using certain tree filters

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#783]
**Description:**
If you enable the Slot and Attachment filters in the tree filter and play any animation in the animate mode, attachments will disappear from the tree view.
Here is a video showing this issue:
https://github.com/EsotericSoftware/spine-editor/assets/85478846/ba297bc2-93d7-4d27-97c8-144b425c1d1b

**Expected behavior:**
Attachments remains visible in tree view after animation playback starts.

**Steps to reproduce:**
1. Open any Spine project with 4.2.46-beta.
2. Enable slot and attachments filters in the tree view.
3. Play any animation in the animate mode. You will then see the attachments disappear in the tree view at the moment playback begins.
The condition persists even after the animation is stopped playing. It can be fixed by switching to setup mode or reselecting the tree filter.

**The version of Spine in which this issue was found:**
Spine 4.2.46-beta

**This issue was reported on the following forum post:**
https://ja.esotericsoftware.com/forum/d/25749-%E6%A8%B9%E7%8B%80%E5%B1%A4%E7%B4%9A%E5%9C%96%E9%A1%AF%E7%A4%BA%E5%95%8F%E9%A1%8C

**Comment by NathanSweet** [comment]
4.2.48-beta
