### ISSUE TITLE
Allow `Output type:Layers` to be selected in `Export type:Animation` in the PSD export.

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#784]
Currently, `Output type:Layers` can only be available when the `Export type` is `Current pose` in the PSD export. If Spine can export each frame as a PSD with separate layers by selecting `Output type:Layers` even when `Export type` is `Animation`, this can be useful if you want to edit the exported PSD with an external tool.

Related forum thread:
https://esotericsoftware.com/forum/d/25752-how-to-export-psd-layers-of-every-pose-by-script

**Comment by NathanSweet** [comment]
When exporting an animation, if we export a layer for each attachment for each frame, you'd get `<attachment count> * <frame count>` layers. That could be a LOT of layers.

**Comment by NathanSweet** [comment]
In 4.2.48-beta you can choose `Layers` for `File per frame` when exporting `Animation`.
