### ISSUE TITLE
Missing page information in atlas file when packing texture atlas under certain conditions

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#785]
**Description:**
Packing a texture atlas under the following conditions causes a problem in that some texture atlas page information is missing in the exported atlas file:

- There is a subdirectory in the images folder, and the skeleton refers to the images in that subdirectory.
- Multiple texture atlas pages are output after packing.

This problem occurs whether the texture atlas is packed during JSON or Binary export, or whether it is packed using the texture packer as a stand-alone tool.
What is lost is the information on the first-packed pages; the information on the last-packed pages is written to the atlas file normally.

**Expected behavior:**
All texture atlas page information is successfully written to the atlas file.

**Steps to reproduce:**
1. Download the attached .zip file: [missing-page-information.zip](https://github.com/EsotericSoftware/spine-editor/files/14797366/missing-page-information.zip)
1. Run Spine 4.2.56-beta and open the Texture packer, then pack the images by specifying the images folder in the downloaded zip as the `Input folder`. Or open the Spine project in the zip and do a JSON export with the following settings:
![Screenshot 2024-03-29 at 9 59 46](https://github.com/EsotericSoftware/spine-editor/assets/85478846/4aa7f2a9-23c5-495e-80cc-161f949498cb)
It is important that `Image folder` is selected in the `Pack` section, but it does not matter if `Single atlas` is selected instead of `Atlas per skeleton`.

The default settings for the texture packer can reproduce this problem.
![Screenshot 2024-03-29 at 9 58 44](https://github.com/EsotericSoftware/spine-editor/assets/85478846/4fb36473-36e1-4d0a-b0d0-850b13976831)

**The version of Spine in which this bug was found:**
Spine 4.2.56-beta

**This issue was reported on the following thread:**
https://ja.esotericsoftware.com/forum/d/25861-4256-beta-%E3%83%86%E3%82%AF%E3%82%B9%E3%83%81%E3%83%A3%E3%82%A2%E3%83%88%E3%83%A9%E3%82%B9%E3%81%AE%E6%9B%B8%E3%81%8D%E5%87%BA%E3%81%97%E4%B8%8D%E5%85%B7%E5%90%88

**Comment by NathanSweet** [comment]
4.2.57-beta
