### ISSUE TITLE
Importing skeleton data results in slight timing discrepancies for some keys

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#786]
**Description:**
Once a skeleton is exported in JSON format and then re-imported, keys that were originally placed in integer frames are placed at slightly off-timings. For example, as seen in the screenshot below, a key that was originally placed at frame `5` is placed at timing `5.001`:
![timming](https://github.com/EsotericSoftware/spine-editor/assets/85478846/f57386d1-368d-4ac5-9973-7943075af115)

**Expected behavior:**
After importing the JSON data, the keys are placed at the same timing as the original skeleton.

**Steps to reproduce:**
1. Create a new project with Spine 4.2.56-beta.
2. Switch to animate mode and add the rotation and scale keys of the root bone at frame `0`, `5`, `10`, and `15`, with random values in the animation:
![Screenshot 2024-03-29 at 11 13 52](https://github.com/EsotericSoftware/spine-editor/assets/85478846/04001af2-509d-4ec4-ae4c-e7310c838594)

4. Export the skeleton data of this project in JSON format.
5. Import the exported JSON file via `Spine menu -> Import Data...` as a new skeleton.
6. If you you select some keys for the animation of the imported skeleton, you will see that some of the keys that would have been on integer frames in the original skeleton have been moved to a halfway frame, such as `5.001` or `9.999`.

**The version of Spine in which this bug was found:**
Spine 4.2.56-beta

**This issue was reported on the following thread:**
https://ja.esotericsoftware.com/forum/d/25863-%E6%9B%B8%E3%81%8D%E5%87%BA%E3%81%97%E3%81%9Fjson%E3%82%92%E3%82%A4%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%88%E3%81%99%E3%82%8B%E3%81%A8%E3%82%AD%E3%83%BC%E3%81%8C%E3%81%9A%E3%82%8C%E3%81%BE%E3%81%99

**Comment by NathanSweet** [comment]
4.2.57-beta
