### ISSUE TITLE
Image export does not correctly detect maximum bounds when no animation is selected

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#787]
**Description:**
Depending on whether animation is selected or not, the maximum bounds for exporting in image formats such as GIF and PNG will vary. The animation selected does not have to match the animation to be exported; as long as an animation is selected, the image can be exported without being cropped.

This behavior can cause undesirable cropping, especially when performing exports via the CLI.

**Expected behavior:**
Whether or not an animation is selected, the maximum boundary of the animation is correctly recognized.

**Steps to reproduce:**
1. Download the attached .zip file: [incorrect-bounds.zip](https://github.com/EsotericSoftware/spine-editor/files/14915897/incorrect-bounds.zip)
2. Open the Spine project contained in the .zip with Spine 4.2.64-beta. 
3. Switch to the animate mode.
4. Do the GIF export with the default settings.
5. You should see the following results for the exported image: 
![exported-GIF](https://github.com/EsotericSoftware/spine-editor/assets/85478846/63e213b2-1686-4850-be39-b7ad2814de7b)
1. Then, after select the animation on the Tree view, do the GIF export with the default settings again.
5. You should see the following results for the exported image: 
![exported-GIF](https://github.com/EsotericSoftware/spine-editor/assets/85478846/c0e32792-730d-44c0-b7e5-6d1c6dc165b5)

**The version of Spine in which this issue was found:**
Spine 4.2.64-beta

**This issue was reported on the following thread:**
https://esotericsoftware.com/forum/d/25962-%E5%85%B3%E4%BA%8Egif%E5%9B%BE%E7%89%87%E5%AF%BC%E5%87%BA%E7%9A%84%E9%97%AE%E9%A2%98

**Comment by NathanSweet** [comment]
4.2.66-beta
