### ISSUE TITLE
Sequence attachments cause errors when exporting due to changes in 4.2.67-beta

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#788]
**Description:**
Since 4.2.67-beta, exporting a skeleton that uses sequence attachments in the JSON or binary format now displays the following error message: 

```
Image for attachment [region: error_test_0000, slot: error_test_0000] not found: error_test_00000001
Image for attachment [region: error_test_0000, slot: error_test_0000] not found: error_test_00000002
Image for attachment [region: error_test_0000, slot: error_test_0000] not found: error_test_00000003
Image for attachment [region: error_test_0000, slot: error_test_0000] not found: error_test_00000004
```

However, the **export itself does not actually fail**. The exported skeleton data can be loaded correctly in the Skeleton Viewer. Therefore, the problem may be the condition under which the error message is displayed.

**Expected behavior:**
If the export is successful, no error message is displayed.

**Steps to reproduce:**
1. Download the attached .zip file: [sequence_error.zip](https://github.com/EsotericSoftware/spine-editor/files/14974407/sequence_error.zip)
2. Open the Spine project in it using Spine 4.2.68-beta, and export the skeleton in the JSON or binary format.
3. Then you will see the error message saying that the attachment images could not be found, even though the image paths are correct.

**The version of Spine in which this bug was found:**
Spine 4.2.67-beta and 4.2.68-beta.

**This issue was reported on the following thread:**
https://esotericsoftware.com/forum/d/25988-%E3%83%90%E3%82%B0%E5%A0%B1%E5%91%8Ajson%E6%9B%B8%E3%81%8D%E5%87%BA%E3%81%97%E3%81%AE%E9%9A%9B%E9%80%A3%E7%95%AA%E3%81%AE%E3%82%A8%E3%83%A9%E3%83%BC%E3%81%8C%E7%99%BA%E7%94%9F%E3%81%97%E3%81%BE%E3%81%99

**Comment by NathanSweet** [comment]
4.2.69-beta
