### ISSUE TITLE
Clipping attachment boundaries are not used as maximum boundary criteria when exporting.

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#789]
**Description:**
In Spine 4.1, if the entire skeleton was clipped by the Clipping attachment, the boundary of the clipping attachment was automatically recognized and exported as the maximum boundary for that animation. For example, here is the result of cropping Spineboy's `jump` animation with clipping attachment and exporting it in GIF format:
![4-1-gif](https://github.com/EsotericSoftware/spine-editor/assets/85478846/a77669ce-710b-4a54-8d61-79b92edd4d4d)
*`Crop` was not checked in the export settings and exported with the automatically detected boundary.

However, in 4.2, the boundary set by clipping attachments is ignored and the size of the entire animation is recognized as the maximum boundary. Here is the result of reopening the Spine 4.1 project that exported the above GIF in 4.2 and exporting the `jump` animation again:
![4-2-gif](https://github.com/EsotericSoftware/spine-editor/assets/85478846/f1cdc248-f2be-45a4-8436-21e6156a731e)

**Expected behavior:**
If the entire skeleton is clipped with a clipping attachment, the boundary of the clipping attachment is automatically recognized as the boundary for image export, as worked in 4.1.

**Steps to reproduce:**
1. Download the attached .zip file: [Spineboy-4-1-with-ClippingAttachment.zip](https://github.com/EsotericSoftware/spine-editor/files/15005184/Spineboy-4-1-with-ClippingAttachment.zip)
2. Open the Spine project in it using Spine 4.2.00.
3. Export the `jump` animation in the GIF format.
4. If you look at the exported GIF file, you will see that a large margin has been left at the top.

**The version of Spine in which this bug was found:**
Spine 4.2.00

**This issue was reported on the following thread:**
https://esotericsoftware.com/forum/d/26002-some-problem-after-update-to-version-42-

**Comment by NathanSweet** [comment]
****
