### ISSUE TITLE
The `Range` option may not appear when exporting animations in the GIF format

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#790]
**Description:**
When exporting animations in GIF format, the `Range` option may not display properly due to some conditions. The conditions are unclear, but I have confirmed that the `Range` option appears correctly when the complexity of the skeleton is reduced.

**Expected behavior:**
The `Range` option appears when exporting an animation (or animations).

**Steps to reproduce:**

1. Download the attached .zip file: [Range_option_does_not_appear.zip](https://github.com/EsotericSoftware/spine-editor/files/15084598/Range_option_does_not_appear.zip)
1. Open the Spine project in it using Spine 4.2.08.
2. Press Ctrl+E to open the Export window. You should see the following settings:
![Screenshot 2024-04-24 at 10 04 44](https://github.com/EsotericSoftware/spine-editor/assets/85478846/c2de28ac-5ee7-4102-ba68-689ef7287b37)
(If you try switching between `Current` and `All` in the `Animations` option or switching `Output type` in this state, you can confirm that the switch is a little slow.)
3. Close the Export window once and delete a bone named `bone5` in the skeleton.
4. Open the Export window again in that state. Immediately after opening, you will not see the `Range` option, but if you switch between `Current` and `All` in the `Animations` option, you should see that the `Range` option appears.
Once it appears, it will always appear after that, even if you reopen the export window:
![Screenshot 2024-04-24 at 10 11 16](https://github.com/EsotericSoftware/spine-editor/assets/85478846/7d124023-bc97-4c76-ba43-c5696418bde9)

**The version of Spine in which this bug was found:**
Spine 4.2.08

**This issue was reported on the following thread:**
https://ja.esotericsoftware.com/forum/d/26033-gif%E5%B0%8E%E5%87%BA%E5%95%8F%E9%A1%8C/4

**Comment by misaki-eymard** [comment]
If you check the `Bones` checkbox in the repro step 3 and run the export, you will get a GIF image of only the pose at frame 0, even though the correct animation duration is `480` frames:
![exported-gif](https://github.com/EsotericSoftware/spine-editor/assets/85478846/6667cabb-07d4-463e-adb8-ccf56fb8792f)

As you can see in the attached screenshot in step 5, when the `Range` option appears, its parameter is set to "0 to 0". Therefore, I suspect that an incorrect range has been set and the animation will not be exported properly.

**Comment by NathanSweet** [comment]
4.2.09

**Comment by misaki-eymard** [comment]
I checked this with 4.2.11, but it does not seem to be completely fixed. When I open the Spine project I attached to this issue ticket to reproduce the problem, the Range option itself is displayed, but the maximum number of frames for the animation is not displayed:
![animation-range](https://github.com/EsotericSoftware/spine-editor/assets/85478846/47d45205-bec5-4600-80c3-dd69991ecac5)

**Comment by NathanSweet** [comment]
When the project is too complex for preview to complete, we aren't able to accurately determine the number of frames or export sizes.

In 4.2.12 we've improved this so it still computes the frames. We still won't have the sizes, which affects the values shown for crop. That has been improved though. To see the crop values you may need to open the preview and click `Reset`, which gives the preview 20 seconds instead of 2 seconds to complete. If it completes in time, we have sizes and the crop values are updated.
