### ISSUE TITLE
Slot order is incorrect after changing the draw order in animate mode

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#791]
**Description:**
If the drawing order is changed while multiple slots are selected in animate mode, the slot order is incorrect. For example, suppose the slots are lined up as shown in the following image:
![Screenshot 2024-05-06 at 12 49 47](https://github.com/EsotericSoftware/spine-editor/assets/85478846/547736c8-5095-4dee-8ee6-60cbb4b14f9a)
Select `slot1` and `slot2` and move over `slot3`.
![move-slots](https://github.com/EsotericSoftware/spine-editor/assets/85478846/c358fe8e-38fb-410f-ae0f-30e1b0e57ec4)
After the move, the order of `slot1` and `slot2` will be swapped, as shown below:
![Screenshot 2024-05-06 at 12 52 58](https://github.com/EsotericSoftware/spine-editor/assets/85478846/7b76cb13-e5fb-4483-b7b2-7faed7b52127)

**Expected behavior:**
The order does not change among the selected slots. In the example above, the order of `slot2` up and `slot1` down should be maintained after the move.
![Screenshot 2024-05-06 at 12 53 27](https://github.com/EsotericSoftware/spine-editor/assets/85478846/12943dcd-e17b-4711-88c8-f85b57209c63)

**Steps to reproduce:**
1. Open the spineboy-pro.spine via the Examples section on the welcome screen.
1. Switch to the animate mode.
1. Select the `muzzle-ring` and the `muzzle-ring2` slots under the `Draw order` section in the tree view.
1. Drag and drop them to over the `muzzle-ring4` slot. Then, you can see the `muzzle-ring` slot is on top and the `muzzle-ring2` slot is below it.

**The version of Spine in which this bug was found:**
Spine 4.2.19

**This issue was reported on the following thread:**
https://esotericsoftware.com/forum/d/26117-modify-layer-order-default-order-error

**Comment by NathanSweet** [comment]
I don't remember which change fixed this, but I don't see it happening in 4.2.21.
