### ISSUE TITLE
The key buttons for the slots disappear when you use the tree filter to display only the slots

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#792]
**Description:**
In animate mode, if you use the tree filter in the tree view to show only the slots, the key buttons that should be next to each slot will disappear.

![in-4-2-19](https://github.com/EsotericSoftware/spine-editor/assets/85478846/e35e673b-4b9c-4892-843d-79be9c8e97ec)

**Expected behavior:**
As was the case up to version 4.1, key buttons are displayed next to each slot, even if only the slots are displayed in the tree view.

![In-4-1-24](https://github.com/EsotericSoftware/spine-editor/assets/85478846/af818e70-eebe-41ad-a250-6566f2552153)

**Steps to reproduce:**
1. Open any Spine project in Spine 4.2.19 and switch to Animate mode.
2. Activate the filter button for the slots in the tree view so that only the slots are displayed. You will notice that the key buttons next to each slot will disappear.

**The version of Spine in which this bug was found:**
Spine 4.2.19

**This issue was reported on the following thread:**
https://esotericsoftware.com/forum/d/26119-after-filtering-the-slots-the-slot-k-frame-button-is-not-visible

**Comment by NathanSweet** [comment]
4.2.20
