### ISSUE TITLE
Allow the size of the soft selection to be changed using hotkeys when the weight mode is `Direct`.

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#797]
Currently, regardless of the weight mode, it is no longer possible to change the size and feather of the soft selection using the `Brush+: '''`, `Brush-: ';'`, `Feather+: '"'`, or `Feather-: ':'` hotkey when the `Weight` tool is active. When using brush modes such as `Add`, `Remove`, and `Replace`, this behavior is correct, but when using `Direct`, it is possible to use both `Direct` and the soft selection, so it should be possible to change the size and feather of the soft selection from the hotkeys.

**Related forum thread:**
https://esotericsoftware.com/forum/d/26320-%EA%B0%80%EC%A4%91%EC%B9%98-%EC%A1%B0%EC%A0%95-%EC%8B%9C-%EB%B8%8C%EB%9F%AC%EC%8B%9C-%EC%82%AC%EC%9D%B4%EC%A6%88-%EB%8B%A8%EC%B6%95%ED%82%A4-%EB%AC%B8%EC%A0%9C

**Comment by NathanSweet** [comment]
4.2.30
