### ISSUE TITLE
Using the `New - New Folder` hotkey to create a folder for slots causes a crash

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#799]
**Description:**
When using the `New - New Folder` hotkey to create a folder for slots, a dialog for naming the folder appears, and after entering any name, the editor crashes. This hotkey can be used to create a folder for constraints without any problems.

**Expected behavior:**
This hotkey can also be used without any problems when creating folders for slots.

**Steps to reproduce:**
1. First, assign any key to `New - New Folder` in hotkey.txt. (By default, no key is assigned to this hotkey.)
1. Open spineboy-pro.spine.
1. Select any folder in the Draw order section of the Tree view and press the hotkey you set.
2. A dialog will appear asking you to enter a folder name, so enter any name and click OK. The editor then crashes.

**The version of Spine in which this problem was found:**
Spine 4.2.29

**Comment by NathanSweet** [comment]
4.2.30
