### ISSUE TITLE
The `Focus - <ViewName>` hotkeys are only recognized when the target view is active

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#800]
**Description:**
Using the `Focus - <ViewName>`  hotkeys should allow you to switch between active views, but in 4.2.29 the hotkeys are only recognized when the hotkey you pressed matches the currently active view, and you cannot switch between active views. For example, `Focus - Dopesheet` is only available when the Dopesheet is active, and using `Focus - Tree` when the Dopesheet is active will not be recognized. The same is true in reverse. The following video shows this behavior:
https://github.com/EsotericSoftware/spine-editor/assets/85478846/21073e49-e404-4709-ab28-40aa2a829375

**Expected behavior:**
All of these hotkeys are recognized regardless of which view is active.

**Steps to reproduce:**
1. First, assign any key to `Focus - Dopesheet` and `Focus - Tree` in hotkey.txt. (By default, no key is assigned to these hotkeys.)
2. Create a new Spine project or open any Spine project.
3. Press `ctrl + shift + K` first to show the hotkey popups so that you can see the easily check that the hotkey is being recognized.
4. Try pressing the hotkeys while the Dopesheet view and Tree view are displayed. You will see that when the Dopesheet is active, `Focus - Dopesheet` is recognized, but `Focus - Tree` is not.

**The version of Spine in which this problem was found:**
Spine 4.2.29

**Comment by NathanSweet** [comment]
4.2.30
