### ISSUE TITLE
The `Favor - <ModeName>` hotkeys do not work

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#802]
**Description:**
The hotkeys for switching the Favor tool's mode are recognized as having been pressed, but those does not actually switch the mode. The following hotkeys are the ones that do not work:
- `Favor - Favor`
- `Favor - Blend`
- `Favor - Shift`
- `Favor - Linear`
- `Favor - Average (curve)`
- `Favor - Average (frame)`
- `Favor - Average (all)`
- `Favor - Default`
- `Favor - Setup`
- `Favor - Store`

Here is a video recording of this issue:
https://github.com/EsotericSoftware/spine-editor/assets/85478846/3c37bb9c-080f-48ca-8707-d746c563814d

**Expected behavior:**
Pressing the key assigned to each hotkey switches the mode of the Favor tool.

**Steps to reproduce:**
1. First, assign any key to the `Favor - <ModeName>` hotkeys in hotkey.txt. (By default, no key is assigned to these hotkeys.)
1. Open spineboy-pro.spine.
1. Switch to the animate mode and display the Favor tool in the Graph view.
2. Press `ctrl + shift + K` first to show the hotkey popups so that you can see the easily check that the hotkey is being recognized.
3. Try switching between the Favor tool modes using hotkeys by pressing the assigned keys. The name of the corresponding hotkey will then pop up, but you can see that the Favor mode itself does not switch.  

**The version of Spine in which this issue was found:**
Spine 4.2.29

**Comment by NathanSweet** [comment]
4.2.30
