### ISSUE TITLE
When switching between Setup and Animation modes, the content selected in the viewport may change due to the tree filter.

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#804]
**Description:**
For example, if you use the tree filter to display only bones in the tree view, then select a mesh attachment in the viewport, and then switch from Setup to Animation mode, the selection will switch to the parent bone of that mesh attachment. This does not happen in 4.1.24, and the selection of the mesh attachment is retained even when switching from setup to animate mode, so it seems that this behavior is a bug that was caused by a modification that was added in 4.2.

**Expected behavior:**
Even if you are using the tree filter and have selected an item in the viewport that is not target of the filter, the selection will be retained when switching between setup mode and animate mode.

**Steps to reproduce:**
1. Open spineboy-pro.spine.
2. In the tree view, turn on the bone filter.
3. In the viewport, select the head mesh attachment.
4. Switch between setup mode and animate mode and you will see that the parent bone is selected instead of the selected mesh attachment.

**The version of Spine in which this problem was found:**
Spine 4.2.29

**This bug was reported in the following forum thread:**
https://esotericsoftware.com/forum/d/26278-%E5%90%8C%E6%A0%B7%E7%9A%84bug%E8%BF%99%E6%AC%A1%E5%87%BA%E7%8E%B0%E5%9C%A8%E9%AA%A8%E9%AA%BC%E4%B8%8A%E9%9D%A2/9

**Comment by NathanSweet** [comment]
This was also reported here, by the same user:
https://esotericsoftware.com/forum/d/25768-bugs-in-grid-functionality
We made changes in 4.248-beta and 4.2.50-beta. The user never reported back until now.

When changing setup/animate mode, the viewport selection is set from the tree selection. The bone is selected in the tree, so it is selected in the viewport.

It seems safe to not do this. If a region attachment is selected in setup mode, we already handle it losing the selection in animate mode. Changed in 4.2.30.
