### ISSUE TITLE
Cannot deselect bones or region attachments by double-clicking the empty space.

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#805]
**Description:**
There is a bug in Spine 4.2.31 where you cannot deselect bones or region attachments even if you double-click on an empty space in the viewport. (Incidentally, attachments that involve vertices, such as meshes and clipping, can be deselected by double-clicking on an empty space without any problems.)

**Expected behavior:**
Even if you have selected bones or region attachments, you can deselect them by clicking on an empty space in the viewport.

**Steps to reproduce:**
1. Open spineboy-pro.spine with Spine 4.2.31.
2. Click on any bone in the viewport.
3. Double click on an empty space, then you can see that the current selection cannot be deselected.

**The version of Spine in which this problem was found:**
Spine 4.2.31

**This problem was reported in the following thread on the forum:**
https://esotericsoftware.com/forum/d/26383-bug4231%E7%89%88%E6%9C%AC/2

**Comment by NathanSweet** [comment]
4.2.32
