### ISSUE TITLE
Slot alpha animations may not be exported correctly in GIF format if there is little difference in color changes.

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#808]
**Description:**
If the color of the background image is light and you then animate the alpha value of a light-colored image on top of it, the animation may not be exported properly when exporting as a GIF. This only occurs when the `Background` is set to `Transparent` in the GIF export settings.

**Expected behavior:**
The animation will be exported as it appears in the editor's viewport and in the preview window of the export window.

**Steps to reproduce:**
1. Download the attached .zip file: 
[Alpha-animation-issue.zip](https://github.com/user-attachments/files/15981248/Alpha-animation-issue.zip)
1. Open the Spine project in the .zip file using Spine 4.2.32.
1. Switch to animate mode and check that the animation of the central white star blinking can be played:
https://github.com/EsotericSoftware/spine-editor/assets/85478846/5eaf5024-dfc1-4577-b29d-429600fdf38c
1. Open the Export window and export the animation with the default settings:
![Screenshot 2024-06-26 at 10 45 16](https://github.com/EsotericSoftware/spine-editor/assets/85478846/b341145a-e537-4ff4-bd8b-53f52e7386e2)
1. You can see that the exported GIF has multiple frames, but the alpha value of the central star has become constant, and the animation of the flickering has disappeared.
![Alpha-animation-0-to-100](https://github.com/EsotericSoftware/spine-editor/assets/85478846/7b62b463-14bc-4788-bc07-1a9566cf2d15)

**Workarounds to this issue:**
There are workarounds for this problem, such as the following:
- Uncheck the `Transparent` box for Background and select `Matte` in the export settings.
- Darken the color of the background image.
- Increase the change in alpha value of the blinking slot.
- Move the parent bone of the blinking slot.

**The version of Spine in which this problem was found:**
Spine 4.2.32

**This problem was reported in the following thread on the forum:**
https://esotericsoftware.com/forum/d/26415-trouble-with-gif-export

**Comment by NathanSweet** [comment]
GIF is not a good choice for subtle color changes. While it's not clear why it only happens when transparency is checked (maybe due to having one fewer colors in the palette), setting `Speed` to `Low (slowest)` fixes it (uses more processing to produce better results). That indicates it's part of the GIF quantization and other color processing. That is very complex and probably not worth debugging further.

APNG or AWEBP or WEBM are much better, more modern formats.
