### ISSUE TITLE
Allow `Export all` option also in binary export

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#812]
Currently, the Export all option is only available for JSON exports, but it would be useful to have it available for binary exports as well, since this option is useful in some cases, such as when upgrading the editor and the runtime versions.

**Related forum thread:**
https://esotericsoftware.com/forum/d/26465-spine-cli-export-option-for-specific-skeleton

**Comment by NathanSweet** [comment]
The binary format is not very good at moving between versions. Literally _any_ change to the format will cause another version to fail to parse it. Given that, there doesn't seem to be a compelling reason to have "export all" for binary.

We've added `--export-all` which will make it so all skeletons are always exported (CLI and editor). This will be available only once we've done the next launcher (4.2.18) and editor (4.2.34) updates, which may be some time.
