### ISSUE TITLE
Timeline bar does not move when playing an animation that has no keys

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#815]
**Description:**
Up to Spine 4.2.22, even if an animation had no keys at all, the timeline bar would move when played with the loop disabled, but in Spine 4.2.23 or later versions, it seems that the timeline bar will not move unless the animation duration is more than one frame.

Here is a video that demonstrates this issue:
https://github.com/EsotericSoftware/spine-editor/assets/85478846/8dd83acd-150a-4aeb-a9df-4b6b2481efc8

**Expected behavior:**
With animation looping disabled, the timeline bar moves even when playing an animation with no key.

**Steps to reproduce:**
1. Create a new Spine project with Spine 4.2.33.
2. Switch to animate mode, disable the loop, and press the play button.
3. Then playback stops on its own and you will see that the timeline bar does not move at all.

**The versions of Spine in which this issue was found:**
Spine 4.2.23 - 33

**This issue was reported in the following thread on the forum:**
https://esotericsoftware.com/forum/d/26483-%E6%A9%9F%E8%83%BD%E8%A6%81%E6%9C%9B/2

**Comment by NathanSweet** [comment]
This was changed purposefully to fix another issue:

> Fixed looping in reverse when playback interpolation is disabled.

The reason the user preferred the old behavior:

> When I first created the motion, I roughly measured the length of the frame while playing it in my head

That seems reasonable, fixed in 4.2.34.
