### ISSUE TITLE
`Polygons` packing fails in Spine 4.2.34 depending on image

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#818]
**Description:**
For some reason, `Polygons` packing fails in Spine 4.2.34, depending on the image used. This occurs even if that image is not a mesh attachment. This may be a problem specific to 4.2.34, as it has been confirmed that the same image can be packed with `Polygons` in Spine 4.2.33.

The error log for this problem is as follows
```
WARNING: Error packing images:
[error] Unable to process polygon for image: muzzle-ring
   at s.yyq._(_:489)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   at java.lang.Thread.run(Unknown Source)
Cause: [error] Image: muzzle-ring
   at s.yyq._(_:487) ...
```

**Expected behavior:**
`Polygons` packing can be done successfully.

**Steps to reproduce:**
1. Download the attached .zip file: [Polygons-packing fails-for-some-reason.zip](https://github.com/user-attachments/files/16490428/Polygons-packing.fails-for-some-reason.zip)
1. Open the Spine project contained in that zip with Spine 4.2.34.
2. Pack textures with setting the texture packer settings as follows (All settings are defaults except that `Packing` is set to `Polygons`.):
![Screenshot 2024-08-05 at 12 50 46](https://github.com/user-attachments/assets/306a91db-bf19-4d8d-8415-e4541a40791e)
1. Then, you should see the following error message:
![Screenshot 2024-08-05 at 12 51 56](https://github.com/user-attachments/assets/eeb4f823-36f1-4316-ae33-c47099604ae5)
The spine.log file should output an error as described in the Description.

This problem also can be reproduced by simply creating a new Spine project and placing the two images that were included in the zip file: `muzzle-glow.png` and `muzzle-ring.png`.
This problem does not occur when just placing either of these images. Also, no error occurs when packing with `Rectangles`.

**The version of Spine in which this issue was found:**
Spine 4.2.34

**This issue was reported in the following thread on the forum:**
https://esotericsoftware.com/forum/d/26633-an-error-occurred-while-packing-the-images-ver-4234

**Comment by davidetan** [comment]
Reported also here:
- https://esotericsoftware.com/forum/d/26642-error-packing-images/
- https://esotericsoftware.com/forum/d/26640-%E6%B1%82%E5%8A%A9%E6%B1%82%E5%8A%A9%E5%BF%83%E6%80%81%E8%A6%81%E8%A2%AB%E6%90%9E%E7%82%B8%E4%BA%86
