### ISSUE TITLE
Key icons still use yellow

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#82]
We changed the changed state for key icons to orange, but some icons are still yellow.

![](http://n4te.com/x/384-i524.png)

This blocks badlogic/spine-internal#68

**Comment by Shiu** [comment]
Icon color is set in code. 
Changed:
keyEdit = skin.newDrawable("button-key", new Color(1, 0.78f, 0, 0.75f));
		keyEditOver = skin.newDrawable("button-key", Color.ORANGE);

To:
keyEdit = skin.newDrawable("button-key", Color.ORANGE);
		keyEditOver = skin.newDrawable("button-key", new Color(1, 0.78f, 0, 0.75f));

**Comment by NathanSweet** [comment]
Over color is too dim, should be brighter than normal color, like the green key button.

**Comment by Shiu** [comment]
Colors are now the same as main toolbar keys

**Comment by NathanSweet** [comment]
Verified, thanks!
