### ISSUE TITLE
Middlemouse + Ctrl to zoom is inverted and inconsistant with other software and mouse wheel-behaviour

### ISSUE THREAD

**Issue by bencresty** [EsotericSoftware/spine-editor#828]
When working with mouse zooming is simple; rotate mousewheel UP = zoom in, mousewheel DOWN = zoom out. And works just like in other applications.

When working with a pen however we don't have a mousewheel, so we set a pen button to simulate a MiddleMouse-button and hold Ctrl while dragging to zoom in/out.

However, when using Ctrl+mmb (with a wacom pen) it's now suddenly zooming the other way, compared to the mouse wheel, but also compared to other software, like blender; now a pendrag UP = zoom out, pendrag DOWN = zoom in. So the opposite direction of other software and even compared to the mousewheel behaviour in spine itself.

Could this behaviour either be inverted in Spine by default, or could we get an option to invert this Ctrl+mmbDrag zoom behaviour?

That would be very appreciated as while constantly switching between spine, blender and other software it's counter intuitive and not that nice that spine works differently in this regard. It's hard to get used to.

Thanks for considering!

**Comment by misaki-eymard** [comment]
I found that there is already an issue that is quite similar, so I added a link there. I think we can close this ticket.

**Comment by bencresty** [comment]
> I found that there is already an issue that is quite similar, so I added a link there. I think we can close this ticket.

Yeah, it looks like the same thing indeed. Sorry for not having found that one.
