### ISSUE TITLE
If the target path is deformed during animation, the path-constrained movement is not correctly reflected in the physics during export.

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#838]
**Description:**
If the target path of a path constraint is deformed during animation, the movement obtained from the path constraint may not be correctly reflected in the physics constraints of the bones constrained by the path constraint when exporting. This problem occurs when exporting animations as images or videos.

**Expected behavior:**
The physics results as seen in the viewport will also be reflected in the exported images and videos.

**Steps to reproduce:**
1. Download the attached .zip file: [path-constrained movement is not correctly reflected in the physics.zip](https://github.com/user-attachments/files/17158958/path-constrained.movement.is.not.correctly.reflected.in.the.physics.zip)
2. Open the Spine project and play the animation. You will see the animation as shown in the following video:
https://github.com/user-attachments/assets/478c4ddd-0868-4c9a-87d6-8aa163744649
1. After checking the animation, export it as an animated GIF. The result of the export will look like this:
![exported-gif](https://github.com/user-attachments/assets/26719062-a491-45ee-aa2a-64aa5ef88d1c)
1. To confirm that this is the effect of the path being deformed, select the path and delete the deform key at frame 0. After deleting the deform key, the movement you can see in the viewport will be like this:
https://github.com/user-attachments/assets/d0c4a4b8-7dac-4495-a23d-6d941d19963e
1.  Export the animation again with the same settings as Step 3. It will be the same as the one you checked in Step 4, as shown below.
![exported-gif2](https://github.com/user-attachments/assets/f0af8cf0-2b4b-45db-ade0-1b5ce49d6512)

**The version of Spine in which this issue was found:**
4.2.36

**This problem was reported by email:**
FMfcgzQXJQMjxsgbdSGbdpqMjDsSKbCW

**Comment by NathanSweet** [comment]
Exporting makes it more complex to reproduce. Checking `Deterministic` (which is similar to what export does) shows the issue more easily.

**Comment by NathanSweet** [comment]
Simplified repro:
http://n4te.com/x/588-path-physics-issue.spine

**Comment by NathanSweet** [comment]
4.2.37
