### ISSUE TITLE
Ensure that the clipped slots are highlighted in the tree view even if the clipping attachment belongs to a skin.

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#841]
Currently, if a clipping attachment belongs to a skin, the highlight and scissors icons indicating the start and end slot are not displayed in the Draw Order node of the tree view, even if the skin is active. It would be easier if you could see the highlight of the clipped slot when clipping is enabled, even if the clipping attachment belongs to a skin.

Related forum thread:
https://esotericsoftware.com/forum/d/27090-help-i-cant-get-clipping-masks-in-skin-placeholders-to-work--

**Comment by NathanSweet** [comment]
4.2.37
