### ISSUE TITLE
Color management is not applied to the display in the Preview view

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#847]
**Description:**
Changing the `General - Color management` to `Linear blending` in the Spine settings changes the color of the skeleton's appearance in the viewport, but the appearance in the Preview view remains the same as in the gamma-blended display:
![Screenshot 2024-10-29 at 11 30 12](https://github.com/user-attachments/assets/8a45cf06-c9aa-4562-8580-9e38fab973b0)

**Expected behavior:**
The appearance in the Preview view matches the appearance of the skeleton on the viewport.

**Steps to reproduce:**
1. Run Spine 4.2.36 and set `General - Color management` to `Linear blending` in the Spine settings window.
2. Restart Spine 4.2.36 and open spineboy-pro.spine.
3. Switch to the animate mode and open the Preview view.
4. Set the active animation to hoverboard in both the viewport and the Preview view.
5. You will notice that the colors are different between the viewport and the Preview view if you look at the hoverboard light VFX area and compare them.

**The versions of Spine that can reproduce this issue:**
4.2.36

**This issue was reported in the following thread on the forum:**
https://esotericsoftware.com/forum/d/27146-spine-examples-show-different-effect-in-linear-color-space-and-gamma-color-space

**Comment by NathanSweet** [comment]
4.2.37
