### ISSUE TITLE
Open output folder when complete checkbox

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#85]
Similar in functionality to the "Show extracted files when complete" checkbox when you unzip a zip file on Windows.

Possible wording:
"Open folder when complete"

When checked, after you export, it opens the output folder in a new explorer/finder window. So the user can confirm that the correct files were exported, was exported in the correct folder, and the user can move or copy them to another folder (or send them off to their programmer) if needed. It's useful for non-SkeletonData exports too, like for gifs, videos and image sequences.

**Comment by NathanSweet** [comment]
3.7
