### ISSUE TITLE
The first playback in the Preview view does not correctly reflect motion created by curves

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#858]
**Description:**
When playing an animation in Preview view, even if Mix is set to 0, the first playback does not correctly reproduce the motion created by the curves in Graph view. Here is a video where you can see this issue:
https://github.com/user-attachments/assets/d01a9945-8c5c-4fd2-88e0-7b129c2e6f17
If you focus on the area around the edge of the sliding image in the center, you will notice that the amount of movement in the first anticipation is different in the first playback than in the second playback.

The translating animation shown in the video is created by the following simple curves:
![Screenshot 2024-12-13 at 17 55 41](https://github.com/user-attachments/assets/b7b9e61c-8452-444f-b11f-cdf5a9548d01)

**Expected behavior:**
If the mix is set to 0, the result played back in the Preview view will be the same as the playback result seen in the viewport.

**Steps to reproduce:**
1. Download the attached .zip file: [The first playback in the Preview view does not correctly reflect motion created by curves.zip](https://github.com/user-attachments/files/18123850/The.first.playback.in.the.Preview.view.does.not.correctly.reflect.motion.created.by.curves.zip)
1. Unzip the .zip file and open the Spine project in it with Spine 4.2.37.
1. Open the Preview view and set the value of Mix in the Preview view to 0.
1. Play the animation “open”. You will see that the movement of the center image (door) is different from the first playback to the second and subsequent ones.

**Workaround:**
If you play back with Mix set to a value other than 0, such as 0.2, and then play back with Mix set to 0, it appears to play back correctly even on the first play.

**The version of Spine in which this issue was found:**
4.2.37

**This issue was reported in the following thread on the forum:**
https://esotericsoftware.com/forum/d/27828-preview-inconsistency

**Comment by NathanSweet** [comment]
4.2.38
