### ISSUE TITLE
Frame-by-frame animation support

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#9]
Keying each frame change is tedious. We could have a "region sequence attachment" which shows images sequentially.

**Comment by dreadicon** [comment]
This would be extremely useful for our use case; png sequences are commonly needed for smoke, light effects, etc. in our pipeline.

**Comment by erikari** [comment]
Here's a +1 for this: http://esotericsoftware.com/forum/Request-wishes-separatewindows-groupbindings-and-more-11244

**Comment by NathanSweet** [comment]
We will still do this, likely in 4.1, but until then a user made a script to help:
https://www.youtube.com/watch?v=c9-UdM7oHKg

**Comment by NathanSweet** [comment]
Added in 4.1.00-beta.
