### ISSUE TITLE
User reported crash when reordering bones in Weights view.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#92]
http://esotericsoftware.com/forum/Program-crash-when-using-weights-6891

**Comment by pharan** [comment]
Tried it with Raptor. Seems fine. There must be something about the setup.

**Comment by NathanSweet** [comment]
Can't do much without this without a way to repro.

**Comment by NathanSweet** [comment]
User emailed project but didn't include steps to repro. Belly mesh seems to work fine for me. Will reopen if repro steps are provided.

BTW, we shouldn't open issues until we have all the information to be able to work on it. Too often it is never provided and we don't want to keep around issues that we can't do anything about. Also, we should link the issue in the forum post so people know that discussion and/or work is being continued.

**Comment by AlstonA** [comment]
Hello, I haven't been able to reproduce the issue again. I'm not sure what happen but its up and running again.
