### ISSUE TITLE
Clicking an attachment's visibility dot may be a bit confusing

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#93]
With the new visible-on-hover behavior for attachments, toggling the visibility dot may be confusing especially for new users.

![](https://cloud.githubusercontent.com/assets/1911082/18032021/8d08f29c-6d2b-11e6-8ef8-ccd188052ad1.gif)
Current:
When you turn the visibility dot off, it just blinks but is still visible.
It doesn't disappear until you move your mouse away from the item (which new users may not think to do).

Expected:
If you click on the visibility dot, it show the actual state of the slot as feedback according to the change you just made.
But if you hover over it again later, it should have the visible-on-hover behavior.

**Comment by NathanSweet** [comment]
3.5.00-beta
