### ISSUE TITLE
Selection in Animations view should not affect Tree view.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#95]
http://esotericsoftware.com/forum/Request-Stop-Hierarchy-autoselect-Animation-6946

Animations view is there so you don't have to select animations in Tree view and scroll away from what you're working on.

But currently, selecting an animation in Animations view selects it in Tree view, and that makes you lose your previous selection in the Tree. If the tree is expanded enough, and if you have enough animations in your list, it will also scroll your original selection out of view.

This is very annoying if you need to modify and key a slot across multiple animations.

**Comment by NathanSweet** [comment]
Is it sufficient to disable auto scrolling in the tree when selecting the animation isn't wanted?
http://esotericsoftware.com/spine-tree#Auto-Scroll

**Comment by Xelnath** [comment]
Hurray :D

**Comment by pharan** [comment]
hmm...
Assuming disabled auto-scrolling but still selects the animation in the tree.

What it handles:
- having to swap attachments in multiple animations. (no scrolling means the slot stays in view)
- manipulating bones in multiple animations. (the viewport selection seems to stay intact)

What it doesn't handle:
- changing slot color in multiple animations (you lose your tree selection every time you switch animations)
- changing constraint properties in multiple animations (you lose your tree selection every time you switch animations)

**Comment by NathanSweet** [comment]
OK, in 3.5.01 the Animations view won't change the tree properties when auto scroll is disabled.

**Comment by NathanSweet** [comment]
Let's change the Animation view to never scroll the tree, regardless of tree auto scrolling. We might also add a select-in-tree button to provide access to delete, clean up, etc.

**Comment by NathanSweet** [comment]
The `Animations` view no longer selects the animation in the tree, unless the selected animation is clicked a second time. 3.5.48
