### ISSUE TITLE
Export GIF: "frame buffer couldn't be constructed"

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#96]
OP posted a spine log.
http://esotericsoftware.com/forum/Export-GIF-error-6971

forum user **mfedorov** thinks this is the problem:
http://troikatronix.com/troikatronixforum/discussion/167/images-4096-pixels-wide-don-t-work-with-intel-hd-graphics-3000

**Comment by NathanSweet** [comment]
Similar to #115, with huge images sometimes OpenGL pukes, especially with lower end GPUs. Not much we can do since we use OpenGL to export. Who really wants a 5598 x 3604 GIF anyway?
