### ISSUE TITLE
New images incorrectly placed if root bone is not at origin.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#97]
When you drag an image from the Images node into a slot, the attachment is positioned at:
`world position of slot.bone` + `the root bone's offset from the (0, 0) point`.
Obviously, that second offset shouldn't be there.
See the forum thread for gifs.

Repro:
Spineboy's root bone (`hip`) is elevated several units. Dragon's root bone too.
http://esotericsoftware.com/forum/New-attachment-s-initial-position-6982

**Comment by NathanSweet** [comment]
3.5.00-beta
